### ISSUE TITLE
Update documentation about no python2.7 support

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openforcefield#110]
In PR #108 we removed travis tests for python2.7. We have not updated all documentation around that change. @davidlmobley suggested
> Update docs in a separate PR to note that py27 may still work but is no longer supported?

I would add and we recommend using python3 instead (potentially pointing to how easy this is with conda?

**Comment by davidlmobley** [comment]
Agreed, yes, @bannanc .

**Comment by jchodera** [comment]
The [README](https://github.com/openforcefield/openforcefield/blob/master/README.md) now mentions the supported versions of python.
