### ISSUE TITLE
Improve SMIRNOFF example READMEs

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#113]
As of the topology revamps coming in soon in a WIP PR, the docs for the examples will be pushed automaticlly online based on the READMEs. This means that the READMEs need improvement, as right now they don't document clearly enough what each example is.

**Comment by jchodera** [comment]
Please update the READMEs via PRs to the `topology` branch rather than the `master` branch, however!

**Comment by jchodera** [comment]
I think this has been solved in 0.2.0!
