### ISSUE TITLE
openforcefield and openforcefield-tools naming clash

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openforcefield#14]
We have openforcefield as the setup name in [this repo](https://github.com/open-forcefield-group/openforcefield/tree/master/openforcefield) and the [openforcefield-tools repo](https://github.com/open-forcefield-group/open-forcefield-tools/tree/master/openforcefield). 

If I wanted to install the tools from both of these wouldn't they overwrite each other?

**Comment by davidlmobley** [comment]
Yes, though there is not much in `openforcefield-tools`. The name there should be changed.

**Comment by bannanc** [comment]
@jchodera 
Should we think about renaming or potentially combine these?

**Comment by davidlmobley** [comment]
We've archived or deleted `openforcefield-tools`; closing.
