### ISSUE TITLE
Add a test that energies/forces are correct in systems with multiple molecules

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#152]
At one point I ran into an issue with problems in systems containing multiple molecules, as most of our tests relating to **correctness** only run on single molecules; the multi-molecule tests typically just check that such systems can process. We should add a test relating to energies/forces on a system with multiple molecules.

**Comment by jchodera** [comment]
Testing the energies and forces are "correct" is difficult without either creating a totally independent codepath to generate parameters and compute energies or manually checking a few systems and hard-coding energies for these reference systems. 

Are there instead simpler things we could check that would catch the _class_ of bugs you ran into? 
For example:
* Check that two molecules at very large separation in vacuum is about twice the single-molecule energy
* Check that two molecules next to each other is not the same as one molecule or two molecules at infinite separation

These are examples of very easy to create tests that would catch whole classes of bugs that are of this character.

**Comment by davidlmobley** [comment]
@jchodera Note that we provide a minimal AlkEthOH forcefield in the repo in both AMBER and SMIRNOFF formats, and test that SMIRNOFF energies for an individual molecule match between the AMBER format version and the SMIRNOFF format version. I would propose we do exactly the same, but for a system consisting of multiple molecules. This would have caught the issues I encountered.

**Comment by jchodera** [comment]
That could work! However, the files here are only mol2 files and parameterized crd and top files for single molecules:

https://github.com/openforcefield/openforcefield/tree/master/openforcefield/data/molecules

We can't use these to generate Amber files for two or more molecules. So we have Tripos mol2 and frcmod files for these molecules somewhere? If so, we can use leap to generate the systems you suggest---ideally small clusters of two or more molecules so we don't need to worry about differences in nonbonded treatment between packages.

**Comment by andrrizzi** [comment]
I remember I had to fix a similar issue too two years ago (see #30). I'll take care of adding the test.

**Comment by davidlmobley** [comment]
Thanks, @andrrizzi . Your past work is probably why I (a) thought we'd already done this, and (b) had the workflow clearly in my mind.
