### ISSUE TITLE
Move imports inside functions

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#155]
If we move `import`s into functions, only importing packages when needed, importing and using the toolkit will be a quicker, cleaner user experience for most users. We should apply this principle generally throughout the toolkit (though this is not necessary for the tests).

**Comment by jchodera** [comment]
1. ["Premature optimization is the root of all evil."](http://wiki.c2.com/?PrematureOptimization). We should not be concerned with optimization unless (1) we know performance is poor, and (2) we have evidence that this is a significant contributor.
2. We _control_ the entire installation environment via conda packaging. If a dependency is missing, it's our fault, and we should catch that with tests---not with a top-level import.

Are there other reasons besides these two that may be compelling?

**Comment by andrrizzi** [comment]
> "Premature optimization is the root of all evil."

Completely agree, but that also applies to move the import statements inside the functions to speed up the import time of our modules.

> We control the entire installation environment via conda packaging

Also true! I often have to fix the environment manually especially during development (e.g., package incompatibilities arising from changes in an external package that we can't control), but I agree that this is not the main use case we want to support.

I'll be happy with any solution anyway. I just wanted to make sure we consider advantages and disadvantages before refactoring.

**Comment by jchodera** [comment]
> Completely agree, but that also applies to move the import statements inside the functions to speed up the import time of our modules.

Except that it's much easier to adopt the import encapsulation principle from the start and move imports to global space if they become a computational bottleneck than it is to go the other way and hunt down all the times imported packages and methods are used.

> I'll be happy with any solution anyway. I just wanted to make sure we consider advantages and disadvantages before refactoring.

+100

**Comment by mattwthompson** [comment]
See linked PR for a decent attempt at cutting down some of these imports (more can be done!) and a quick method for analyzing and visualizing import times.
