### ISSUE TITLE
"permissive" flag for reading cosmetic fields in OFFXML

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#160]
As an example, ForceBalance should use the toolkit to read/modify values in OFFXML files. However, ForceBalance also parses the XML file, and expects `parameterize` keywords listed in the XML for each parameter it should optimize. 

We can solve this by adding a `permissive` bool as an argument to the `ForceField` initializer. If `permissive` is true, the entire OFFXML will be read, and unrecognized attributes will be `setattr`'d on to their respective parameters (and therefore be available for modification and writing)

It may also be worth thinking about additional functionality that specifies whether to ignore unrecognized parameters vs. raise an error.

**Comment by jchodera** [comment]
We may also need a mode where we write a "clean" version where we simply remove all unrecognized accessory parameters, so that we can write out cleaned-up parameter files after FB or Bayesian optimization,

**Comment by leeping** [comment]
I agree with all of the above. :)

**Comment by j-wags** [comment]
The ability to read and write cosmetic attributes has been implemented. We don't have an example for it yet, but here are tests that cover their functionality.

https://github.com/openforcefield/openforcefield/blob/topology/openforcefield/tests/test_parameters.py#L325-L367

**Comment by davidlmobley** [comment]
Add an issue for "create example of use of cosmetic flags"?

**Comment by j-wags** [comment]
@davidlmobley added to #223
