### ISSUE TITLE
Split property-estimator branch into its own repo

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#162]
The `property-estimator` branch is largely its own toolkit. While it uses the openforcefield toolkit to perform system prep, it also has very different functionality and introduces dependencies that aren't used anywhere else (eg. dask).

Splitting `property-estimator` out into an independent repo would also let it start building compatibility with the openforcefield toolkit version 1.0.0 prototype. Until we split it out, getting each openforcefield toolkit update will require a manual merge from the `topology` branch. Once it's split, `property-estimator`'s will be able to pull dev versions of the openforcefield toolkit during Travis builds.

**Comment by jchodera** [comment]
Some name suggestions:
* `openproperties`
* `openproperty`
* `openobservables`
* `openestimator`
* `openmeasurement`

**Comment by j-wags** [comment]
This was resolved a few weeks ago. The new propertyestimator repo lives at https://github.com/openforcefield/propertyestimator/
