### ISSUE TITLE
Update Contributors List

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openforcefield#169]
This is somewhat random, but the Contributor section of the README is really outdated, as in there are a lot of people that should be there at this point that aren't. @j-wags maybe you can include an update to that section in the topology PR?

**Comment by davidlmobley** [comment]
Or update separately, either way.

**Comment by j-wags** [comment]
This sounds like a good idea. I'll update the README in a PR soon.

One note -- @SimonBoothroyd and I noticed that we do some unusual things in this codebase that don't seem to be super common. One of these is the author/contributor list in each file. While it's good to give credit, I think we should just keep a master contributor list in the README, and remove the individual ones in each file. Keeping these per-file lists around will create some burden of bookkeeping/evaluating amounts of contributions, with no clear benefit (changes are recorded in the Git commit history anyway). That said, I haven't added myself to any contributor lists yet, so I'd be interested to hear what the bigger contributors (@davidlmobley @bannanc and @jchodera) think

**Comment by jchodera** [comment]
+1 for a central contributor list!

**Comment by bannanc** [comment]
I also think a central contributor list is the easiest to maintain. I just happen to notice how short the main list was when I was looking for something else.

**Comment by davidlmobley** [comment]
I agree, yes. Per-file lists don't really make sense.

**Comment by j-wags** [comment]
This issue will be closed when 
* we have added all contributors to a central list (`README.md`?).
* we have removed all per-file lists

**Comment by jchodera** [comment]
Fixed in #246, where we now point to the GitHub contributors page.
