### ISSUE TITLE
ImproperHandler failing on triazole

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#172]
From Ian Craig:

[2019_01_25_triazole_improper_data.tar.gz](https://github.com/openforcefield/openforcefield/files/2796858/2019_01_25_triazole_improper_data.tar.gz)

> Hi. I'm running through the notebook provided during the hands-on session at the San Diego meeting earlier this month. I'm having problems parameterizing my own molecules though. In particular, the forcefield.create_openmm_system call complains that certain pairs of atoms aren't bonded according to the topology.
> I'll post the error below, but it seems that the PDB I'm providing isn't consistent with the SMILES somehow. Does the PDB have to be created in a particular way, or with a particular atom ordering, etc ..? The attached notebook and PDB should illustrate.

**Comment by j-wags** [comment]
Working on a fix in `j-wags-ff-update` branch.

**Comment by davidlmobley** [comment]
What's the problem, out of curiosity?

**Comment by j-wags** [comment]
The ImproperHandler wasn't complaining about the workshop molecules, so I hadn't polished it at all. One part was a pretty obvious atom indexing error. There seems to be another problem, which I'm still working on.

**Comment by j-wags** [comment]
I've gone ahead and tried this with the 0.2.1 version of the toolkit. Parameterization completes successfully, and the missing valence checks say it's OK. There are three trivalent planar atoms, and three improper torsions being applied, so I think it's being parameterized correctly. 

Closing this issue. 

<img width="740" alt="Screen Shot 2019-04-16 at 5 01 29 PM" src="https://user-images.githubusercontent.com/16329175/56251703-56774380-6069-11e9-887f-80f05f54cea3.png">

**Comment by davidlmobley** [comment]
@j-wags point this out to Ian on Slack wherever this issue came from?
