### ISSUE TITLE
Bring doctest online

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#181]
We have noticed that numerous examples are failing (per #178).

This issue is to bring online tests of the examples included in our documentation. A good choice for package to do this seems to be doctest, which is already in our ReadTheDocs configuration: https://github.com/openforcefield/openforcefield/blob/65f6b45954bde02c6cec1059661635c53a7f4e35/docs/conf.py#L41

**Comment by jchodera** [comment]
Do you mean the examples in the docstrings, or the examples in the `examples/` folder? Both are important, but `doctest` will only test the former.

**Comment by jchodera** [comment]
A decent number of the examples in `examples/` are Jupyter notebooks. Perhaps the [`nbval`](https://github.com/computationalmodelling/nbval) plugin for `pytest` would be of use here?

**Comment by jchodera** [comment]
@bannanc beat me to it with https://github.com/openforcefield/openforcefield/issues/178#issuecomment-463863571!

**Comment by j-wags** [comment]
Thanks for the input, @jchodera and @bannanc. I'll aim to put both online during the docs+examples update.

**Comment by jchodera** [comment]
I believe this is working now, since doctest failures necessitated #243.
