### ISSUE TITLE
Reactivate valence checks to raise exception when no SMARTS match is found

### ISSUE THREAD

**Issue by andrrizzi** [openforcefield/openforcefield#185]
See also [this comment](https://github.com/openforcefield/openforcefield/issues/75#issuecomment-465211049) in #75.

**Comment by andrrizzi** [comment]
Question: Do we want to raise an exception if `ForceField` has no parameters for some of the improper torsions?

**Comment by davidlmobley** [comment]
@andrrizzi :
> Question: Do we want to raise an exception if ForceField has no parameters for some of the improper torsions?

Are you asking whether we should raise an exception if an improper specified in the force field is missing some parameters? My answer to that is "yes". 

But you might be asking, "Do we want to ensure that all groups which COULD be assigned an improper torsion parameter do indeed have one assigned?" If the latter is what you're asking, the answer is NO. Impropers are an exception where they are not necessarily employed in the force field. Historically they have only seen occasional use/use for only certain chemistry. We will likely be broadening use of them, but it is still not the case that everything which COULD be assigned an improper SHOULD be assigned one. Effectively impropers are "optional".

**Comment by andrrizzi** [comment]
This was implemented in #217 .
