### ISSUE TITLE
Potentially unsafe use of `OEPerceiveChiral`

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#201]
Are you sure you want to be calling [`OEPerceiveChiral` here](https://github.com/openforcefield/openforcefield/blob/a8205cc1cb58fea3936cd1d808bc31f71033a662/openforcefield/utils/toolkits.py#L699)?

The [documentation](https://docs.eyesopen.com/toolkits/cpp/oechemtk/OEChemFunctions/OEPerceiveChiral.html) says:
>  as a side-effect, it also sets the ‘symmetry’ property of all the atoms the molecule to be their ‘explicit hydrogen suppressed’ symmetry class, by calling the OEChem TK function OEPerceiveSymmetry.

That sounds dangerous!

Don't you just want to query the stereochemistry of sites after constructing them from a SMILES? 

Instead of letting users operate the toolkit with the safeties off just to deal with amines, what about instead detecting if you have a tertiary amine if OEChem thinks stereochemistry is undefined, and allowing that to be OK if so?

_Originally posted by @jchodera in https://github.com/openforcefield/openforcefield/issues/182#issuecomment-465350377_

**Comment by j-wags** [comment]
I think this may not be used any more. Can we find this in the 0.2.0 toolkit?

**Comment by andrrizzi** [comment]
I've looked into this, and I think we're ok.

`OEPerceiveChiral` only sets the "symmetry" property of the atoms as a side effect, but it leaves hydrogens untouched (i.e. it doesn't suppress explicit hydrogens into implicit ones). Also, if I add `oechem.OESuppressHydrogens(oemol)` right after that line, a bunch of test cases (we have 371) for `from_openeye` a bunch of them start failing so I think we're covered.

I'm closing this now, but feel free to reopen if you think I've missed something.
