### ISSUE TITLE
Implement/test multi-conformer SDF reading through RDKit

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#202]
This dovetails with setting a partial charge spec for SDF. 

If SDF will become the bread-and-butter molecule format for OpenFF, this will be especially important.

**Comment by jchodera** [comment]
From what I understand, SDF does not support multiple conformers---it is a single-conformer format.

**Comment by j-wags** [comment]
Fantastic. I'll close this issue, and will hold off on making one for SDF partial charges until they're supported in RDKit/OE toolkit releases.
