### ISSUE TITLE
Automatically test the examples in the examples/ folder and in the main README.md file

### ISSUE THREAD

**Issue by andrrizzi** [openforcefield/openforcefield#211]
I'm going to try a simple hack using a `pytest` test that reads the `README.md` and either simply `eval()` the example or create a fake temporary Python module with the example, and then calls `doctest.testfile()`.

**Comment by andrrizzi** [comment]
We should also test in Travis the examples in the `examples/` folder. This should be relatively straightforward.

**Comment by andrrizzi** [comment]
I'm going to take a stab at this next so that we can ensure that all our examples work.

**Comment by jchodera** [comment]
Just as a reminder here: for the next release, it's most critical to have a few great working examples that show off the basic functionality than many examples that are not so great. We can delete examples that aren't ready yet and rescue them later when we are ready to add them back.

**Comment by andrrizzi** [comment]
I agree.
