### ISSUE TITLE
ForceField.create_openmm_system(topology) should read the box vectors from topology

### ISSUE THREAD

**Issue by andrrizzi** [openforcefield/openforcefield#222]
Currently, they are ignored so if `create_openmm_system(..., default_box_vectors=None)` the resulting `System` object will have arbitrary box vectors of 2nm per side.

Relatedly, now that the OFF `Topology` comes with box vectors, do we still want to keep the `default_box_vectors` argument to overwrite them? Or do we want the user to set `topology.box_vectors` before passing it to `create_openmm_system()`?

**Comment by j-wags** [comment]
Oh, totally my fault. I should have removed that. The user should now set `Topology.box_vectors` before system creation.

**Comment by j-wags** [comment]
Fixed in #225
