### ISSUE TITLE
Update travis build system to new MolSSI cookiecutter

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#237]
## ! All tests are now being run with RDKit !

We've added `rdkit` to the `meta.yaml`, which is currently being used during travis builds. Moving forward, the package will always have RDKit+Ambertools.

This means that we need to rethink our testing matrix, which currently tries to do builds with and without RDKit and OpenEye.

This could be a good opportunity to update the build system to the new cookiecutter format, which would let us use totally different `yaml`s for testing configurations.

**Comment by jchodera** [comment]
For now, a simple fix would just be to force uninstall of RDKit on test branches that shouldn't use it.

That is, change
```
  # Install RDKit
  - if [[ "$RDKIT" == true ]]; then conda install --yes -c rdkit rdkit; fi
  - if [[ "$RDKIT" == true ]]; then conda install --yes -c omnia ambertools; fi
```
to
```
  # Install RDKit
  - if [[ "$RDKIT" != true ]]; then conda remove --force --yes rdkit; fi
  - if [[ "$RDKIT" != true ]]; then conda remove --force --yes ambermini; fi
```

**Comment by j-wags** [comment]
We should also move `oe_license.txt.enc` out of the top-level directory of the repo. It's confusing GitHub's license analysis bot and screwing up our `LICENSE` badge
