### ISSUE TITLE
Implement Topology.to_openmm() 

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#240]
It would be useful to implement [`Topology.to_openmm()`](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/topology/topology.py#L1551-L1560) to reduce the amount of code needed to set up the protein-ligand system.

**Comment by j-wags** [comment]
Reopening this to keep track of thoughts on `create_parmed_structure`:

> John Chodera [10:43]
> I've quickly checked how the latest `parmed` release handles conversion from an OpenMM `System` to a `parmed.Structure` object and how the `+` operator works on `Structure` objects (which represent parameterized systems).
> 
> Here is the ParmEd code for how the `+` operator adds two `parmed.Structure` objects:
> https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L3354
> 
> For adding nonbonded forces, it looks like it just appends a list of `Atom` objects, which carry their partial charges and vdW parameters:
> https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L3374-L3377
> 
> Atom properties are here:
> https://github.com/ParmEd/ParmEd/blob/master/parmed/topologyobjects.py#L239-L427
> 
> This would indicate the `+` operator ignores anything to do with nonbonded treatment and simply pulls partial charges and LJ parameters from the atoms. That means it might also regenerate exceptions/exclusions when exporting. So we might lose a lot of information, like other scale factors applied to 12, 13, 14, 15 interactions
> 
> The method that converts from an OpenMM `System` object to a `Structure` is here:
> https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/topsystem.py#L30
> Processing of `NonbondedForce` is handled here:
> https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/topsystem.py#L375
> 
> Notably:
> * The `parmed.Structure` object is very AMBER-centric. If AMBER has a representation for this in a `prmtop` object, it's present, but if AMBER relegates this to an `mdin` input setting, it won't be there. Other codes have concepts that are also not well-handled by `Structure`.
> • Requires exceptions follow the normal AMBER pattern of `scale12 = scale13 = 0`, but will autodetect `scale14` as long as it is a constant applied everywhere.
> •  There cannot be any 1-5 exceptions at all. If they are detected, a warning will be thrown and they will silently be dropped. So we should raise an exception if we have `scale15 != 1`, and we should likely skip generation of 1-5 exceptions if `scale15 = 1`
> • The `NonbondedMethod` and all other parameters (PME tolerance, alpha, cutoff, etc.) are all ignored.

https://openforcefieldgroup.slack.com/archives/C8NE3J96U/p1553881413021900

**Comment by j-wags** [comment]
Concrete steps to closing this issue are:
* Agree on logic for carrying through selected settings from OpenMM systems to Parmed structures
* Identify which configurations can not be converted and when to throw exceptions
* Add a warning system explaining which information is always lost and whether it's expected to significantly change simulation results.

**Comment by j-wags** [comment]
Sorry for the spam -- I'm going to rename this Issue as "create_openMM_system" and #277 as "implement to_parmed_structure", to keep them separate
