### ISSUE TITLE
Add support for loading partial charges from SDF tags using new standard

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#250]
The OE and RDK maintainers have agreed on a spec for storing partial charges in SDF. We should implement support for I/O of this data.

**Comment by j-wags** [comment]
Test suggestions from John:

> (1) including a set of charged SDF files in our test dataset
> (2) ensuring openforcefield.topology.Molecule can write charged SDF files via either RDKit or OpenEye
> (3) adding tests of round-trips in all relevant directions between charged SDF files, OpenEye, RDKit, and Molecule?

I think this is exactly how we should go about this.

**Comment by j-wags** [comment]
Some notes as I move towards implementing this:

We will assume that partial charges should be written to a `>  <atom.dprop.PartialCharge>` block in SDF files. Units for these values are assumed to be `simtk.unit.elementary_charge` (I'll consider whether we should explicitly specify this in another SD field)

It will generally follow the spec laid out here: https://github.com/rdkit/rdkit/pull/2297

**Comment by j-wags** [comment]
Note: Keep a record of what we end up calling the partial charge field in the table in #135

**Comment by jchodera** [comment]
We should be sure to document (and version) the standard SDF tagging scheme for charges clearly in a readily accessible location so that it will be clear to other cheminformatics packages what the standard actually requires.
