### ISSUE TITLE
Update all examples to run using Binder

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#255]

**Comment by j-wags** [comment]
Also try adding NGLView to visualize output simulations

**Comment by mattwthompson** [comment]
I don't think this is worthwhile now, but at some point it may be useful to provide our own Docker images for examples and send them to mybinder, which would give us a some customization and a one stop shop for re-using examples outside of binder


https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html

**Comment by mattwthompson** [comment]
Some other good resources here for making them run quicker: https://discourse.jupyter.org/t/how-to-reduce-mybinder-org-repository-startup-time/4956/2
