### ISSUE TITLE
Allow easy swaps of parameter groups such as for water

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#26]
As noted in #24 , we want to begin using standard water models. Currently, there seem to be two ways of adding a water model (such as TIP3P) neither of which seems ideal:
a) Add the water model into an existing FFXML file, such as SMIRNOFF99Frosst. But, this would mean the water model is not easily replaceable by another 
b) Put the water into its own FFXML file. But since each FFXML file is applied independently to a system, it means it could only be applied to systems consisting only of water (which would then need to be re-combined with systems containing other molecules)

To some degree, this would be helped by adding support for including XML files within existing XML files, as requested in #19 . But, there may still be some complexities -- for example, we have to have a mechanism for ensuring the new content ends up in the right place in the hierarchical format.

@jchodera , insights? This also has some overlap with #25 since when we swap water models we also want to make sure the charges are going to come from the right place.

**Comment by andrrizzi** [comment]
I'm admittedly still unfamiliar with `ForceField` internals, but is there a fundamental reason as to why FFXML are applied to a system independently and not "merged" when the `ForceField` constructor is called?

**Comment by davidlmobley** [comment]
> I'm admittedly still unfamiliar with ForceField internals, but is there a fundamental reason as to why FFXML are applied to a system independently and not "merged" when the ForceField constructor is called?

So, I think there is a fundamental reason, yes. Specifically, it's a hierarchical format, where "last match wins". So, to merge them we would need some mechanism of specifying where in the format the new stuff goes (that is to say, which patterns it is going to override). 

To make this concrete for water: Currently, SMIRNOFF99Frosst definitely has parameters that match water. So if you were to blindly plunge ahead and enable a mechanism to include your water at the TOP of SMIRNOFF99Frosst (or apply it first) then it would get overridden by SMIRNOFF99Frosst, whereas if you included it at the bottom/applied it afterwards, it would override SMIRNOFF99Frosst. So in the one case you'd get TIP3P and in the other you wouldn't.

**Comment by jchodera** [comment]
For discussion of enabling how we can express TIP3P and friends in the SMIRNOFF XML format, be sure to see my comment here: https://github.com/open-forcefield-group/openforcefield/issues/24#issuecomment-298091518

The original `ForceField` class lets the user specify multiple XML files when initializing the forcefield object:
```python
forcefield = ForceField('file1.xml', 'file2.xml')
```
You can also use 
```python
forcefield = ForceField('file1.xml')
forcefield.loadFile('file2.xml')
```
Both of these schemes will cause *all* parameters from these files to be read in and stored. Because SMIRNOFF is a hierarchical forcefield, the second file puts the types at the end, and these types have priority in "winning" matches since typing uses last-match-wins.

That suggests it is very easy for us to test against existing water models this way:
* Either extend the SMIRNOFF format with the ability to override partial charges (most convenient) or always provide `OEMol` molecules with partial charges that match the water model of interest (less convenient)
* Make sure to encode the water model `ffxml` files to *only* match water
* Always specify the water model `ffxml` files last, such as
```python
forcefield = ForceField('SMIRNOFF99Frosst.xml', 'tip3p.xml')
```

**Comment by davidlmobley** [comment]
> That suggests it is very easy for us to test against existing water models this way:
>
> * Either extend the SMIRNOFF format with the ability to override partial charges (most convenient) or always provide OEMol molecules with partial charges that match the water model of interest (less convenient)
> * Make sure to encode the water model ffxml files to only match water
> * Always specify the water model ffxml files last, such as

**This sounds like a plan**. Under the first bullet, we can *now* use TIP3P by just pre-charging everything (so we don't have to extend the format to allow overrides yet if we are short on implementation time) but extending the format sounds like the right way to go long term.

**Comment by jchodera** [comment]
> This sounds like a plan. Under the first bullet, we can now use TIP3P by just pre-charging everything (so we don't have to extend the format to allow overrides yet if we are short on implementation time) but extending the format sounds like the right way to go long term.

It looks like the implementation and testing of the `charge` override would take approximately one hour, so we can do it now if we need to, but simply diving in with a pre-charged `OEMol` with hardcoded TIP3P charges will probably take just a couple of minutes, so maybe we can try that first.

**Comment by davidlmobley** [comment]
@andrrizzi - be sure to see this, as I think this has what you need. :)

**Comment by jchodera** [comment]
I believe we currently support reading multiple `.offxml` files, so this functionality has been implemented.

The `charge` functionality mentioned in #34 can be discussed there.
