### ISSUE TITLE
Update SMIRNOFF spec to include ToolkitAM1BCC

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#262]
Referencing https://github.com/openforcefield/openforcefield/issues/25#issuecomment-481476509
> I can't find mention of the ToolkitCharges. The ChargeIncrementModel was supposed to be our AM1-BCC, but we added the toolkit charge as a temporary workaround and may have neglected to add it to the spec. So yes, let's amend the spec in a bugfix release (spinning off a separate issue).

I forgot to add the `<ToolkitAM1BCC/>` tag to the SMIRNOFF spec

**Comment by jchodera** [comment]
Addressed by #267.
