### ISSUE TITLE
Build packaged version of toolkits with all dependencies included

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#263]
This will be important for our supporters who are not able to `conda install` from online sources, and is thus high-priority. 

Also summarize this process at https://github.com/choderalab/software-development

**Comment by j-wags** [comment]
So far, I'm seeing two ways to do this. 

1) [conda constructor](https://github.com/conda/constructor), which seems to do exactly what we want, but I'm a bit concerned by the lack of stars and the last commit being >1 month ago. 
2) Manually packaging all dependencies and running an offline conda install upon delivery, as described [here](https://stackoverflow.com/questions/51286388/creating-an-offline-package-folder-for-anaconda)

I'm leaning toward option 1, and I'll talk to MolSSI this afternoon about it and post notes here.

==========

We'll also need to figure out an infrastructure to perform/host these builds. 

It'll probably be something like
1) add "run `constructor`" to the deployment process checklist (Or could we bundle this with our eventual integration test framework? So travis would try to `conda install` the toolkit, run the tests, and then run constructor and push out the `constructor`ed packages)
2) add an openforcefield.org page pointing to a data store where the files are hosted

**Comment by j-wags** [comment]
### Notes from meeting with Psi4 devs 
(Thanks @loriab!)

Psi4 uses [`conda constructor`](https://github.com/conda/constructor)

Overall documentation for their release process is here: http://psicode.org/psi4manual/master/manage_release.html#build-psi4conda-set

* Build code lives here: https://github.com/psi4/psi4meta/tree/master/conda-recipes/constructor-cutter-unified
  * Platforms/pythons to build for are defined here: https://github.com/psi4/psi4meta/blob/master/conda-recipes/constructor-cutter-unified/cookiecutter/cookiecutter.json-v1.3 
  * There will be trouble with noarch dependencies (of which we have several), but they may be added manually, as shown at https://github.com/conda/constructor/issues/86#issuecomment-358895352 
  * You can set the resulting environment to have a specific channel priority (we’ll need to set `conda-forge` and maybe `omnia` over default if users might do subsequent installs)
  * If we wanted to also ship optional dependencies (that are available, but not installed by default) we could include packages in a “local/offline” channel. Users could later install optional dependencies from this local channel. (may be useful for supercomputer users, or if there’s a dependency clash)
  * We can decide whether to ship with raw package data, or just with the packages installed into the environment
* Build code runs: On a dedicated linux build machine at Georgia tech. 
  * I’m not sure if we want to do these using a physical machine, or delegate it to Travis.
  * Compatibility: Linux can build for mac and linux, but a windows machine would be required to build for windows
* The output of the constructor gets uploaded to a file server at Georgia tech
* The psi4 website then has a PR opened to point “latest” to a new version
  * Example update PR: https://github.com/psi4/psicode-hugo-website/pull/6
  * Resulting download page: https://admiring-tesla-08529a.netlify.com/installs/v13/

**Comment by jchodera** [comment]
It's possible we could use something like CircleCI that stores [build artifacts](https://circleci.com/docs/2.0/artifacts/) in a separate `openforcefield-constructor` repo that just builds and packages for releases.

**Comment by j-wags** [comment]
This is now complete -- The installer build system is at: https://github.com/openforcefield/toolkit-installer-constructor

Instructions have been tied into the Standard Release Process: https://github.com/openforcefield/openforcefield/issues/286

Installers of the most recent version have been quietly added to the assets list for the 0.4.1 release: https://github.com/openforcefield/openforcefield/releases/tag/0.4.1
