### ISSUE TITLE
Add classmethod to create ForceField from smirnoff data

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#265]
It would be helpful (and I think standard) to have a convenience `classmethod` to be able to create a `ForceField` object from a smirnoff data dict, i.e to be able to do
```
force_field = ForceField.from_smirnoff_data(data_dict)
```
instead of
```
force_field = ForceField()
force_field.load_smirnoff_data(data_dict)
```

**Comment by jchodera** [comment]
Why not just call this `from_dict()`?

**Comment by jchodera** [comment]
Also, can you elaborate on the use case here? I'm hoping we can get most users to use the object model to access parameters, rather than manipulating internal `dict` representations.

In fact, if we even make this part of the public API, we'd have to codify the dict structure and make sure it does not change. So I'd really prefer we _don't_ do make this public unless there is a compelling reason to do so where our object model will not be suitable.

**Comment by SimonBoothroyd** [comment]
> Why not just call this `.from_dict()`?

Mainly just to be consistent with the existing `load_smirnoff_data` and `to_smirnoff_data` methods - I think @j-wags has reasons for not going with `dict` / `to_dict` and `from_dict`? My personal preference would be `to_dict` and `from_dict` to be consistent with the `Serializable` class.

> Also, can you elaborate on the use case here? 

Purely for serialization - it enables me to easily incorporate this object into my data models (currently JSON, but also easily YAML and XML if I ever make a switch) without just turning the FF into an XML string and storing that in the outputted JSON.

> I'm hoping we can get most users to use the object model to access parameters, rather than manipulating internal dict representations.

100% agree we **do not** want people changing things by altering a `dict` using string literal accessors! Maybe this can be added as a note in the docstrings of these methods if we want to be a bit more explicit?

> In fact, if we even make this part of the public API, we'd have to codify the dict structure and make sure it does not change.

Currently this behaviour is already exposed as part of the public API through the `load_smirnoff_data` and `to_smirnoff_data` methods - the proposed change would be either in addition to (non-API breaking and my preference) or in place of (breaking) `load_smirnoff_data` to expose a slightly cleaner   (and I think in a way which is more consistent with [other APIs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)) way of calling `load_smirnoff_data` without explicitly creating a new FF object each time.

**Comment by jchodera** [comment]
Oh, dear. I think we might want to eliminate the public API for load_smirnoff_data we accidentally exposed in 0.2. We really don't want to have to support a public object API *and* and XML serialization spec *and* a dict based format for the same thing in perpetuity. I think we eventually just want to get down to the object model and either the dict or serialization, but not all three of these.

@j-wags: could we make the dict API private, or at least flag it with a warning that the dict structure is potentially subject to change? We can hash this out in a call next week.

**Comment by SimonBoothroyd** [comment]
Ah ok - I thought this was an intentional part of the API! If not supported then I agree the `*_smirnoff_data` methods should be made private. I'm happy for this issue to be closed if this is the case!

**Comment by j-wags** [comment]
> could we make the dict API private, or at least flag it with a warning that the dict structure is potentially subject to change?

Yes. That's a good idea. I'll open an issue to make it private.

Sorry for the confusion, @SimonBoothroyd, that's totally my mistake. I agree that, especially while we don't know what the final form of this intermediate dict representation will be, we shouldn't expose it.
