### ISSUE TITLE
Set up pull request template

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#270]
It would be useful to set up a [pull request template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) that helps remind absent-minded developers like myself to update the changelog for their PRs when they open them!

**Comment by andrrizzi** [comment]
+1!

**Comment by jchodera** [comment]
Do you have a format you like @andrrizzi ?

**Comment by andrrizzi** [comment]
Something like this maybe? But I've no strong opinion about it
```
- [ ] Add (tests)[https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests].
 - [ ] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs).
 - [ ] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)
```

**Comment by jchodera** [comment]
Let's get this implemented ASAP, since it looks like PRs are neglecting to update their changelogs!
