### ISSUE TITLE
Remove {load,to}_smirnoff_dict from public ForceField API

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#278]
Per the discussion in #265, we should remove `load_smirnoff_data` and `to_smirnoff_data` from the public API.

> Oh, dear. I think we might want to eliminate the public API for load_smirnoff_data we accidentally exposed in 0.2. We really don't want to have to support a public object API and and XML serialization spec and a dict based format for the same thing in perpetuity. I think we eventually just want to get down to the object model and either the dict or serialization, but not all three of these.
> 
> @j-wags: could we make the dict API private, or at least flag it with a warning that the dict structure is potentially subject to change? We can hash this out in a call next week.

**Comment by j-wags** [comment]
ALSO -- and big API oversight here -- add 
`ForceField.to_file(filename, format, return_cosmetic_attributes=False)`
and
`ForceField.to_string(format, return_cosmetic_attributes=False)`

**Comment by jchodera** [comment]
We should definitely add this, but we should discuss this in a separate issue.

Also, do you mean `retain_cosmetic_attributes` instead of `return_cosmetic_attributes`? 
And perhaps we would want to retain these by default unless instructed to strip them out?

**Comment by j-wags** [comment]
Closed by #291
