### ISSUE TITLE
Update __init__ file to not raise exception

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openforcefield#279]
I apologize if this is a duplicate of something you already have documented @j-wags. The main [`__init__`](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/__init__.py) file in openforcefield looks like it still raises an exception if OpenEye toolkits aren't installed. It also has a few commented out lines at the bottom that seem like they should be uncommented or removed.

**Comment by andrrizzi** [comment]
Thanks for catching this! It's weird that our tests don't catch this. I'll take a look at this today, and schedule it for the upcoming milestone as I think this is critical.

**Comment by j-wags** [comment]
Sorry to be late to this party. I just checked out @andrrizzi's PR #280 . I agree with him that this exception was getting caught by `try/except` logic before, but it did result in us double printing the "you didn't install the OpenEye Toolkit" message. 

Looking into this also revealed a potential error with our build system (which is I think what @bannanc wanted to chat about tomorrow in Irvine). 

Thanks for posting this issue. I didn't even realize that the top-level __init__ had any logic in it before.

Agree that merging #280 should close this.
