### ISSUE TITLE
Add tests for jupyter notebooks

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#29]
It looks like it's fairly straightforward to [programmatically execute jupyter notebooks](http://blog.thedataincubator.com/2016/06/testing-jupyter-notebooks/) to make sure they haven't gone stale. Maybe we can add this to our travis tests?

**Comment by jchodera** [comment]
cc: #8

**Comment by davidlmobley** [comment]
Ha, cool. This is excellent!

**Comment by bannanc** [comment]
Good to know!
Should we run all of them? Some are really slow. The one used for filtering DrugBank or checking parameters in smirnoff take ~20 minutes to run all the way through.

**Comment by davidlmobley** [comment]
That won't be practical for Travis-CI if it's slow. However, there is a way to flag some tests as "slow" and have Travis skip slow tests. I think this is done for some tests in `openmoltools` so this would be a good way to deal with this issue.

**Comment by jchodera** [comment]
That scheme uses a decorator to flag tests with attributes that nose can use to skip some tests, but I'm not sure it would work for notebooks (depending on how you autodiscover and run notebooks).

Do you want to bail partway through those expensive notebooks, or just not run them at all? If partial testing is better than no testing, we could add a convenience routine that checks if a Travis environment variable is set and exits if so, and you can add that to expensive notebooks at the point where you want them to stop.

I love notebooks, but the difficulty of testing them really means we should put any nontrivial code not associated with plotting or simple examples into library modules, at least whenever possible.

**Comment by jchodera** [comment]
We can use [this plugin](https://github.com/computationalmodelling/nbval) after we migrate to `py.test`.

**Comment by jchodera** [comment]
This was added by @andrrizzi
