### ISSUE TITLE
Implement GBSAParameterHandler

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#290]
Our [GBSA implementation](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/typing/engines/smirnoff/parameters.py#L2306) is close to functional. If we're happy with the [spec section](https://open-forcefield-toolkit.readthedocs.io/en/latest/smirnoff.html#gbsa), we can go ahead and finish implementing this in a near-term feature release milestone.

**Comment by proteneer** [comment]
What's missing in terms of implementation?

**Comment by proteneer** [comment]
On the spec side of things, is it intended that GBSA charges will be inherited from the nonbonded charges? AFAIK OpenMM's system class doesn't actually require NonbondedForce charges to be the same as that of GBSA charges.

**Comment by j-wags** [comment]
> What's missing in terms of implementation?

* Refactoring `GBSAHandler` and `GBSAType` to inherit the `ParameterHandler` base class 
* Implementing checks to ensure valid combinations of parameters are used to initialize `GBSAHandler` and `GBSAType`
* Finding a better long-term solution for assigning/passing charges between different `ParameterHandler`s
* Tests and examples

> On the spec side of things, is it intended that GBSA charges will be inherited from the nonbonded charges? AFAIK OpenMM's system class doesn't actually require NonbondedForce charges to be the same as that of GBSA charges

Good question. My own thought is that the charges should be inherited, but I'll tag @jchodera and @davidlmobley to see if that's how they see it, too.

**Comment by davidlmobley** [comment]
The thought is that they would inherit the nonbonded charges AFAIK. 

Is there a use case for GBSA charges to be separate? Or something having them separate would enable that can't be accomplished by having them inherit?

I suppose I can see someone wanting to fit GBSA-specific charges, but... presumably if they were doing that they're basically buidling a GBSA-specific force field and I don't necessarily see that we need to allow them to retain their original force field in the same file. So inheritance seems good to me.

**Comment by proteneer** [comment]
I'm also +1 on inheriting them. Though one corner case might be where you intentionally turn off GBSA for certain parts of the system and use vanilla electrostatics. But even then you probably want to use the same charges.

**Comment by j-wags** [comment]
Whoops, this should have been closed with PR #363
