### ISSUE TITLE
Refactor SMIRNOFF spec to better encapsulate data

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#297]
@jchodera asked several questions of the form "why is there a `to_X` function and not a `from_X` function?"

This was a really interesting question to think about. What it comes down to is that the SMIRNOFF data model makes serialization and deserialization asymmetric. That is, it would be satisfying to be able to take a SMIRNOFF dict (hierarchical dict representation of an OFFXML), and pass it to the `ForceField` initializer, and have that pass each parameter section into the appropriate `ParameterHandler` initializer, and have that pass the parameter list into the `ParameterList` initializer, and have that pass each individual parameter into the appropriate `ParameterType` initializer. But we can't.

This is because there are at least two cases where information that is scientifically important to the `ParameterType` is actually stored in the section header (and therefore becomes an attribute of the `ParameterHandler`). These are:

* units
* `Torsions`'s `default_idivf`

So, what really happens is:
* the `ParameterHandler` is initialized using the section dict as kwargs for its initializer
* the `ParameterHandler` initializes a `ParameterList` for itself (no kwargs)
* the `ParameterHandler` modifies each parameter (which is still a dict) by attaching units, 
* the `ParameterHandler` uses the unit-attached dict as kwargs to the `ParameterType` initializer, 
* the `ParameterHandler` finally appends the initialized `ParameterType` to its `ParameterList`.

Because of this, we can't directly serialize a ParameterType to a line in an OFFXML file. At a minimum, the owning `ParameterHandler` must decide which units all of its `ParameterTypes` will use, and then convert all of the serialized `ParameterType`s it owns to use those values.

I think that modifying the SMIRNOFF spec to achieve this symmetry would be more than just satisfying -- It would probably head off several errors and simplify development in the future. What do you think, @jchodera @SimonBoothroyd @andrrizzi @davidlmobley ?

_Originally posted by @j-wags in https://github.com/openforcefield/openforcefield/pull/291#issuecomment-489141867_

**Comment by davidlmobley** [comment]
Yes, agreed, as I think I said in the other thread.
