### ISSUE TITLE
Documentation formatting cleanup

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#307]
@SimonBoothroyd pointed out something that's been bothering me for a while, which is that our documentation is formatting in an unreadable way for long paths. We should look into a better way to present this.

> Simon Boothroyd [05:55]
> Is there perhaps different settings we could use for the side navigation pane on the docs pages? At the moment I'm finding the docs a bit difficult to traverse, as most of the navigation text is getting truncated:
> <img width="597" alt="Screen Shot 2019-05-08 at 8 50 59 AM" src="https://user-images.githubusercontent.com/16329175/57391087-97e3a600-7172-11e9-8980-916ab930c42f.png">
>

**Comment by j-wags** [comment]
linking #397, since that's also a `good first issue` related to documentation.

**Comment by jchodera** [comment]
What if we ditch the side navbar for API docs? That would both make the width available for the API docs to be wider and get rid of the running-out-of-the-navbar text issue.

We may still need to find a way to reduce font sizes for the long module paths, though.

**Comment by jchodera** [comment]
Hm, this might be more tricky. There's no way to hide the navbar in just the API docs using the [standard theme configuration options](https://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html#customization). There's also no easy way to change the font sizes.

This may require more complex customization or, perhaps easier, switching to a different theme.
