### ISSUE TITLE
Allow configure VdW switching in ForceField

### ISSUE THREAD

**Issue by andrrizzi** [openforcefield/openforcefield#31]
I couldn't find a way to `setUseSwitchingFunction` and `setSwitchingDistance` through `ForceField.createSystem`. We can still work around it by just configuring manually the force after the system has been created, but it would be nice to support it in `NonbondedGenerator.createForce`.

**Comment by davidlmobley** [comment]
This sounds interesting, but how would you think to bring it in? Via arguments to `createSystem`?

**Comment by andrrizzi** [comment]
I didn't go to deeply in checking its feasibility, but `ForceField.createSystem` currently takes `kwargs` that gets feed to `force.createForce(..., **kwargs)`. Similarly to `openmm.AmberPrmtopFile.createSystem(..., switchDistance=Quantity(value=0.0, unit=nanometer))`, we could have one of those kwarsg be a `switchDistance` parameter that will be taken by `NonbondedGenerator.createForce()` to set the switching accordingly.

**Comment by davidlmobley** [comment]
Sounds good to me.

**Comment by jchodera** [comment]
Should the switching function be an intrinsic property of the forcefield (and described in the XML) or should it be something that we leave to the user to decide every time they create a System object?

In inclined to say that anything that affects the potential should probably be encoded in the XML file. Once we have the ability to parameterize forcefield a using consistent data, we would presumably want to derive parameters specific to particular nonbonded treatments or constraints.

**Comment by davidlmobley** [comment]
I'm thinking that for SMIRNOFF force fields we derive by fitting to data, it should be encoded by the force field. 

BUT, this will not be all force fields -- for example SMIRNOFF99Frosst was developed without a specific switching function in mind. Also, we're hoping to get others to put their force fields into this format, and those, likewise, will come in without having been necessarily designed for a specific switching function (or at least, whether they were or not is a matter of debate). So, people using these types of "historical" or at least "not fitted with a specific switching function" force fields will want/need the ability to pick.

**Comment by jchodera** [comment]
What if we allow these things to be encoded by the XML but provide optional arguments to ForceField to override or specify these?

The question then is whether there should be defaults, or if we should require either the XML specify things or the user provide an optional argument to ForceField?

**Comment by davidlmobley** [comment]
> What if we allow these things to be encoded by the XML but provide optional arguments to ForceField to override or specify these?

Yes, that's my preference.

> The question then is whether there should be defaults, or if we should require either the XML specify things or the user provide an optional argument to ForceField?

I think defaults makes sense to me, though I don't have strong opinions on what the defaults should be.

**Comment by jchodera** [comment]
Are you sure? That means there are THREE places that the settings you are using in your simulation could come from, rather than two.

I would much rather be more strict, and require these things to be specified by the optional arguments if they are not in the XML files.

**Comment by davidlmobley** [comment]
> I would much rather be more strict, and require these things to be specified by the optional arguments if they are not in the XML files.

I'm fine with this; that's why I phrased it tentatively. It sounds like you have a strong opinion on it and I'm OK with that approach.

**Comment by jchodera** [comment]
These settings are now controlled by the `vdW` section of the SMIRNOFF spec:
https://open-forcefield-toolkit.readthedocs.io/en/latest/smirnoff.html#vdw
