### ISSUE TITLE
Support constraints argument in ForceField.createSystem

### ISSUE THREAD

**Issue by andrrizzi** [openforcefield/openforcefield#32]
Currently, calling `createSystem` with `constraints` different than `None` raises an exception. Since the constraints have been implement, we could now in principle support standard OpenMM constraints specification (e.g. `HBonds`, `HAngles`) by "appending" the SMIRNOFF definition of constraint to the stored force field specification.

**Comment by davidlmobley** [comment]
Yes, that would be great. No one has done anything with them yet since John implemented them, so you're paving the way here. THanks for working on it.

**Comment by andrrizzi** [comment]
I believe the consensus here, for now, was to add constraints specification exclusively through the `offxml` files and the `<Constraints>` tag. For some applications such as relative free energy calculations, selected constraints that are hardcoded in the force field can still be removed with `openmm.System.removeConstraint(constraint_idx)`.

I'm going to close this issue to keep the tracker clean, but feel free to reopen if I misunderstood something.
