### ISSUE TITLE
Undefined stereochemistry error on molecule creation should be only a warning if undefined stereochemistry is allowed

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#323]
Currently, the `Molecule.from_openeye` code prints an error message about undefined stereochemistry even if `allow_undefined_stereo=True`; however, it only raises an Exception if it is set to False (default).

The error message printed should presumably be changed to a warning if `allow_undefined_stereo` is set to `True` otherwise it is confusing, e.g. I end up with a big set of printouts saying things like:

```
Unable to make OFFMol from OEMol: OEMol has unspecified stereochemistry. oemol.GetTitle(): 
Problematic atoms are:
Atom atomic num: 6, name: , idx: 11, aromatic: False, chiral: True with bonds:
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 10, aromatic: True, chiral: False
bond order: 1, chiral: False to atom atomic num: 6, name: , idx: 12, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 1, name: , idx: 16, aromatic: False, chiral: False
bond order: 1, chiral: False to atom atomic num: 7, name: , idx: 26, aromatic: False, chiral: False
```

but the code runs. 

The problem seems to be right here: https://github.com/openforcefield/openforcefield/blob/b860311b3e02c198cf16c579468e270b7b759854/openforcefield/utils/toolkits.py#L736-L743 where `msg` gets printed (and denotes "Unable to make..." ) even if no Exception is raised and a molecule is made.

(I ran into this because I was trying to test parameter usage on the Roche set; I don't actually care about whether the molecules have 3D geometries, I just want to test what parameters would be used.)

**Comment by j-wags** [comment]
Good catch, @davidlmobley. Should be an easy fix. I've assigned this to the 0.3.1 milestone, if we don't get to it sooner.

**Comment by ChayaSt** [comment]
@j-wags, I found when I added [these lines](https://github.com/openforcefield/cmiles/blob/stereo-fix/cmiles/_cmiles_oe.py#L360-L363), the spurious warnings stop. `oechem.OEPerceiveChiral(molecule)` is not enough in some cases.
