### ISSUE TITLE
cyclohexane_water packmol box leads to unstable simulation

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#324]
## Expected Behavior
Parameterizing `systems/packmol_boxes/cyclohexane_water.pdb` (a box with one cyclohexane and a few hundred waters) should lead to a straightforward simulation.

## Actual Behavior

Taking steps of 1 or 2 femtoseconds, hydrogens on the cyclohexane molecule move rapidly and, after <10 steps, cause the simulation to crash. Investigating the parameters by eye shows the correct bond connectivity, with reasonable `k` and `d` values, and a quick look at angles and torsions doesn't show anything out of place either. The starting geometry of the cyclohexane looks reasonable, and measuring the bonds and angles numerically shows values close to equilibrium.

Taking steps of 0.1 femtoseconds, the simulation completes, but the cyclohexane has far more kinetic energy than other molecules in the system. Video below:

![cyclohexane_water_0p1fs](https://user-images.githubusercontent.com/16329175/57899927-c10bd280-7813-11e9-9f95-dd85d594a545.gif)

Removing all molecules except the cyclohexane from the starting PDB leads to an unremarkable simulation that is stable with steps of 2 fs.

Removing all molecules except the cyclohexane and one water from the starting PDB leads to an unremarkable simulation that is stable with steps of 2 fs.

## Ideas

Given that the simulation is totally stable when less particles are present, this may be a heating/thermostat issue. One thought is that the only `PeriodicTorsion`s in the system are in the cyclohexane, and maybe that's leading to an unequal distribution of energy.

## Minimal Reproducible Example
```
from simtk.openmm.app import PDBFile
from openforcefield.utils import get_data_file_path
pdb_file_path = get_data_file_path('systems/packmol_boxes/cyclohexane_water.pdb')
pdbfile = PDBFile(pdb_file_path)
from openforcefield.topology import Molecule
cyclohexane = Molecule.from_smiles('C1CCCCC1')
water = Molecule.from_smiles('O')
from openforcefield.topology import Topology
from openforcefield.typing.engines.smirnoff import ForceField

# Create the Open Force Field Topology from an OpenMM Topology object.
omm_topology = pdbfile.topology
off_topology = Topology.from_openmm(omm_topology, unique_molecules=[cyclohexane, water])

# Load the smirnof99Frosst force field.
forcefield = ForceField('smirnoff99Frosst.offxml')

# Parametrize the topology and create an OpenMM System.
system = forcefield.create_openmm_system(off_topology)
from simtk import openmm, unit

# Propagate the System with Langevin dynamics.
time_step = 1*unit.femtoseconds  # simulation timestep
temperature = 300*unit.kelvin  # simulation temperature
friction = 1/unit.picosecond  # collision rate
integrator = openmm.LangevinIntegrator(temperature, friction, time_step)

# Length of the simulation.
num_steps = 1000  # number of integration steps to run

# Logging options.
trj_freq = 1  # number of steps per written trajectory frame
data_freq = 1  # number of steps per written simulation statistics

# Set up an OpenMM simulation.
simulation = openmm.app.Simulation(omm_topology, system, integrator)

# Set the initial positions.
positions = pdbfile.getPositions() 
simulation.context.setPositions(positions)

# Randomize the velocities from a Boltzmann distribution at a given temperature.
simulation.context.setVelocitiesToTemperature(temperature)

# Configure the information in the output files.
pdb_reporter = openmm.app.PDBReporter('trajectory.pdb', trj_freq)
state_data_reporter = openmm.app.StateDataReporter('data.csv', data_freq, step=True,
                                                   potentialEnergy=True, temperature=True,
                                                   density=True)
simulation.reporters.append(pdb_reporter)
simulation.reporters.append(state_data_reporter)


simulation.step(num_steps)

```

Optionally: 
```
from simtk.openmm import XmlSerializer
from pprint import pprint
pprint(XmlSerializer.serialize(system))
```

## Specifications

  - Version: current master

**Comment by j-wags** [comment]
@SimonBoothroyd points out that, if we minimize the system beforehand, using `simulation.minimizeEnergy()`, the simulation can be run at a 2 fs timestep with no problems. I am able to reproduce this, but I see that the cyclohexane coordinates after minimization are quite different than before. This is confusing, as I inspected the geometry by eye and did several measurements of bond lengths and angles and didn't find anything severely out of place.

**Comment by j-wags** [comment]
A useful step forward would be to investigate the energy by component, to help narrow down what to check by eye.

**Comment by jchodera** [comment]
You should always minimize the energy prior to simulation to ensure stable simulations. It's likely that the packmol-generated boxes have atom-atom contacts much tighter than equilibrium simulations, so simulating directly from these will dump a huge amount of energy into the system that the Langevin thermostat isn't able to remove quickly enough.

If you're using constraints, the bonds to hydrogen are being reset to their constrained bond lengths in the first step, likely leading to further injection of energy into the system.

If we want users to be able to simulate from our initial structures right away, we will need to pre-minimize them in smirnoff99Frosst and write out those files for use.

**Comment by davidlmobley** [comment]
This... explains why I've never had problems iwth that box, since I always minimize first. We COULD deposit a minimized box for starting these I suppose.

I'd change the title to something about "test boxes could be minimized before deposition" and mark it as a low priority fix.

**Comment by mattwthompson** [comment]
I can reproduce the above (crashes w/o minimization, starts well enough w/). I agree saving energy minimized structures (with smirnoff99Frosst, parsely, whatever) would be worthwhile.

**Comment by j-wags** [comment]
Sounds good. Glad to hear it wasn't a technical issue. Let's save minimized
structures with Parsley (openff-1.1.0).
