### ISSUE TITLE
Deprecate or decide to keep functionality in utils/structure.py 

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#333]
We have several utility functions here, some of which we fixed in the 0.2.0 release, but many of which have lapsed. 

Functions to decide on are:
* `generateSMIRNOFFStructure(oemol)`
* `generateProteinStructure(proteinpdb, protein_forcefield='amber99sbildn.xml', solvent_forcefield='tip3p.xml')`
* `combinePositions(proteinPositions, molPositions)`
* `mergeStructure(proteinStructure, molStructure)`  
* `generateTopologyFromOEMol(molecule)`  <-- probably delete, we shouldn't need to handle OEMols specially any more
* `normalize_molecules(molecules)` <-- probably delete, we already perform molecule sanitization elsewhere
* `read_molecules(file_path, verbose=True)` <-- probably delete, redundant with Molecule.from_file
* `setPositionsInOEMol(oemol, positions)` <-- probably delete
* `extractPositionsFromOEMol(oemol)` <-- probably delete
* `read_typelist(file_path)` <-- probably delete
* `positions_from_oemol(mol)` <-- probably delete
* `check_energy_is_finite(system, positions)`
* `get_energy(system, positions)`
* `get_molecule_parameterIDs(molecules, forcefield)`
* `getMolParamIDToAtomIndex(molecule, forcefield)`
* `merge_system(topology0, topology1, system0, system1, positions0, positions1, label0="AMBER system", label1="SMIRNOFF system", verbose=True)`
* `save_system_to_amber(openmm_topology, system, positions, prmtop, inpcrd)`
* `save_system_to_gromacs(openmm_topology, system, positions, top, gro)`

**Comment by davidlmobley** [comment]
I agree with all of the ones that you proposed deleting, and actually I think ALL of them can be deleted (unless used in tests!)except maybe I could still see wanting to use

`get_molecule_parameterIDs(molecules, forcefield)`
`getMolParamIDToAtomIndex(molecule, forcefield)`

I don't see any need for most of these and in fact we had already agreed we wanted to remove most of the functionality in `utils` and focus on exposing the API/getting people to use the API ratehr than wrapper functions provided here.

**Comment by j-wags** [comment]
In #425 I'm going to add deprecation warnings to all of these functions, with instructions to come back to this issue and let me know if folks want us to continue supporting specific functionality.

**Comment by mattwthompson** [comment]
Haven't seen any complaints (at least publicly, feel free to reach out elsewhere if there are other concerns)

Should we target removal in 0.8.0?

**Comment by jchodera** [comment]
I think all of these methods are now covered by actual designed API methods, so it would be great to ditch them and see if anyone complains!

**Comment by mattwthompson** [comment]
With the exception of one function that was still used in an example, the module has been removed and will be unavailable in 0.8.0.

**Comment by j-wags** [comment]
Thanks, Matt. This can now be closed!
