### ISSUE TITLE
Missing Torsion Parameter For >C-N-N=N- 

### ISSUE THREAD

**Issue by yudongqiu** [openforcefield/openforcefield#336]
### Description
The torsion parameter for the torsion angle of pattern >C-N-N=N- is missing.

### Output
The files are provided in the attachments below.
```
$python debug.py
Traceback (most recent call last):
  File "debug.py", line 7, in <module>
    forcefield.create_openmm_system(topology)
  File "/home/qyd/codes/anaconda3/envs/openff/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py", line 997, in create_openmm_system
    parameter_handler.create_force(system, topology, **kwargs)
  File "/home/qyd/codes/anaconda3/envs/openff/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py", line 1412, in create_force
    exception_cls=UnassignedProperTorsionParameterException)
  File "/home/qyd/codes/anaconda3/envs/openff/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py", line 1004, in _check_all_valence_terms_assigned
    raise exception_cls(err_msg)
openforcefield.typing.engines.smirnoff.parameters.UnassignedProperTorsionParameterException: ProperTorsionHandler was not able to find parameters for the following valence terms:
- (6, 8, 10, 11)


```

### Screenshot

![image](https://user-images.githubusercontent.com/6952367/58515298-428b2b00-8159-11e9-89aa-acf4675ecfc6.png)

### Attachments
[report_missing_smirks.tar.gz](https://github.com/openforcefield/openforcefield/files/3229865/report_missing_smirks.tar.gz)

**Comment by j-wags** [comment]
Thanks for the thorough report, @yudongqiu! 

I'm not seeing any obvious reason that this would be intentional in our forcefields. I wonder if @bannanc, @jchodera, or @davidlmobley can offer any insight on this.

**Comment by davidlmobley** [comment]
@yudongqiu do you have an example molecule? Your depiction is missing bond orders so I can't quite tell what this is. :) 

Probably we can fix this by adjusting one of the generics or adding a specialized parameter. This is something we should cover, I think, though it's unclear how WELL we should cover it.

@bannanc thoughts? (She may be a bit slow to respond as her defense is next week.)

**Comment by davidlmobley** [comment]
(We should also open an issue on the smirnoff99frosst repo since that's the place for FF issues.)

**Comment by yudongqiu** [comment]
@davidlmobley Yes the example molecule files and script I wrote are all in the attachment below the picture.

**Comment by davidlmobley** [comment]
@yudongqiu do we have coverage of this chemistry in the Roche set/torsion scans we've done so far? If so I would advocate for just adding a torsional parameter to cover this chemistry (I can come up with a SMIRKS pattern probably) and we can fit it.

**Comment by yudongqiu** [comment]
Yes I found it missing because three molecules in the Roche set have this torsion. However the current group 1 torsion scans does not cover torsions that are in a ring, so this torsion is not scanned yet. We have plans to add next group of scans to cover the limited torsion inside rings, and at that time we can fit the newly added SMIRKS.

**Comment by davidlmobley** [comment]
I actually realized that right after I asked -- since it's a ring of course it wouldn't be scanned. 

I'll work on coming up with a SMIRKS.

**Comment by davidlmobley** [comment]
CC @bannanc

**Comment by davidlmobley** [comment]
For the record, because I somewhat prefer to work with SMILES, the isomeric SMILES for this is `Cc1ccccc1c2[n-]nnn2`. Very related compounds come up in ZINC (2786193, 12360034, 13556282) and eMolecules (there's quite a lot, but see for example CAS# 51449-86-6)

Looking at the smirnoff99Frosst v1.0.8 offxml, these would be in the torsions section; we're looking for torsions where nitrogens are the central atoms and we have terminal carbon and nitrogen. 

One might expect the generics below to catch this (https://github.com/openforcefield/smirnoff99Frosst/blob/master/smirnoff99frosst/offxml/smirnoff99Frosst-1.0.8.offxml#L270-L271):
```
 <Proper smirks="[*:1]~[#7X2:2]-[#7X3:3]~[*:4]" id="t128" idivf1="1" k1="0.625" periodicity1="1" phase1="180.0"/>
    <Proper smirks="[*:1]=[#7X2:2]-[#7X2:3]=[*:4]" id="t129" idivf1="1" k1="1.4" periodicity1="1" phase1="180.0"/>
    <Proper smirks="[*:1]~[#7X2:2]=,:[#7X2:3]~[*:4]" id="t130" idivf1="1" k1="6.000" periodicity1="1" phase1="180.0"/>
    <Proper smirks="[*:1]~[#7X3+1:2]=,:[#7X2:3]~[*:4]" id="t131" idivf1="1" k1="3.000" periodicity1="1" phase1="180.0"/>
```

But they are not generic enough, it appears. Specifically, t128 fails to match because none of the nitrogens have three connections; t129 fails to match because the 1 and/or 4 positions don't involve double bonds, t130 fails to match because the central bond is single, and t131 fails to match for the same reason.

We could address this by introducing a generic nitrogen-nitrogen single bond parameter, `[*:1]~[#7:2]-[#7:3]~[*:4]`, but that may be too broad. I have some preference for actually introducing a specific ring bond parameter, `[*:1]~[#7:2]@[#7:3]~[*:4]`.

Thoughts @yudongqiu and @cbayly13 ?

**Comment by yudongqiu** [comment]
I agree that a specific ring bond parameter is better than the generic one. I wouldn't argue even it's more specific. (like `[#6:1]~[#7:2]@[#7:3]=[#7:4]`?) Because the `>C-N-N=N` that appears in the CN4 ring is the only case I see this pattern in the Roche set.

**Comment by davidlmobley** [comment]
@yudongqiu we COULD do that, but it might pay to have a generic ring bond torsion just in case a related but different case comes up somewhere else. 

I'm checking with Chris too; we should be able to get this fixed at the same time as the other issues we're discussing on Slack.

**Comment by cbayly13** [comment]
parm@Frosst did treat tetrazoles but I think I did not translate the parameter into the best smarts string. I had just zeroed out the parameter anyway. We need a parameter that can handle both the ionized and protonated form, and which can account for the resonance forms which allow the negative charge to go on any of the nitrogens. So for the smarts string I propose:
`[*:1]@[#7X2:2]@[#7X2:3]@[#7X2,#6X3:4]` for the anion
`[*:1]-[#7X3:2]-@[#7X2:3]=@[#7X2:4]` for the neutral (wherein the first atom could be exocyclic)
From parm@Frosst I would just zero out the parameter for now.

**Comment by davidlmobley** [comment]
@cbayly13 the pattern `[*:1]-[#7X3:2]-@[#7X2:3]=@[#7X2:4]` is not matching anything for me; I've also tried the neutral form of the tetrazole in question -- Cc1ccccc1c2[nH]nnn2 -- and am not getting any matches with this pattern, using the toolkit or in picto.  Picto tells me that `[*:1]@[#7X3:2]@[#7X2:3]@[#7X2:4]` -- which I think is close to what you are after though not as general -- would work, but this is not matching in the toolkit (perhaps an aromaticity model issue). I'm not quite clear what to do with this one.

If you think this particular parameter was inserted to avoid "no parameter for this molecule" type errors, I suggest removing it (and keeping only the one we need) until we encounter a specific molecule where it is relevant.

**Comment by cbayly13** [comment]
I think it is an aromaticity issue: `[*:1]-[#7X3:2]-@[#7X2:3]=@[#7X2:4]` is for a non-aromatic tetrazole, and I am pretty sure any 5-membered heteroaromatic including tetrazole is non-aromatic with the MDL aromaticity model (and aromatic with most others). Lowercase characters in your smiles string  Cc1ccccc1c2[nH]nnn2 defines an aromatic tetrazole so my smarts string would not match. So I am puzzled... does C1-N-N=N-N=1 become aromatic with MDL aromaticity? 
Anyway, we could use your pattern `[*:1]@[#7X3:2]@[#7X2:3]@[#7X2:4]`and we would just lose bond order information; I would prefer to have bond orders but we need to move forward.

**Comment by davidlmobley** [comment]
@cbayly13 - right now there’s still an issue with the tetrazole torsions; the new SMIRKS we have for the ring in question is getting overridden by a later more generic parameter:

        ```<Proper smirks="[*:1]@[#7X3:2]@[#7X2:3]@[#7X2:4]" periodicity1="1" phase1="180.0 * degree" k1="0.000 * mole**-1 * kilocalorie" id="t128b" idivf1="1.0"></Proper>
        <Proper smirks="[*:1]~[#7X2:2]-[#7X3:3]~[*:4]" periodicity1="1" phase1="180.0 * degree" k1="0.625 * mole**-1 * kilocalorie" id="t128" idivf1="1.0"></Proper>```

Should I switch the order of these? e.g. for Cc1ccccc1c2[nH]nnn2.

**Comment by davidlmobley** [comment]
From Chris Bayly:
> Regarding tetrazole: I propose ditching t128b in favor of the generic. The generic torsion is more broadly applicable to diazoles and triazoles (which are much less acidic) in addition to tetrazoles, and that properly reflects the chemistry this force field "knows", meaning we didn't do any science to distinguish the protonated tetrazole torsion from diazole and triazole, and all three are pretty closely related chemically. It is deprotonating the tetrazole that really changes that chemistry with delocalization and charge.

**Comment by davidlmobley** [comment]
@yudongqiu I think we have this one resolved now, right?

**Comment by yudongqiu** [comment]
@davidlmobley Yes I can confirm that the problem is solved when using [smirnoff99Frosst_experimental.offxml](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/data/test_forcefields/smirnoff99Frosst_experimental.offxml)
