### ISSUE TITLE
Rename chargeincrement attribute to charge_increment

### ISSUE THREAD

**Issue by andrrizzi** [openforcefield/openforcefield#348]
In the current spec of `ChargeIncrementModel` (not currently implemented), we are using the attribute `chargeincrement`. Should we rename it according to the naming conventions of the other attributes (i.e. `charge_increment`)?

**Comment by j-wags** [comment]
Yes. I think so. That was laziness on my part -- We recently changed the indexed values of `chargeincrement` from `charge#increment` to `chargeincrement#`, and I should have put an underscore in the middle.

**Comment by j-wags** [comment]
This was implemented here, but rolled back because the PR was getting too big, and this change will need to be accompanied by a SMIRNOFF spec update

https://github.com/openforcefield/openforcefield/pull/349#discussion_r292707035
