### ISSUE TITLE
Unexpected behavior: Parameter usage statistics incorrect when creating from SMILES without explicit hydrogens

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#362]
We've been estimating parameter usage statistics for a set of molecules and found that parameter usage is handled unexpectedly when a molecule is provided which does not have explicit hydrogens (which is not infrequent when creating a molecule from SMILES, as the below shows). Specifically, unless explicit hydrogens are provided, not all parameters are listed. For example:

```
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField
from openeye import oechem

# Create a simple molecule from SMILES and turn it into a topology.
smiles = "C#C"
mol = oechem.OEMol()
oechem.OESmilesToMol(mol, smiles)
molecule = Molecule.from_openeye(mol)
topology = Topology.from_molecules([molecule])

# Let's label using the smirnoff99Frosst force field
forcefield = ForceField('smirnoff99Frosst.offxml')

# Run the molecule labeling
molecule_force_list = forcefield.label_molecules(topology)

# Print out a formatted description of the parameters applied to this molecule
for mol_idx, mol_forces in enumerate(molecule_force_list):
    print(f'Forces for molecule {mol_idx}')
    for force_tag, force_dict in mol_forces.items():
        print(f"\n{force_tag}:")
        for (atom_indices, parameter) in force_dict.items():
            atomstr=''
            for idx in atom_indices:
                atomstr += '%3s' % idx
            print("atoms: %s  parameter_id: %s  smirks %s" % (atomstr, parameter.id, parameter.smirks) )
```

yields the following output:
```
Forces for molecule 0

Bonds:

Angles:

ProperTorsions:

ImproperTorsions:

vdW:
atoms:   0  parameter_id: n14  smirks [#6:1]
atoms:   1  parameter_id: n14  smirks [#6:1]

Electrostatics:

ToolkitAM1BCC:
```

Adding the single line:
`oechem.OEAddExplicitHydrogens(mol)`
after creation of the OEMol from the SMILES string results in the following (correct) output:

```
Forces for molecule 0

Bonds:
atoms:   0  1  parameter_id: b27  smirks [#6X2:1]#[#6X2:2]
atoms:   0  2  parameter_id: b85  smirks [#6X2:1]-[#1:2]
atoms:   1  3  parameter_id: b85  smirks [#6X2:1]-[#1:2]

Angles:
atoms:   0  1  3  parameter_id: a16  smirks [*:1]~[#6X2:2]~[*:3]
atoms:   1  0  2  parameter_id: a16  smirks [*:1]~[#6X2:2]~[*:3]

ProperTorsions:
atoms:   2  0  1  3  parameter_id: t156  smirks [*:1]-[*:2]#[*:3]-[*:4]

ImproperTorsions:

vdW:
atoms:   0  parameter_id: n15  smirks [#6X2:1]
atoms:   1  parameter_id: n15  smirks [#6X2:1]
atoms:   2  parameter_id: n10  smirks [#1:1]-[#6X2]
atoms:   3  parameter_id: n10  smirks [#1:1]-[#6X2]

Electrostatics:

ToolkitAM1BCC:
```

Using the internal `molecule = Molecule.from_smiles('C#C')` results in correct behavior, I believe.

This isn't actually incorrect, but also shouldn't lead to "silent failures" like at present. In my view, if a molecule is provided which is missing explicit hydrogens, the toolkit should either:
1) Add explicit hydrogens, or
2) Raise an exception that explicit hydrogens are missing

It shouldn't just print incorrect statistics. 

This has some overlap with https://github.com/openforcefield/openforcefield/issues/61 in that a molecule without all of its protons (or any other obviously incorrect molecule) shouldn't be just processed by the toolkit as if it is correct.

**Comment by jchodera** [comment]
Since this is meant to be a convenience function, and we dontl't have to worry about changing atom counts, the toolkit should automatically add explicit hydrogens in this case.

**Comment by j-wags** [comment]
Agreed. I had considered that the OEMol might have thought it was `[C-1]#[C-1]`, but that doesn't seem to be the case when I try to reproduce it here. I'll get this added ASAP.
