### ISSUE TITLE
Test FF (and smirnoff99Frosst) issues requiring fixing

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#367]
We have identified several cases where specific parameters in smirnoff99Frosst are not utilized when processing 1M molecules from eMolecules, and traced these to three types of problems that require fixing:
1) Hierarchy problems, where a less specialized parameter comes after a more specialized one
2) Typos in SMIRKS patterns/SMIRKS inaccuracies
3) A missing parameter (https://github.com/openforcefield/openforcefield/issues/336)
**In this issue I'll lay out the specific problems and what we plan to do to fix them.**

### Changes will happen here first, then in smirnoff99Frosst

Because of ongoing changes to infrastructure, we are not yet ready to roll these changes into the [smirnoff99frosst repo](https://github.com/openforcefield/smirnoff99frosst), though they need to end up there. So the current plan is to first
a) make the changes to the FF here in `test_forcefields`, documenting them here (so that @yudongqiu can go ahead and begin using them in fitting work), then 
b) after @j-wags gets the necessary infrastructure in place, bring the changes into a release in smirnoff99frosst

### Specific issues and changes
(Many discussed on Slack `#striketeam` channel  from June 20-24).

**Hierarchy problems**

- One group is t18 `[#1:1]-[#6X4:2]-[#6X3:3]=[#8X1:4]`, t19 `[#1:1]-[#6X4:2]-[#6X3:3]=[#6X3:4]` and t20 `[*:1]-[#6X4:2]-[#6X3:3]=[*:4]`. The last of these is the least specific and empties the other two. *It needs to be re-ordered to be before `t18` and `t19`.*
- We have `b57` and `b31` which are almost the same (carbon sulfur double bonds) but get rather different parameters; and `b57`, being more generic, empties `b31`. The patterns are `[#16:1]=[#6:2]` for `b57` (length 1.7, k=600) and `[#6X2:1]=[#16:2]` for `b31` (length 1.54, k=854). Chris Bayly explains: "b57 has a totally generic C=S smarts pattern with a C-S single bond length. So, first, it should before b31 because it is generic. Second, I think the CS bonds should be grouped together so we can understand the hierarchy better. Third, b57 should be left as generic C=S but with a bond length of 1.65 based on https://quod.lib.umich.edu/a/ark/5550190.0012.506/1". *Accordingly, we are moving `b57` to before `b31` and renaming it `b31a`.*
- The phenyl azide torsion (`t132`) is getting emptied by our “generic terminates with a triple bond” torsion, `t157`, `<Proper smirks="[*:1]~[*:2]-[*:3]#[*:4]" periodicity1="1" phase1="0.0 * degree" k1="0.0 * mole**-1 * kilocalorie" id="t157" idivf1="1.0"></Proper>` The `t132` case is `<Proper smirks="[#6:1]-[#7X2:2]~[#7X2:3]~[#7X1:4]" periodicity1="2" phase1="0.0 * degree" k1="0.0 * mole**-1 * kilocalorie" id="t132" idivf1="1.0"></Proper>` Chris Bayly notes: Regarding the phenyl azide torsion, since torsion t132 is zeroed-out like the generic t157, I think we should drop t132. It would cause no numerical differences and let the data drive speciation. Also, zeroed out torsions are often a null hypothesis to prevent the ff from erroring on a missing parameter. Sometimes however it was "active" parametrization when we found the 1-4 vdW and electrostatics were enough by themselves." *We are removing `t132`*
- Phosphorus-fluorine bonds: the parameter `<Bond smirks="[#15:1]~[#9:2]" length="1.639 * angstrom" k="600.0 * angstrom**-2 * mole**-1 * kilocalorie" id="b64"></Bond>` gets emptied by `<Bond smirks="[#15:1]-[#9:2]" length="1.6 * angstrom" k="880.0 * angstrom**-2 * mole**-1 * kilocalorie" id="b79"></Bond>` There should be no P-F bonds but single so these should be the same. Chris Bayly notes: "I agree we only need one of b64 and b79 and that P-F bonds are alway single as in b79. However the b64 bond length is the one I can vouch for (a B3LYP/6-311G(d,p) result) so I propose ditching b64 and changing the b79 bond length to 1.64." *Deleting b64 and changing b79 bond length accordingly*

I don’t think we expect any PF bonds EXCEPT single, so these should be a single parameter, right? Which value should be the starting value?

**Typos/SMIRKS fixes**

- A set involving N-C bonds for azides. Currently t81 (`[#7X1:1]~[#7X2:2]-[#6X3:3]~[#6X3:4]`), t82 (`[#7X1:1]~[#7X2:2]-[#6X4:3]-[#6X3:4]`) and t83 (`[#7X1:1]~[#7X2:2]-[#6X4:3]~[#1:4]`) are problematic. This was discussed [on our Slack](https://openforcefieldgroup.slack.com/archives/CKSHCE7SB/p1561002003008000). Chris Bayly tracked down parm@frosst parent parameters `NL-NL-CA-CA`, `NL-NL-CT-CA` and `NL-NL-CT-H1` and notes "They are for azides which have the resonance forms `R-N=[N+]=[N-] <-> R-[N-]-[N+]#N`; clearly in my SMARTS strings the `[#7X1]` is a mistake and should be `[#7X2]`; I put in the terminal N one atom too soon. Nevertheless, the correct SMARTS strings (to capture both azide resonance forms of azide) should be:" t81 `[#7X2:1]~[#7X2:2]-[#6X3:3]~[#6X3:4]`, t82 `[#7X2:1]~[#7X2:2]-[#6X4:3]-[#6X3:4]`, and t83 `[#7X2:1]~[#7X2:2]-[#6X4:3]~[#1:4]`
- `t102` matches nothing. From Chris Bayly: "t102 `[#1:1]-[#8X2H1:2]-@[#6X3:3]~[*:4]` is a problem, as in "what was I thinking?". For one thing, the ring '@' in the central bond makes this fragment impossible to match ("endocyclic hydroxyl"?), though the first two atoms are really specific for hydroxyl. For another, the barrier is really high (2.5 kcal/mol). So what was I thinking? Back in "the provenance" of smirnoff99Frosst I labeled this as "generic endocyclic". So I think I was not meaning hydroxyl but furan type fragment, so I propose this for t102:`[*:1]-[#8X2:2]-@[#6X3:3]~[*:4]` which makes it a strongly-conjugated version of t96 for conjugated endocyclic ethers like furan. If that now leaves conjugated hydroxyl getting the generic t96, parm@Frosst thinks this is not too far off so that might be OK until the data drives it elsewhere." After further discussion we found the central bond should be `@` not `-@` so I have updated to address that. We checked this on `c1(O)conc1` to ensure it uses `t97` and `t102` as it ought.
- `b22`, `[#6X3:1]:[#8X2+1:2]`, intended for aromatic oxoniums like peonin and cyanidin, were not matching anything (nor those molecules); it seems they are not perceived as aromatic, and this was falling back to the more generic `b20` `[#6:1]=[#8X1+0,#8X2+1:2]`. After discussion with Chris Bayly, we are changing `b22` to `[#6X3:1]~[#8X2+1:2]~[#6X3]`. 

**Unnecessary parameters**

We're also checking to ensure all parameters get used, and some remaining parameters are still too generic or have other issues. Specifically:
-  `t53`, `[*:1]-[#7X4,#7X3:2]-[#6X4;r3:3]-[*:4]`, is a generic that is followed by `t54` which covers the case where there is a proton in the 1 position, and `t56` which covers the case where there is not a proton in the 1 position. Thus it should never be used and needs to be removed.
- `t153`, `[*:1]~[#7X4:2]-[#15:3]~[*:4]`, is an adaptation of chemistry implied by GAFF atom types (see https://github.com/openforcefield/smirnoff99Frosst/issues/32) but we're having trouble finding instances of this, so I am removing for now. We can re-add if we find molecules where it occurs.
- `b51` and `b55`: We are merging. Chris Bayly writes:
> Regarding the S-O single bond and b51, I suggest combining b51 and b55:
> `<Bond smirks="[#16X2:1]-[#8X2:2]" id="b51" k="600.0" length="1.60"/>`
> `<Bond smirks="[#16X4,#16X3:1]-[#8X2:2]" id="b55" k="600.0" length="1.596"/>`
into a single generic:
>`<Bond smirks="[#16:1]-[#8X2:2]" id="b51" k="600.0" length="1.60"/>`
>because I think that covers all the S-O single bond cases, the two are effectively redundant, and it looks like that is the best science we have so far in this force field. Let the data drive speciation. One fewer parameters and a simpler one at that... it's that easy! Up with SMIRNOFF!

**New parameters needed**
- tetrazole torsion, https://github.com/openforcefield/openforcefield/issues/336

**Comment by j-wags** [comment]
I think it's really important that we do this work, but:
1) tying in these changes/this commit history into the OFF toolkit risks getting important provenance info swept away in a torrent of toolkit commits.
2) The `smirnoff99Frosst.offxml` in this repo is used in spec-equivalence tests, so its contents need to match the contents of two other files (otherwise tests will fail). I'd prefer to avoid changing `smirnoff99Frosst.offxml` itself, and would ask that we use a different file name like `smirnoff99Frosst-experimental.offxml` if we do decide to make modifications here.
3) It'll be inconvenient to version/access this file, since @yudongqiu will need to `git clone` this repo (>200MB), and the `master` branch may contain API-breaking changes at any time.

Unless very important information is already in this repo's commit history, I'd suggest making these file changes on a branch of `openforcefield/smirnoff99Frosst`.

**Comment by jchodera** [comment]
I hadn't realized `smirnoff99Frosst.offxml` is used in spec equivalence tests! Perhaps we shouldn't do that, and instead rename it something else, like `spec-equivalence-test-1.offxml` or put it in `test_data/spec-equivalence-tests/` to make this obvious?

> It'll be inconvenient to version/access this file, since @yudongqiu will need to git clone this repo (>200MB), and the master branch may contain API-breaking changes at any time.

Holy crap, we need to fix that if the repo is >200MB.

You can also `wget` the file directly if you just want the one file, or conda install the toolkit and use the file from the `test_data/` path.

> Unless very important information is already in this repo's commit history, I'd suggest making these file changes on a branch of openforcefield/smirnoff99Frosst.

That's where these changes should ultimately go, but we have been waiting for you to refactor that repo.

**Comment by j-wags** [comment]
> I hadn't realized smirnoff99Frosst.offxml is used in spec equivalence tests! Perhaps we shouldn't do that, and instead rename it something else, like spec-equivalence-test-1.offxml or put it in test_data/spec-equivalence-tests/ to make this obvious?

Ahh, I misspoke here. The spec-equivalence tests are run using the FFs in `test_forcefields/old`. A few other tests do simple tests on the contents of this file (such as counting parameters), but they can be modified with updated numbers so they pass.

> Holy crap, we need to fix that if the repo is >200MB. Was this due to large files? If so, they should be removed from git history.

This is the suggestion in #43. Andrea and I keep assigning this to upcoming milestones, but never get to it. We spoke just this morning and agreed that, after the 0.6.0 release, we really need to spend a few weeks on housekeeping issues. 

>That's where these changes should ultimately go, but we have been waiting for you to refactor that repo.

Ok. I see I'm blocking on this issue. I think I'd made some progress on this previously. Let me see if I can prioritize this ASAP. Until I do, let's keep making these changes in the toolkit repo.

**Comment by davidlmobley** [comment]
Will keep making these changes here, but absolutely amenable to renaming things as needed to avoid problems with spec equivalence tests. I agree that it might make sense to have those files have very distinctive names to prevent anyone from using them for anything.

**Comment by davidlmobley** [comment]
I have finished dealing with these issues and will work on finalizing the PR for review.

**Comment by davidlmobley** [comment]
Closed by #368
