### ISSUE TITLE
Add ForceField.registered_handler_names (Add handy handling of handlers)

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#369]
**Is your feature request related to a problem? Please describe.**
I want to be able to loop over all parameter handlers in a force field, but I have no way to dig up the names of all registered handlers.

**Describe the solution you'd like**
`ff.registered_handler_names` should return a list of strings, each of which could be fed to `ff.get_parameter_handler(handler_name)`

**Describe alternatives you've considered**
```
for handler_name in ff._parameter_handlers.keys():
    handler = ff.get_parameter_handler(handler_name)
```

**Comment by jchodera** [comment]
@andrrizzi: can you give a usage example?

**Comment by davidlmobley** [comment]
I just ran into wishing I had this, again. :)
