### ISSUE TITLE
Make missing valence errors more informative

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#388]
**Is your feature request related to a problem? Please describe.**
Missing valence errors aren't very informative right now. They only return topology atom indices. These are at least off-by-one from the indexing system in a single mol2, and would be even more confusing if a `Topology` were defined using multiple copies of molecules (instead of a PDB).

**Describe the solution you'd like**
The atom representation printed in this error should be of the form `f{atom.element}{atom.topology_atom_index}`.

https://github.com/openforcefield/openforcefield/blob/master/openforcefield/typing/engines/smirnoff/parameters.py#L1589-L1653

**Describe alternatives you've considered**
The `__repr__` of `TopologyAtom` could be made into this format, but this may not be suitable for all instances where the `TopologyAtom` needs to be printed.

https://github.com/openforcefield/openforcefield/blob/master/openforcefield/topology/topology.py#L257-L259

**Comment by j-wags** [comment]
Thinking more about this -- If the `Topology` comes from PDB, then `f"{element}{topology_atom_index}"` is fine. But if the `Topology` comes from a concatenation of molecules (`Topology.from_molecules([molecule_list])`), then the user won't know what a certain topology_atom_index corresponds to. In the latter case, it would be most useful to provide the `molecule_atom_index`, and some representation of the underlying reference molecule (maybe a tagged SMILES? This would be most useful but require a bit more effort). As a quick solution, we could offer the Hill formula of the molecule.

**Comment by davidlmobley** [comment]
I was thinking about whether there were better days to do it. I wondered about whether we'd be OK introducing a ChemPer dependency and asking it to generate SMIRKS for the environment out to, say, two layers. One problem might be that it might generate too-complex SMIRKS that FULLY describe the environment, but maybe there is a way to turn that off.

To me the best way would seem to be to generate a description of the fragment which is involved in the torsion somehow. If there's no easy way to do it with ChemPer, we could simply print elements, connectivities and bond orders.

**Comment by jchodera** [comment]
The `Topology` object knows what molecules it is composed of, so it should be able to tell the user
* the specific molecule that is missing a valence term
* the specific unique atom names corresponding to them; if atom names are not provided

Currently, not all `Molecule` objects will have unique atom names, but that makes debugging very hard. I think we should always have `Molecule` objects create unique atom names if they do not exist so that it is always possible for someone to debug this by writing the `Molecule` to a format they can read (or just printing it) and inspecting the unique atom names.

**Comment by jaimergp** [comment]
+1 on atom names (and residues/molecules?). This is currently a problem when interacting with ParmEd.

**Comment by jchodera** [comment]
I think the simplest behavior change that would be sensible is, as stated above:

`Molecule` objects should create unique atom names upon molecule creation if atom names are not specified or are not unique.

**Comment by j-wags** [comment]
Before I lose it, here's a code snippet I used for atom name assignment in a test involving ParmEd. 
```
molecule = Molecule.from_file(mol2_file_path, allow_undefined_stereo=allow_undefined_stereo)
for idx, atom in enumerate(molecule.atoms):
    atom.name = f'{atom.element.symbol}{idx}
```

**Comment by j-wags** [comment]
#394 adds a "good enough" solution to this issue for now. We can reopen if it becomes a big performance problem later on.
