### ISSUE TITLE
Make cosmetic attributes public

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#393]
**Is your feature request related to a problem? Please describe.**
There's no public way within the API to see if an already-existing attribute is cosmetic. ForceBalance needs to check if certain attributes are cosmetic. https://github.com/leeping/forcebalance/pull/151/files#diff-1075646a3fd36fc66a1baec7dfd03793R166-R167

**Describe the solution you'd like**
`attribute.is_cosmetic()` or `attrib_name in parameter.cosmetic_attributes`

**Describe alternatives you've considered**
`attrib_name in parameter._cosmetic_attribs`

**Additional context**
This is a necessary API point for ForceBalance

**Comment by SimonBoothroyd** [comment]
It would be great to have this! Currently we have to access private members of parameters to check if an attribute is cosmetic or not which is not great and breaks easily!
