### ISSUE TITLE
Code comment problems/documentation issues relating to `Molecule.positions`

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#405]
I'm trying to make a minimal example that loads a molecule from a mol2 file and then energy minimizes it. It turns out this is somewhat nontrivial given the current docs as it's not totally clear how to retrieve the positions from an OpenFF `Molecule` and/or `Topology` to use in setting the positions when I initialize an openMM simulation.

Looking for info on this led me to this code snippet in the tests: https://github.com/openforcefield/openforcefield/blob/35b54c5acb5d9e635caa2a9123b336e51095ece5/openforcefield/tests/test_smirnoff.py#L251-L266

However, the doc string there is inconsistent with the function. The doc string says the function takes "molecule : openforcefield.topology.Molecule" but it seems to actually take an OEMol. (Reading the doc string caused me to try to access a `Molecule.positions` for an OpenFF Mol but there is no such attribute).

Overall I think this means:
a) We need to provide access to positions in our topology/molecules (wherever stored)
b) We need to document this
c) We should provide an example of using it, e.g. to do a minimization (Right now our examples only access positions loaded from an OpenMM object like a `PDBFile`, e.g. https://github.com/openforcefield/openforcefield/blob/master/examples/SMIRNOFF_simulation/run_simulation.ipynb) 
d) We should fix the doc strings in the test linked to above
d)

**Comment by j-wags** [comment]
This is redundant with #387. Closing this to keep the issue in one place.
