### ISSUE TITLE
Unable to load toolkit <openforcefield.utils.toolkits.OpenEyeToolkitWrapper

### ISSUE THREAD

**Issue by bgobbi** [openforcefield/openforcefield#406]
I installed the new version according to the instructions but did not install the openeye toolkit.

When trying to run the "SMIRNOFF_simulation" example I get this error after:
```
from openforcefield.utils import get_data_file_path
```
```
Unable to load toolkit <openforcefield.utils.toolkits.OpenEyeToolkitWrapper object at 0x2aaad2cf0f28>.
```

Is this exp[ected? I thought the version does not require OE?

Thanks,
Alberto

**Comment by davidlmobley** [comment]
It doesn't require OE, so this SHOULD work (and in fact is a tested option). Could you specify a bit more about how you're installing? That is, are you using the package installer, or installing from conda?  What platform?

**Comment by j-wags** [comment]
Yes -- when you first import the toolkit, it will _attempt_ to load OE, but if it doesn't, it will use RDKit. Right now, we don't pull down OpenEye by default. So this is completely expected behavior, and your toolkit installation should be fully functional.
