### ISSUE TITLE
ParameterError after update

### ISSUE THREAD

**Issue by ljmartin** [openforcefield/openforcefield#444]
Hi all,
I updated openforcefield/openforcefields using `conda install -c omnia openforcefield openforcefields` this morning and tried to use `ff = ForceField('openff-1.0.0.offxml')` but I may have missed something, as now code that used to work is getting a ParameterError after `createSystem`. Would appreciate if anyone can point me to a solution?
Thankyou!

Gist with minimal example using just propane:
https://gist.github.com/ljmartin/77e01e2b1cc5e9b4c274fff565e4fe96

error:
```
##Create drug system:
drug_system = drug_structure.createSystem(nonbondedMethod=PME, nonbondedCutoff=0.9*nanometer)
>>>
---------------------------------------------------------------------------
ParameterError                            Traceback (most recent call last)
<ipython-input-6-2c7ab80dfea0> in <module>
----> 1 drug_system = drug_structure.createSystem(nonbondedMethod=PME, nonbondedCutoff=0.9*nanometer)

~/miniconda3/envs/lew_conda/lib/python3.7/site-packages/parmed/utils/decorators.py in new_fcn(*args, **kwargs)
     29         if not SUPPORTED_VERSION:
     30             raise ImportError('You must have at least OpenMM 6.3 installed')
---> 31         return fcn(*args, **kwargs)
     32 
     33     return new_fcn

~/miniconda3/envs/lew_conda/lib/python3.7/site-packages/parmed/structure.py in createSystem(self, nonbondedMethod, nonbondedCutoff, switchDistance, constraints, rigidWater, implicitSolvent, implicitSolventKappa, implicitSolventSaltConc, temperature, soluteDielectric, solventDielectric, useSASA, removeCMMotion, hydrogenMass, ewaldErrorTolerance, flexibleConstraints, verbose, splitDihedrals)
   2028         LOGGER.info('Adding bonds...')
   2029         self._add_force_to_system(system,
-> 2030                 self.omm_bond_force(constraints, rigidWater, flexibleConstraints)
   2031         )
   2032         LOGGER.info('Adding angles...')

~/miniconda3/envs/lew_conda/lib/python3.7/site-packages/parmed/utils/decorators.py in new_fcn(*args, **kwargs)
     29         if not SUPPORTED_VERSION:
     30             raise ImportError('You must have at least OpenMM 6.3 installed')
---> 31         return fcn(*args, **kwargs)
     32 
     33     return new_fcn

~/miniconda3/envs/lew_conda/lib/python3.7/site-packages/parmed/structure.py in omm_bond_force(self, constraints, rigidWater, flexibleConstraints)
   2258                 continue
   2259             if bond.type is None:
-> 2260                 raise ParameterError('Cannot find necessary parameters')
   2261             force.addBond(bond.atom1.idx, bond.atom2.idx, bond.type.req*length_conv,
   2262                           2*bond.type.k*frc_conv)

ParameterError: Cannot find necessary parameters
```

**Comment by j-wags** [comment]
Hi @ljmartin ,

Thanks for the report and reproducing example!

This is happening because `openff-1.0.0.offxml` includes hydrogen bond length constraints in the force field definition, which makes the original bond `k` values get lost in this workflow. We quietly updated [the examples](https://github.com/openforcefield/openforcefield/blob/8baf5da16418e64f75e648e5a96e155c6c5d4dec/examples/using_smirnoff_in_amber_or_gromacs/convert_to_amber_gromacs.ipynb) to fix this, but probably should have been more verbose about the needed changes.

To fix this, you should load the force field _without_ hbond length constraints (`openff_unconstrained-1.0.0.offxml`):
```
ff = ForceField('openff_unconstrained-1.0.0.offxml')
```
 and have ParmEd apply them with the `constraints=HBonds` keyword argument to `create_structure` in the last cell:
```
from simtk.openmm import app
drug_system = drug_structure.createSystem(nonbondedMethod=PME, 
                                          nonbondedCutoff=0.9*nanometer, 
                                          constraints=app.HBonds)
```

This fix worked for me in the notebook you sent. Please let me know if it clears up the issue for you.

**Comment by jchodera** [comment]
This is a peculiarity of going through the OpenMM `System` representation, and would be resolved once we can implement https://github.com/openforcefield/openforcefield/issues/310

**Comment by ljmartin** [comment]
Thankyou very much for the explanation! That works.

Didn't realise the examples had been updated but it's pretty clear in the one you linked.
cheers
