### ISSUE TITLE
Create unique atom names for Molecule object on creation

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#460]
**Is your feature request related to a problem? Please describe.**
Currently, when we create a `Molecule`, it's possible to construct one where the atoms lack unique names. This causes problems when we pass them to other tools that require unique atom names.

**Describe the solution you'd like**
When constructing a `Molecule` object from another molecule that lacks unique atom names, we should create unique atom names. We could also check that provided atom names are unique when constructing atom-by-atom, but this is less critical.

**Describe alternatives you've considered**
Forcing the user to always specify a molecule as input with unique atom names seems overly burdensome.

Another alternative could be to have a `Molecule.normalize()` or `Molecule.validate()` option that checked for unique atom names and enforced them as being unique at that time, and we would only call this before using or exporting the molecule.

**Comment by mark-cresset** [comment]
This is particularly important if you're going to be using SDF files as inputs, which lack any facility for naming atoms.

**Comment by davidlmobley** [comment]
Ahh, it looks like this is headed for the `0.7.0` release, @j-wags ? But it's already reoslved in master?
