### ISSUE TITLE
Partial, formal, and total charges are reported with inconsistent units

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#465]
The current version of the toolkit reports partial, formal, and total charges with inconsistent units:
```python
>> from openforcefield.topology import Molecule
>>> molecule = Molecule.from_smiles('c1ccccc1')
>>> molecule.total_charge
0
>>> molecule.atoms[0].formal_charge
0
>>> molecule.atoms[0].partial_charge
Quantity(value=0.0, unit=elementary charge)
>>> molecule.partial_charges
Quantity(value=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), unit=elementary charge)
```
Instead, we should presumably adopt a consistent output format (with or without units) for all charge-related quantities.

**Comment by j-wags** [comment]
Good catch. #471 will standardize to report partial and formal charges in units of elementary charge.

**Comment by j-wags** [comment]
I'm also making the setter for `Atom.formal_charge` accept `int` or `Quantity`, since there's a good argument for both. All getters will return Quantity, and all other setters will require Quantity.
