### ISSUE TITLE
AM1-BCC charging fails on carboxylates with newer versions of antechamber

### ISSUE THREAD

**Issue by mark-cresset** [openforcefield/openforcefield#473]
**Describe the bug**
If you use a newer version of antechamber than the one packaged with the toolkit then the am1bcc pathway fails

**To Reproduce**
Example molecule attached. This parameterises fine with the antechamber packaged with the toolkit, but if you instead use antechamber from AmberTools 19, the second call to antechamber on line 2753 of toolkits.py (in compute_partial_charges_am1bcc) fails.

[molecule.sdf.gz](https://github.com/openforcefield/openforcefield/files/3973225/molecule.sdf.gz)

The reason is that the newer versions of antechamber include the AC Doctor functionality, which leads to antechamber being unable to read the mol2 files that it writes for caboxylates: it writes both the C-O bonds as single, but then complains on read that the carbon is only 3-valent.

**Output**
Welcome to antechamber 19.0: molecular input file processor.

acdoctor mode is on: check and diagnose problems in the input file.
-- Check Format for mol2 File --
   Status: pass
-- Check Unusual Elements --
   Status: pass
-- Check Open Valences --
   Status: pass
-- Check Geometry --
      for those bonded   
      for those not bonded   
   Status: pass
-- Check Weird Bonds --
/home/mark/gui/trunk/buildDependencies/AmberTools/linux-x86_64/bin/antechamber: Fatal Error!
Weird atomic valence (3) for atom (ID: 17, Name: C14).
       Possible open valence.

**Computing environment (please complete the following information):**
 - Debian 10.2
 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ambermini                 16.16.0                       7    http://conda.binstar.org/omnia
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boost                     1.70.0           py37h9de70de_1    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bson                      0.5.8                      py_0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
cryptography              2.8              py37h72c5cf5_0    conda-forge
cython                    0.29.14          py37he1b5a44_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
fftw3f                    3.3.4                         2    http://conda.binstar.org/omnia
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
importlib_metadata        0.23                     py37_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.9.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                hc3755c2_1    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openforcefield            0.6.0                    py37_0    http://conda.binstar.org/omnia
openforcefields           1.0.0                    py37_0    http://conda.binstar.org/omnia
openmm                    7.4.0           py37_cuda101_rc_1    http://conda.binstar.org/omnia
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parmed                    3.2.0            py37hc99cbb1_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.1            py37hd70f55b_1    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycairo                   1.18.2           py37h438ddbb_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pyrsistent                0.15.5           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
rdkit                     2019.09.1        py37hb31dc5d_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
six                       1.13.0                   py37_0    conda-forge
smirnoff99frosst          1.1.0                    py37_1    http://conda.binstar.org/omnia
sqlite                    3.30.1               hcee41ef_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toml                      0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge

**Additional context**
This isn't a problem with the toolkit as it stands: we only noticed it as we are trying to minimise the number of different instances of the amber tools that we bundle... 

There are two possible fixes:
- Specify "-dr n" to the second antechamber call
- Use ac as the intermediate file format between the two calls rather than mol2

**Comment by davidlmobley** [comment]
See also #130 

Though this suggests a relatively simple fix that will solve both, I think: Switch to the newer antechamber while also changing how antechamber is called.

Tagging @j-wags and @trevorgokey

**Comment by aniketsh** [comment]
@j-wags @mark-cresset 
Hi, I am having the same issue with AmberTools 19, and "-dr n" option didn't fix it for me; I have followed the other threads mentioned above as well, but couldn't find any solution, other than to switch back to an older version of AmberTools.

**Comment by jchodera** [comment]
I'm able to charge the [original example](https://github.com/openforcefield/openforcefield/issues/473#issue-539032954) using the latest version, which uses `ambertools` 19.11 from `conda-forge`:
```python
>>> from openforcefield.topology import Molecule
>>> m = Molecule.from_file('molecule.sdf')
>>> m.total_charge
-1
>>> m.compute_partial_charges_am1bcc()
>>> m.partial_charges
Quantity(value=array([-0.15424001,  0.05277   , -0.17367999, -0.04852   , -0.09211   ,
       -0.16841   , -0.07853   , -0.09747   ,  1.51713014, -0.41382   ,
       -0.1612    ,  0.66460001, -0.44679999, -0.7723    ,  0.0754    ,
        0.0295    ,  0.91206998, -0.65297997, -0.65297997, -0.63264   ,
       -0.83274996, -0.01576   ,  0.18381   , -0.83274996, -0.10109   ,
       -0.16841   , -0.07853   , -0.1779    , -0.17925   , -0.13185   ,
        0.05963   ,  0.05963   ,  0.05963   ,  0.13922   ,  0.16003001,
        0.15674999,  0.14692   ,  0.37865999,  0.44722998,  0.18339001,
        0.16755   ,  0.15674999,  0.14692   ,  0.14906999,  0.11068   ,
        0.10663   ]), unit=elementary charge)
```

**Comment by jaimergp** [comment]
Following this issue 👀

**Comment by aniketsh** [comment]
@jchodera 
I did following as per the thread and tested on the molecule provided in the thread but still no luck: Is there something else I need to change?
--------------------------------------------------------------------------
conda install ambertools=19.11 -c conda-forge 
Collecting package metadata (current_repodata.json): done
Solving environment: done
# All requested packages already installed.
--------------------------------------------------------------------------
>>> from openforcefield.topology import Molecule
>>> m = Molecule.from_file('molecule.sdf')
>>> m.total_charge
-1
>>> m.compute_partial_charges_am1bcc()
Exception: Antechamber/sqm partial charge calculation failed on molecule 5KR (SMILES [H][C]1=[C]([H])[C]([H])=[C]([N]([H])[C](=[O])[C]2=[C]([H])[C]([H])=[C]([C]([H])([H])[H])[C]([S](=[O])(=[O])[N]([H])[C]3=[C]([H])[C]([H])=[C]([Br])[C]([H])=[C]3[H])=[C]2[H])[C]([C](=[O])[O-])=[C]1[H])
------------------------------------------------------------------------------------------------

**Comment by aniketsh** [comment]
@jchodera #Solved

My bad, I reinstalled the openforcefield, and had forgotten to put "-dr no", it works now with ambertools=19.11!
 
Thanks a lot.

**Comment by jchodera** [comment]
We think this is addressed!
Please re-open if there are still lingering issues.
