### ISSUE TITLE
Add InChI Support

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#474]
**Is your feature request related to a problem? Please describe.**
It would be useful for the toolkit to support creating `Molecule` objects from [InChI](https://iupac.org/who-we-are/divisions/division-details/inchi/) strings in addition to SMILES strings. InChI keys appear to be cheminformatic-toolkit independant due to their fixed spec.

**Describe the solution you'd like**
Add a new `Molecule.from_inchi(inchi: str) -> Molecule` class method which creates a `Molecule` from an InChI string.

**Comment by jchodera** [comment]
Can we also add `Molecule.to_inchi()` at the same time?

**Comment by jthorton** [comment]
This should be added in during the planned cmiles merge.

**Comment by ChayaSt** [comment]
While InchI's are cheminformatics toolkit independent, they can also be a bit lossy. For example, you will get the same InchI for different tautomers. See this [notebook](https://github.com/openforcefield/cmiles/blob/master/notebooks/Tautomers.ipynb) for some examples.

**Comment by jchodera** [comment]
@ChayaSt : InchI has a Fixed-H later that allows you to represent a specific tautomer if you include it.

**Comment by jchodera** [comment]
@ChayaSt : InchI has a Fixed-H later that allows you to represent a specific tautomer if you include it.

https://www.inchi-trust.org/technical-faq-2/#6

**Comment by jthorton** [comment]
It looks like you can set this option in RDKit using `rdkit.Chem.rdinchi.MolToInchi(rdkit_mol, options='-FixedH')` or in openeye with `opts = oechem.OEInChIOptions()
opts.SetFixedHLayer(True)` which adds the fixed hydrogen layer but gives non-standard strings. Would we want the identifers to give non-standard strings or both?

**Comment by ChayaSt** [comment]
That is true, but then it is not the standard InChI. `cmiles` only provides the standard InChI and I would argue that is what the `cmiles` identifiers should provide because it is used for standardization. 

However, this functionality might be good enough for creating an OFF molecule independent of `cmiles` identifiers where input should be less stringent.

**Comment by jthorton** [comment]
I guess its then up to the user to ensure they have the correct InchI key when trying to make a molecule so this should be safe to include as a new class method. Then we could have  `mol.to_inchi(fixedH=False)` and `mol.to_inchikey(fixedH=False)`  which can still be used to make standard `cmiles` identifiers or tautomer specific ones?

**Comment by ChayaSt** [comment]
Yes. The default for `mol.to_inchi()` and `mol.to_inchikey()` should be the standard InchI.

**Comment by jchodera** [comment]
> That is true, but then it is not the standard InChI. cmiles only provides the standard InChI and I would argue that is what the cmiles identifiers should provide because it is used for standardization.

@ChayaSt: We do want to uniquely identify distinct chemical species with `cmiles`, as well as being able to collect all tautomers of the same species, so we need _both_ kinds of InChI in `cmiles`.

**Comment by ChayaSt** [comment]
@jchodera, the SMILES are used to uniquely identify chemical species. InChI is there for standardization to collect all tautomers of the same species. Is there a need to also have non standard InChI if we already have isomeric SMILES for that purpose?

**Comment by jchodera** [comment]
No, as long as it's clear that constructing a molecule from that InChI will _not_ give you the molecule the calculation was done on!
