### ISSUE TITLE
Atom ordering changes during molecule file format conversion.

### ISSUE THREAD

**Issue by dfhahn** [openforcefield/openforcefield#475]
There is an issue when converting SDF files to PDB with the OFF toolkit (based on the OpenEye toolkit), i.e. doing
`ligand = Molecule.from_file('lig_23475.sdf', 'sdf')`
`ligand.to_file('lig_23475.pdb', 'pdb')`
The resulting PDB file has a different atom order than the initial SDF, which is problematic if one has e.g. associated topology files for a given atom order. 
Using the same code based on the RDKit instead of the OpenEye toolkit, the atom order stays the same. See the attached notebook.
I assume it is not a bug (rather a feature) in the OpenEye toolkit. Can one force the same atom ordering?

**Comment by dfhahn** [comment]
The  `openforcefield.topology.Molecule` object still has the same atom ordering. It happens during writing to pdb.

**Comment by dfhahn** [comment]
Attempting to writing the `ligand` to a MOL format file results in a 
> KeyError: 'MOL'
with both RDKit and OE.

**Comment by j-wags** [comment]
@dfhahn I don't think we support OE or RDKit writing out MOL format (though we could without too much trouble). Maybe you're thinking of `mol2`?

**Comment by jchodera** [comment]
> I assume it is not a bug (rather a feature) in the OpenEye toolkit. Can one force the same atom ordering?

I suspect switching to use the [low-level OpenEye molecule writers](https://docs.eyesopen.com/toolkits/python/oechemtk/molreadwrite.html#flavored-input-and-output) will fix this.

**Comment by jchodera** [comment]
Actually, one more important question: Does the resulting file have hydrogens? We may accidentally be dropping hydrogens, which would also change the atom order.

**Comment by dfhahn** [comment]
> @dfhahn I don't think we support OE or RDKit writing out MOL format (though we could without too much trouble). Maybe you're thinking of mol2?

Ok, sorry. OE writes out mol2, and the atom ordering is correct there. For RDKit, mol2 is not supported, right?

> I suspect switching to use the low-level OpenEye molecule writers will fix this.

The low level writer `OEWritePDBFile` does not print a connection table.

> Actually, one more important question: Does the resulting file have hydrogens? We may accidentally be dropping hydrogens, which would also change the atom order.

The resulting files have hydrogens.

**Comment by dfhahn** [comment]
> The low level writer `OEWritePDBFile` does not print a connection table.

Found a solution: One can print the `CONECT` by defining the flavor `oechem.OEOFlavor_PDB_BONDS` int the `OEWritePDBFile` function. This function indeed does not alter the atom ordering! 
@jchodera Thanks!
@j-wags  What about changing the OFF toolkit to this function instead of `oechem.OEWriteMolecule`?

```
from openeye import oechem
from simtk import unit
import itertools
import numpy as np

oemol = ligand.to_openeye()

ofs = oechem.oemolostream('lig_23475_oechem_writepdb.pdb')
oechem.OEOFlavor_PDB_BONDS=True
oechem.OEWritePDBFile(ofs, oemol, oechem.OEOFlavor_PDB_BONDS)

ofs2 = oechem.oemolostream('lig_23475_oechem_writemolecule.pdb')
ofs2.SetFormat(oechem.OEFormat_PDB)
oechem.OEWriteMolecule(ofs2, oemol)

oemol2 = oechem.OEMol()
ifs2 = oechem.oemolistream('lig_23475_oechem_writepdb.pdb')
oechem.OEReadPDBFile(ifs2, oemol2)

oemol3 = oechem.OEMol()
ifs3 = oechem.oemolistream('lig_23475_oechem_writemolecule.pdb')
oechem.OEReadPDBFile(ifs3, oemol3)

confs = [ligand.conformers[0].value_in_unit(unit.angstrom), #input
    oemol.GetCoords(), #input converted to OEMol
    oemol2.GetCoords(), #OEMol written by writepdb function
    oemol3.GetCoords()] #OEMol written by writemolecule function

print('X-coordinates of molecules:')
print('{:>15s}{:>15s}{:>15s}{:>15s}{:>15s}'.format('Index', 'Original(OFF)', 'Original(OE)', 'WritePDB', 'WriteMolecule'))
for i in range(len(confs[0])):
    x  = [conf[i][0] for conf in confs]    
    for pair in itertools.combinations(x,2):
        if not np.isclose(pair[0], pair[1], atol=1e-2):
            print('{:15d}{:15.1f}{:15.1f}{:15.1f}{:15.1f}'.format(i, *x))
            break
```

X-coordinates of molecules
          Index  Original(OFF)   Original(OE)       WritePDB  WriteMolecule
             21           40.0           40.0           40.0           39.3
             22           40.6           40.6           40.6           37.8
             23           44.4           44.4           44.4           37.5
             24           43.9           43.9           43.9           38.7
             25           41.7           41.7           41.7           39.9
             26           38.8           38.8           38.8           40.0
             27           39.7           39.7           39.7           40.6
             28           40.3           40.3           40.3           44.4
             29           39.3           39.3           39.3           43.9
             30           37.8           37.8           37.8           41.7
             31           37.5           37.5           37.5           38.8
             32           38.7           38.7           38.7           39.7
             33           39.9           39.9           39.9           40.3
