### ISSUE TITLE
Switch from ambermini to ambertools in omnia package

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#487]
Currently, our omnia package uses [`ambermini`](https://github.com/omnia-md/conda-recipes/blob/09071a6cc02d0b2d2a2730a2d6b2f7af1fd30803/openforcefield/meta.yaml#L38) as a dependency. This causes issues because some of our more modern tools install `ambertools` instead, and the collision of the two causes unstable behavior or behavior that depends on the order in which the two packages are installed.

We should standardize on `ambertools`, which is much more up to date, and use the [AmberMD](https://anaconda.org/ambermd) channel until the well-maintained [conda-forge channel](https://anaconda.org/conda-forge/ambertools/files) has the [`osx` builds working](https://github.com/conda-forge/ambertools-feedstock/pull/11). @jaimrgp is working on this right now, so I think we can do this soon. 

But we're going to have lots of stability / incorrect results issues until we fix this.

**Comment by jaimergp** [comment]
My last attempts at getting `osx` to build hit what I think it's a CMake configuration error on AmberTools' side. I am going to need help from the developers but I haven't reached out yet. I'll keep you posted!

**Comment by jchodera** [comment]
Thanks to @jaimergp's fantastic work, we now have `ambertools` built for both `osx` and `linux` on [`conda-forge`](https://anaconda.org/conda-forge/ambertools/files)!

We should move ahead with these changes ASAP to resolve these issues now.

**Comment by jchodera** [comment]
Fixed by https://github.com/omnia-md/conda-recipes/pull/1009
