### ISSUE TITLE
Maximum Smarts Matches for Larger Molecules

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#491]
**Describe the bug**

Currently both the RDKit and OpenEye toolkit backends cap the maximum number of matches which can be found for a given smarts pattern to [1000](https://www.rdkit.org/docs/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.Mol.GetSubstructMatches) and [1024](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemClasses/OESubSearch.html#OEChem::OESubSearch::GetMaxMatches) respectively (relevant to the toolkit `_find_smarts_matches` methods).

When trying to assign parameters to larger molecules such as (bio)polymers this leads to many `UnassignedXParameterException` exceptions being raised for even simple things like an aromatic torsion, but only for valence terms between atoms with higher indices.

In the case of OpenEye a hard to spot `Warning: default number of matches limit reached in substructure search` warning is given during parameter assignment, while RDKit gives no warning.

**Possible solutions**

Both RDKit and OpenEye offer ways to change this cap. In the [OpenEye toolkit](https://github.com/openforcefield/openforcefield/blob/97d3602e6306d546c3a5d35283ae3141e6e6de81/openforcefield/utils/toolkits.py#L1415) the cap can be raised using the OESubSearch.SetMaxMatches method, and in the [RDKit toolkit](https://github.com/openforcefield/openforcefield/blob/97d3602e6306d546c3a5d35283ae3141e6e6de81/openforcefield/utils/toolkits.py#L2248) by passing a different maximum to `GetSubstructMatches`.

It would be good to expose an option for setting this value on `ToolkitWrapper` classes which implement a `find_smarts_matches` method, and possibly increase the default value for the cap.

**Comment by j-wags** [comment]
Thanks for the thorough write-up, @SimonBoothroyd. I think we should either remove the match limit or set it to some very high number. This should be very straightforward, so I'm tagging it as a "good first issue".

To close this issue, we should remove or raise the match limit, and add a test for both the OETH and RDKit backends where we can load and parameterize a >2000 atom polymer using library charges.
