### ISSUE TITLE
Versioning the SMIRNOFF specification

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#5]
cc: https://github.com/open-forcefield-group/smarty/issues/175 https://github.com/open-forcefield-group/smarty/issues/42

One of the original ideas of splitting off SMIRNOFF was that we could version the specification and synchronize the GitHub releases. Since we're combining several tools in one repo now, we can avoid needing exact version synchronization, but we will still want to add a version number attribute and call the current version something. We could start with 0.1.5, since that was the last version of smarty that SMIRNOFF was included in.

I think we currently have a float version tag (https://github.com/open-forcefield-group/smarty/issues/42#issuecomment-258300796), but I don't see this in the [SMIRNOFF spec](https://github.com/open-forcefield-group/openforcefield/blob/master/The-SMIRNOFF-force-field-format.md).

Instead of `x.y.z` for the spec, I think we are OK with `x.y`:
* `X`: update for major, API-breaking changes
* `Y`: update every time we add a new feature that doesn't break the API

where the `z` of `x.y.z` can be reserved for code bugfix updates.

**Comment by davidlmobley** [comment]
This sounds good to me. I never really did anything with the version tag in SMIRNOFF and certainly not enough that I felt it was nailed down enough to put it into the spec.

**Comment by davidlmobley** [comment]
One thing I am unclear on (which I thought I'd noted somewhere, but now can't find) is how exactly we handle versioning of the SMIRNOFF spec and coupling of this to the parser. Specifically, I know how to make sure that `openforcefield` uses a particular version number, and we can have a particular version number specified in SMIRNOFF XML files. But what do we do from there? Does the `forcefield` parser insist that provided XML files match its current version, or does it maintain backwards compatibility? And if backwards compatibility, how do we achieve that? 

This is not that important yet, as we haven't dramatically changed anything. But as soon as we start adding and using fancy virtual sites ( #41 ), etc., then this will become critical.

**Comment by jchodera** [comment]
Here's how I envision this would work:

Suppose release A.B.C of `openforcefield` adds support for SMIRNOFF version X.Y.Z. The `openforcefield` release should be guaranteed to be compatible with all earlier versions of SMIRNOFF as well. If someone has an installation of `openforcefield` that isn't recent enough to support `X.Y.Z`, it will complain that you need to upgrade to a more recent version, and people would generally install the latest version.

The only problem would be if we want to really *break* the format in a manner that would make backward-compatible support hard *and* we don't want to bundle the older parsing support with new releases of `openforcefield`. If we thought this was likely, we should split off SMIRNOFF support and have it move at least in same major version as SMIRNOFF, so that the tools version 2.x may not work with SMIRNOFF 1.x.

**Comment by davidlmobley** [comment]
That sounds like a good goal. Implementation-wise, how would you imagine achieving this? Will a given `openforcefield` install carry along with it a `forcefield` class for each prior version of the spec and switch to the appropriate one depending on the version it encounters?

**Comment by jchodera** [comment]
If we are careful to make sure the forcefield spec is backwards-compatible (where earlier SMIRNOFF versions are a strict subset of later SMIRNOFF versions), we can simply keep adding to the `ForceField` class to handle these new additions to the spec while also processing older versions. We would check the `version` attribute of the XML file to make sure it is <= the current version we can handle, throwing an exception if it is > than the version we know how to parse. This is how OpenMM handles its own XML format now.

If we decide to completely refactor things to handle a newer version of the spec that ditches backwards compatibility, we could check the version number and call the older version of the parser for older versions. That's ugly, but we hope to avoid this scenario.

**Comment by davidlmobley** [comment]
OK, that sounds reasonable to me and simpler than I was expecting.

**Comment by jchodera** [comment]
Closing this in favor of #249.
