### ISSUE TITLE
Include find rotatable bonds in OETKW and RDKTKW

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#500]
This is needed for the bespoke workflow.

**Comment by jthorton** [comment]
We might also want to identify some functional groups, these would not be targeted for refitting as they would be simple like methyl etc.

**Comment by jchodera** [comment]
Any suggestions for what the API should look like?

**Comment by jchodera** [comment]
> We might also want to identify some functional groups, these would not be targeted for refitting as they would be simple like methyl etc.

This is currently handled by @ChayaSt's code as a list of SMARTS patterns that can be used to filter out bonds that don't need to be driven, but is this something you envision being part of the `Molecule` API?

**Comment by j-wags** [comment]
Thanks for the tip @jchodera -- Posting a link to some of @ChayaSt's functional groups SMARTS for reference: 

https://github.com/openforcefield/fragmenter/blob/24bcd6ff89549dcd5129bb86dab97023cca99344/fragmenter/torsions.py#L58

https://github.com/openforcefield/fragmenter/blob/master/fragmenter/data/fgroup_smarts.yml

Josh and I are talking about this -- How about the following:

```
import openforcefield.FunctionalGroup as fg
rotatable_bonds = tookit_registry.find_rotatable_bonds(offmol, ignore_functional_groups=[fg.methyl, fg.peptide_bond])
print(rotatable_bonds)
```
> ( <offbond with atom1 index 2 and atom2 index 4>, <offbond with atom1 index 4 and atom2 index 6>, ...)
```
print([(bond.atom1_index, bond.atom2_index) for bond in rotatable_bonds])
```
> ((2, 4), (4, 6), ...)
```
# Running it again without ignoring any functional groups
rotatable_bonds = tookit_registry.find_rotatable_bonds(offmol)
print([(bond.atom1_index, bond.atom2_index) for bond in rotatable_bonds])
```
> ((2, 4), (2, 5), (4, 6), ...)

The `FunctionalGroup` class be defined as an enum as follows: 
```
from enum import Enum
class FunctionalGroup(Enum):
    methyl = '[*:1]-[#6X4H3:2]'
    peptide = '[*]-[#6X3:1](=[#8]):[#7H1X3:2]'
    terminal = '[*]~[*:1]-[X2H1,X3H2,X4H3:2]-[#1]'
print(FunctionalGroup.peptide.value)
```
> [*]-[#6X3:1](=[#8]):[#7H1X3:2]


## Pseudocode

The `find_rotatable_bonds` function could work as follows:

```
class Molecule: 
    def find_rotatable_bonds(self, ignore_functional_groups=None, toolkit_registry=None):
        rotatable_bonds = toolkit_registry.find_rotatable_bonds(self)
        ignore_functional_groups = [list of SMARTS to ignore]
        ignore_bonds = toolkit_registryfind_smarts_matches to find matches for the items in ignore_functional_groups
        Remove ignore_bonds from rotatable_bonds
        return rotatable_bonds
``` 
        
```

**Comment by jchodera** [comment]
Thanks! This is very helpful.

Why make it a static method of `Molecule`?
That is, why do you prefer
```python
bonds = Molecule.find_rotatable_bonds(molecule)
```
over
```python
bonds = molecule.find_rotatable_bonds()
```
or even 
```python
bonds = molecule.rotatable_bonds
```
?

I like the idea of a functional groups handler that could also have preprogrammed _sets_ of functional groups, but that seems to be more complicated than just an iterable set of SMARTS patterns for a first pass. We'd have to do a lot more API design for that, but could maybe start with also supporting a list of SMARTS patterns.

For the SMARTS patterns, what would the exclusion criteria be? Would we check every torsion incident to the central bond (might be 9 or more torsions) to see if any bond in that torsion is covered in the SMARTS match? What happens if some of them are covered but not others---is the bond still rotatable then? In short: *How will we use the SMARTS pattern to reject potentially rotatable bonds?*

**Comment by j-wags** [comment]
> Why make it a static method of Molecule?

Ah, I'd propose making it an instance method -- Apologies if that was unclear. So I'd advocate for your Option 2:
```
bonds = molecule.find_rotatable_bonds()
```
Options 3 and 4 would make it a property, which wouldn't let us pass in arguments like `toolkit_registry` or `ignore_functional_groups`. Though we could add something like Option 4 as a method of `Bond`, just accepting kwargs. 

> We'd have to do a lot more API design for that, but could maybe start with also supporting a list of SMARTS patterns

@jthorton, @trevorgokey, and I have been tossing around the idea of having a dev namespace inside OFFTK to host preliminary functionality while the API is discussed. We need the this functionality for the QCA submission workflow, so either we need to crunch in an API discussion ASAP, release a restricted `find_rotatable_bonds` function now that will scoop up terminal groups (and add kwargs later), or put these in a `dev` namespace, where the API has no guarantee of stability. I prefer the latter. What do you think?

> What happens if some of them are covered but not others---is the bond still rotatable then?

I'd argue "no" -- basically, if any "ignored" torsions include the central bond, then all torsions with that central bond are ignored.

**Comment by jchodera** [comment]
Instead of a dev namespace, what about just marking functions with experimental APIs with docstring warnings that the API is subject to change? That is much simpler to manage.

**Comment by jthorton** [comment]
> I'd argue "no" -- basically, if any "ignored" torsions include the central bond, then all torsions with that central bond are ignored.
 
I would agree with this!

Also, I quite like the idea of the bond class having an attribute to store this information as well like
`bond.is_rotatable`. This could easily be captured from the toolkit backend on the creation of the OFFMol and  would tell us if that bond is generally regarded as rotatable, then more specific collections of rotatable bonds can be grabbed through the suggested `molecule.find_rotatable_bonds(offmol)` method. 

> I like the idea of a functional groups handler that could also have preprogrammed sets of functional groups, but that seems to be more complicated than just an iterable set of SMARTS patterns for a first pass. We'd have to do a lot more API design for that, but could maybe start with also supporting a list of SMARTS patterns.

I would think we would want to accept both eventually? The list of predefined patterns helps users who want common groups to be ignored but in the bespoke workflow I could imagine users wanting to ignore rotating some other specific torsion type as they feel it is already well fit, or they already have specific parameters for this.

**Comment by jchodera** [comment]
> I'd argue "no" -- basically, if any "ignored" torsions include the central bond, then all torsions with that central bond are ignored.

OK, so methyl rotors would indeed have to specify the central bond, like in your example: `'[*:1]-[#6X4H3:2]'`. That means these are not really "functional groups" but instead "trivial rotors" or something. Same for the peptide bond(*) example. So let's be careful about naming conventions.

(*) We should really drive the peptide bond. It does not fully have double-bond character, and if we don't drive it, we end up just making up a large barrier height that proves to be the cause of downstream nightmares. For examples, for many many years, the AMBER force fields had:
```
X -C -N -X    4   10.00        180.0             2.         AA|check Wendy?&NMA
```
where someone (Wendy Cornell?) made up the barrier height of exactly 10.00 kcal/mol as being "big enough". Except it turns out that parallel tempering simulations can actually cross this barrier...

**Comment by jchodera** [comment]
> I would think we would want to accept both eventually? The list of predefined patterns helps users who want common groups to be ignored but in the bespoke workflow I could imagine users wanting to ignore rotating some other specific torsion type as they feel it is already well fit, or they already have specific parameters for this.

Yes, I agree! I was just arguing for a staged implementation so we can get something working soon while we design the API for the more complex predefined rotors and collections of rotors.

**Comment by j-wags** [comment]
> Instead of a dev namespace, what about just marking functions with experimental APIs with docstring warnings that the API is subject to change?

That sounds good to me. API stability adds a lot of friction to development right now -- On one hand, there are clear pain points in the current API, but I'm hesitant to change them since that hurts users with existing workflows. On the other hand, I have trouble developing new features because I get paranoid about the API needing changes later. 

Hopefully organizing thing on Confluence can help us make timelines, with concrete blocks for "1 week for designing the spec/API", which happens strictly before coding, so that API suggestions aren't coming up in PR reviews.

**Comment by jchodera** [comment]
> That sounds good to me. API stability adds a lot of friction to development right now -- On one hand, there are clear pain points in the current API, but I'm hesitant to change them since that hurts users with existing workflows. On the other hand, I have trouble developing new features because I get paranoid about the API needing changes later.

We shouldn't be afraid to mark an API point as deprecated (with warnings in docs and on use, to be removed in a future version) and introduce a newer, better API that we start using right away---especially at this early stage of the project. Once it becomes a hassle to maintain the old API, we remove it. Software much more mature than ours does this all the time, and we're still early enough in the project that the pipelines are not widely deployed. 

> Hopefully organizing thing on Confluence can help us make timelines, with concrete blocks for "1 week for designing the spec/API"

I'd like to not miss these API design discussions, so it would be great if some sort of "URGENT" email pops up to key stakeholders so we don't miss it between slack messages, github alerts, and confluence notifications.
