### ISSUE TITLE
[LINT] 'temporary_directory' duplicates 'tempfile.TemporaryDirectory'

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#503]
**Describe the bug**
The `utils.temporary_directory` duplicates the `tempfile.TemporaryDirectory` context manager without providing the same level of flexibility.

`utils.temporary_directory` should likely be removed in favour of `tempfile.TemporaryDirectory`.

**Comment by j-wags** [comment]
I agree with the proposal, and agree that this is a good first issue.
