### ISSUE TITLE
Migrate 'ambertools' Launching to 'subprocess'

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#504]
**Describe the bug**

The `AmberToolsToolkitWrapper` currently launches the `ambertools` utilities using `os.system` which does not capture the output of the utility (such as stdout, stderr), and often returns just a generic exception.

This should likely be migrated to call using `subprocess.Popen` which is a higher level function which is more informative and has greater flexibility.

E.g.

```
antechamber_process = subprocess.Popen(
    [
        "antechamber",
        "-i",
        sdf_file_path,
        "-fi",
        "sdf",
        "-o",
        processed_sdf_path,
        "-fo",
        "sdf",
        "-at",
        amber_type,
        "-rn",
        "MOL",
        "-an",
        "no",
        "-pf",
        "yes",
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
)

antechamber_output, antechamber_error = antechamber_process.communicate()
antechamber_exit_code = antechamber_process.returncode
```

Related to #447

**Comment by j-wags** [comment]
Thanks for the code snippet. I agree with the proposal, and the tagging as a good first issue. 

This issue should be closed when a PR 
* modifies the `AmberToolsToolkitWrapper` to run the CLI tools using `Popen`
* captures the output, printing the stdout using `print`, and the stderr in the `Exception` that is raised if `sqm` or `antechamber` fails

**Comment by dgasmith** [comment]
Oh yea, didn't even see this. I avoid recommend avoiding `Popen` so much boilerplate that isn't needed. We will be moving a lot of the QCEngine wrapper and harness tech to QCElemental. Would suggest migrating to this where possible.

**Comment by SimonBoothroyd** [comment]
I can't remember exactly but I thought @slochower mentioned at some point that amber tools sometimes returns a non-zero return code even if it ran successfully - @slochower have I made this up?

**Comment by j-wags** [comment]
I'm cranking through a diverse molecule set with the changes to see if we get any unexpected AT errors.

**Comment by j-wags** [comment]
I stopped the test after 200 diverse freesolv molecules went through conf gen + charge calc without an error. I think this is behaving correctly, but if there are pathological molecules that will trigger the behavior that @SimonBoothroyd mentioned, please post them here, @slochower :-)

**Comment by slochower** [comment]
I'm not sure off the top of my head about the behavior of `antechamber`, but as Simon said, sometimes (?) `tleap` will not return error code 0, even if it is successful.
