### ISSUE TITLE
OFFMol.to_rdkit loses aromaticity info

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#513]
**Describe the bug**
`Molecule.to_rdkit` loses track of atom aromaticity in the example below. This happens in the line https://github.com/openforcefield/openforcefield/blob/master/openforcefield/utils/toolkits.py#L2282
```
Chem.SanitizeMol(rdmol, Chem.SANITIZE_ALL ^ Chem.SANITIZE_ADJUSTHS ^ Chem.SANITIZE_SETAROMATICITY)
```
which messes with aromaticity even though we tell it not to.

**To Reproduce**
```
from openforcefield.topology import Molecule
smiles = "[H]c1c(c(c(c(c1OC2=C(C(=C(N3C2=C(C(=C3[H])C#N)[H])[H])F)[H])OC([H])([H])C([H])([H])N4C(=C(C(=O)N(C4=O)[H])[H])[H])[H])F)[H]"
mol = Molecule.from_smiles(smiles)

for atom in mol.atoms:
    print('OFF: ', atom.is_aromatic)
rdmol = mol.to_rdkit()
from rdkit import Chem

for rdatom in rdmol.GetAtoms():
    print('RDK: ', rdatom.GetIsAromatic())

```

> OFF:  False
> OFF:  True
> OFF:  True
> OFF:  True
> OFF:  True
> OFF:  True
> OFF:  True
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> OFF:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False
> RDK:  False

**Proposed Solution**
Add 
```
        if aromaticity_model == 'OEAroModel_MDL':
            Chem.SetAromaticity(rdmol, Chem.AromaticityModel.AROMATICITY_MDL)
        else:
            raise ValueError(f"Aromaticity model {aromaticity_model} not recognized")
``` 
to here: https://github.com/openforcefield/openforcefield/blob/master/openforcefield/utils/toolkits.py#L2282

**Steps to close Issue**
- [x] Code change above
- [x] Add this as a test case in `test_toolkits` for `RDKitToolkitWrapper`

**Comment by jchodera** [comment]
@j-wags : Any idea why our round-trip tests didn't catch this?
