### ISSUE TITLE
Molecule.from_iupac Returns Empty Molecule on Failure

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#514]
**Describe the bug**
The `Molecule.from_iupac` function returns an empty molecule when `oeiupac.OEParseIUPACName(oemol, iupac_name)` fails rather than raising an exception.

**To Reproduce**
```
from openforcefield.topology import Molecule
assert len(Molecule.from_iupac(".BETA.-PINENE").atoms) > 0
```

**Output**
```
Warning: Failed to parse name: .BETA.-PINENE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

**Comment by jchodera** [comment]
Good catch!

What kind of exception should we return? A [`ValueError`](https://docs.python.org/3/library/exceptions.html#ValueError)?

**Comment by SimonBoothroyd** [comment]
I wonder if it would be good to start moving towards more custom exceptions for public API points. Perhaps something like:

```
class MoleculeParseError(Exception):
    """An exception raised when a cheminformatics toolkit
    is unable to parse a molecule from a particular source.
    """

    def __init__(self, message, toolkit_registry):
        """
        Parameters
        ----------
        toolkit_registry: ToolkitRegistry
            The registry which attempted to parse the molecule
            source.
        """

        super(MoleculeParseError, self).__init__(message)
        self.toolkit_registry = toolkit_registry
```

**Comment by j-wags** [comment]
Yes, we should move toward custom exceptions -- It's not standard practice
to build off of Python built-in exceptions. At some point we should define
a logical OFFTK exception hierarchy and then do a refactor so we only throw
those.
