### ISSUE TITLE
Remove requirement for unique atom names in reference molecules

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#52]
Currently, `generateTopology_from_oemol` is used to turn reference molecules into Topology objects for matching against the provided OpenMM `Topology` when applying `createSystem`, and this builds a topology using atom names to create bonds. This results in a requirement where the reference `OEMol` objects must have unique atom names. We should revise how this is handled to fix.

Ultimately, I think we want to replace this method of generating topologies with the `oemol_to_openmmTop` in https://github.com/oess/oeommtools/blob/master/oeommtools/utils.py . However, I would have to check whether that will fix this specific issue.

**Comment by davidlmobley** [comment]
(A use case to reproduce the problem here: If component OEMols are generated from SMILES and no atom names are assigned (e.g. `OETriposAtomNames`) then force field assignment will presently fail.)

**Comment by davidlmobley** [comment]
@j-wags I believe this can be closed as this requirement should have been removed by the big `Topology` revamp? (0.2)?

**Comment by j-wags** [comment]
Yes, I don't think this should be an issue any more.
