### ISSUE TITLE
Molecule.from_qcschema() should ALWAYS return a molecule with the tagged smiles atom ordering

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#525]
This came up in our QCFractal meeting today: @ChayaSt and I are strongly against having `Molecule.from_qcschema()` return a Molecule object with an incorrect atom ordering by default. 

If the cmiles block is present, the atom order of the generated molecule _must_ match the tagged SMILES. The entire point of CMILES is to provide this tagged canonical ordering for this purpose---99.9% of our use cases require the molecule be constructed in the correct order.

If there are use cases for not doing this, let's list them in this issue and find the best way to accommodate them, but they will be minor use cases.

**Comment by j-wags** [comment]
Lucky for us, I'm working on this right now and I realized I misspoke -- `Molecule.from_qcschema` leverages `Molecule.from_mapped_smiles`, which DOES produce a molecule in map order.

https://github.com/openforcefield/openforcefield/blob/5baae2983a181582c0f3715376f4bc0a6bcbd079/openforcefield/topology/molecule.py#L3567-L3615

**Comment by jchodera** [comment]
Huzzah! It's like you time traveled into the past and fixed it!

**Comment by j-wags** [comment]
Josh gets all the credit :-)
