### ISSUE TITLE
Enumerating states.

### ISSUE THREAD

**Issue by jthorton** [openforcefield/openforcefield#526]
**Is your feature request related to a problem? Please describe.**
During the QCArchive submission framework, we plan on enumerating several states and it would be nice to have API points that can easily allow users to expand states such as tautomers, stereoisomers and protonation states. 

**Describe the solution you'd like**
I am not too sure on what would be best here either one general state enumerator that takes an argument corresponding to the sate or a separate API point for each state we require. 
so 
```python
# options would be stereoisomers, tautomers, protonation?
molecules = molecule.enumerate_state(state='stereoisomers')
```

or 

```python
molecules = molecule.enumerate_stereoisomers()
```

After a quick look into this, I have found that RDKit can do 
- [stereoisomers](https://www.rdkit.org/docs/source/rdkit.Chem.EnumerateStereoisomers.html) 
- [tautomers](https://rdkit.blogspot.com/2020/01/trying-out-new-tautomer.html) are coming

I did not find any info for protonation though someone else may know?

Openeye I believe can already do this and tautomer and stereoisomer expansion has already been done in fragmenter 
- [steroisomers and tautomers](https://github.com/openforcefield/fragmenter/blob/master/fragmenter/states.py) fragmenter link
- [protonation](https://docs.eyesopen.com/toolkits/python/quacpactk/OEProtonFunctions/OEGetReasonableProtomers.html?highlight=oegetreasonabletautomers) openeye docs

tagging @jchodera and @ChayaSt

**Comment by jchodera** [comment]
Would we want one API call to do this?

If so, if we specify a combination of states, what order is the enumeration carried out in?

**Comment by jthorton** [comment]
My thought was that only one state could be enumerated per API call, as if the user-supplied multiple it might not be clear in the return where the divide between the states is even if we did it in the order the user-supplied.

**Comment by jchodera** [comment]
In looking through the `Molecule` API, I realize we that we internally store information about stereochemistry for stereoatoms or bonds, but we don’t note which atoms/bonds are stereocenters/bonds but without defined stereochemistry.

So even if we load a molecule by allowing undefined stereochemistry, we provide no methods for checking whether the molecule has defined stereochemistry, even before we talk about iterating over stereocenters/bonds.

**Comment by jthorton** [comment]
Yes, this could be potentially added in during this PR but is that needed? As far as I can tell the back end toolkits will enumerate all stereocenters/bonds regardless of if they are defined or not provided we use the right keywords giving users the ability to have functionality like this:

```python
# this is the default and will enumerate all stereocenters/bonds
molecules = mol.enumerate_stereoisomers(undefined_only=False, maxisomers=20, unique=True, try_embedding=True)
```
so I don't think we would not need to tag undefined centres/bonds for this purpose, as targeting all undefined centres/bonds could be done via:

```python
molecules = mol.enumerate_stereoisomers(undefined_only=True)
```

but maybe this undefined stereo tagging would be helpful for the sanity checking functionality we talked about adding in #516.

**Comment by jthorton** [comment]
I was having a play with state enumeration to see if I can get stereoisomers to work and hit a snag, @jchodera  may be right that we should store information about chiral centres and stereo bonds who are undefined as converting these molecules back to RDKit for enumeration causes them to be missed. To get around this without saving the info in the offmol we can  just call these functions to flag them as possibles first 
```python
Chem.AssignStereochemistry(rdmol, force=True, flagPossibleStereoCenters=True)
Chem.FindPotentialStereoBonds(rdmol)
```
but it might be better to have some equivalent of `Chem.rdchem.BondStereo.STEREOANY` to store on the bond and a similar for chiral atoms?

**Comment by davidlmobley** [comment]
It sounds like if RDKit is missing enumeration of reasonable protonation states, we should advertise this prominently as an area where there are gaps in open source cheminformatics toolkits and see if anyone wants to contribute in this area. This isn't something where we should try and fix it ourselves.

**Comment by jthorton** [comment]
As far as I can see I can't find an automated way to do it in RDKit so I think it would be good to advertise this. For now, I'll add stereoisomer and tautomer support for both toolkits till we have his fixed.

**Comment by davidlmobley** [comment]
OK. Do you have ideas on the best way to advertise needs in this area?

Maybe create an example of what OpenEye can do/what we're relying on and then post it into a separate issue, and I/OpenFF can tweet about it?
