### ISSUE TITLE
Implement the `ParameterHandler.get_parameter` function

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#541]
**Describe the solution you'd like**
It would be great to have the `ParameterHandler.get_parameter(...)` function implemented:

https://github.com/openforcefield/openforcefield/blob/0e5ff41b72ce4dcb4c0e9cd431faa28c7b7cd1ab/openforcefield/typing/engines/smirnoff/parameters.py#L1421-L1436

As general note - instead of just calling `pass` it would be great instead to raise a `NotImplementedError` for yet to be implemented functions / features.

**Comment by j-wags** [comment]
Oh WOW that is bad. thanks for finding this. I'm going to put the `NotImplementedError` in immediately. There's no reason this should pass.
