### ISSUE TITLE
Cannot load topology

### ISSUE THREAD

**Issue by daveminh** [openforcefield/openforcefield#546]
**Describe the bug**
I cannot load the openforcefield.topology module

**Output**
![image](https://user-images.githubusercontent.com/6304824/77127692-b9f0ba80-6a0a-11ea-9a23-a6334fbd3217.png)

**Computing environment (please complete the following information):**
 - Operating system
Mac OS X 10.14.6

# packages in environment at /miniconda2/envs/openmm:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
ambertools                18.0                          0    omnia
appnope                   0.1.0                 py37_1000    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                    openblas
bleach                    3.1.3              pyh8c360ce_0    conda-forge
blosc                     1.16.3               hd9629dc_0
bzip2                     1.0.8                h01d97ff_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cffi                      1.14.0           py37h356ff06_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
cryptography              2.8              py37he655712_2    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.13          py37h6de7cb9_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
exampleplugin             1.0                      pypi_0    pypi
expat                     2.2.6                h0a44026_0
fftw3f                    3.3.4                         2    omnia
freetype                  2.10.1               h8da9a1a_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.58.3          py37h577aef8_1002    conda-forge
gridplugin                1.0                      pypi_0    pypi
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.9                        py_1    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.5.0            py37hc8dfbb8_1    conda-forge
importlib_metadata        1.5.0                         1    conda-forge
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.12.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.16.0                   py37_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.0.0                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
kiwisolver                1.1.0            py37ha1b3eb9_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcxx                    9.0.0                h89e68fa_1    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                hd44dcd8_1    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libxml2                   2.9.9                hf6e021a_1
libxslt                   1.1.33               h33a18ac_0
llvm-openmp               9.0.0                h40edb58_0    conda-forge
lxml                      4.5.0            py37hef8c89e_0
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
markupsafe                1.1.1            py37h9bfed18_1    conda-forge
matplotlib                3.1.3                    py37_0
matplotlib-base           3.1.3            py37h9aa3819_0
mdtraj                    1.9.3            py37h3e38534_1    conda-forge
mistune                   0.8.4           py37h0b31af3_1000    conda-forge
mock                      3.0.5            py37hc8dfbb8_1    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
numexpr                   2.7.1            py37h9ff8ad3_0
numpy                     1.17.2           py37h6b0580a_0    conda-forge
numpydoc                  0.9.2                      py_0    conda-forge
openforcefield            0.0.4                    py37_1    omnia
openforcefields           1.1.0                    py37_0    omnia
openmm                    7.4.0           py37_cuda101_rc_1    omnia
openmoltools              0.8.5                    py37_0    omnia
openssl                   1.1.1e               h0b31af3_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    0.25.3           py37h4f17bb1_0    conda-forge
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parmed                    3.2.0            py37h4a8c4bd_2    conda-forge
parso                     0.6.1                      py_0    conda-forge
pcre                      8.43                 h0a44026_0
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.3.1                   py37_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.3                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_4    conda-forge
pyrsistent                0.15.7           py37h9bfed18_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytables                  3.6.1            py37h5bccee9_0
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyzmq                     18.1.1           py37h4bf09a9_0    conda-forge
qt                        5.9.7                h93ee506_2    conda-forge
qtconsole                 4.7.1                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
scipy                     1.2.1            py37hbd7caa9_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.4.0                   py37_0    conda-forge
sip                       4.19.8           py37h0a44026_0
six                       1.14.0                   py37_0    conda-forge
snappy                    1.1.7             h4a8c4bd_1003    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    2.4.4                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.9             h2573ce8_1003    conda-forge
tornado                   6.0.4            py37h9bfed18_1    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
urllib3                   1.25.7           py37hc8dfbb8_1    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.3.7                h5bba6e5_0

**Comment by j-wags** [comment]
Hi @daveminh,

In the above conda environment, I'm seeing an old OpenFF toolkit version:
```
 openforcefield 0.0.4 py37_1 omnia
```

We're up to toolkit version 0.6.0 -- Could you try reinstalling into a new conda environment and seeing if that resolves the issue?

```
conda create -n openff2 -c conda-forge -c omnia openforcefield
conda activate openff2
```

**Comment by daveminh** [comment]
It seems like work after I did "conda update --all". I don't know why it loaded an old version since I just did the conda install of the toolkit today.

**Comment by daveminh** [comment]
Thanks for looking into it so quickly!

**Comment by j-wags** [comment]
Thanks for trying out the OFF toolkit. Glad updating resolved it for you :-)
