### ISSUE TITLE
JSON serialization of Molecule broken

### ISSUE THREAD

**Issue by daveminh** [openforcefield/openforcefield#547]
**Describe the bug**
JSON serialization of Molecule broken

**To Reproduce**
Steps to reproduce the behavior. A minimal reproducing set of python commands is ideal.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/6304824/77211596-abb1a580-6ac1-11ea-840d-3bea21874724.png">

**Computing environment (please complete the following information):**
# packages in environment at /miniconda2/envs/openmm:
#
# Name                    Version                   Build  Channel
amberlite                 16.0                     pypi_0    pypi
ambertools                17.0                     pypi_0    pypi
appnope                   0.1.0           py37hc8dfbb8_1001    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.3              pyh8c360ce_0    conda-forge
boost                     1.72.0           py37hbf1eeb5_0    conda-forge
boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
bson                      0.5.9                      py_0    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cffi                      1.14.0           py37h356ff06_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
codecov                   2.0.15                     py_1    conda-forge
coverage                  5.0.4            py37h9bfed18_0    conda-forge
cryptography              2.8              py37he655712_2    conda-forge
curl                      7.68.0               h8754def_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.15          py37h570ac47_1    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
exampleplugin             1.0                      pypi_0    pypi
expat                     2.2.9                h4a8c4bd_2    conda-forge
fftw                      3.3.8           nompi_h44ae4c8_1110    conda-forge
fftw3f                    3.3.4                         2    omnia
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.1               h8da9a1a_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                h0b31af3_2    conda-forge
glib                      2.58.3          py37h7c187be_1003    conda-forge
gridplugin                1.0                      pypi_0    pypi
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.5.0            py37hc8dfbb8_1    conda-forge
importlib_metadata        1.5.0                         1    conda-forge
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.13.0           py37h43977f1_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.16.0           py37hc8dfbb8_1    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.0.0                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
kiwisolver                1.1.0            py37ha1cc60f_1    conda-forge
krb5                      1.16.4               h1752a42_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hf57f61e_0    conda-forge
libcurl                   7.68.0               h709d2b2_0    conda-forge
libcxx                    9.0.1                         1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm9                  9.0.1                ha1b3eb9_0    conda-forge
libnetcdf                 4.7.3           nompi_hda4e5f1_101    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libpq                     12.2                 h554dc5a_0    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.1.0                h2ae36a8_5    conda-forge
libwebp                   1.1.0                hd3bf737_2    conda-forge
libwebp-base              1.1.0                         2    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               9.0.1                h28b9765_2    conda-forge
lxml                      4.5.0            py37heb1707f_1    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py37h9bfed18_1    conda-forge
matplotlib-base           3.2.1            py37hddda452_0    conda-forge
mistune                   0.8.4           py37h0b31af3_1000    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
more-itertools            8.2.0                      py_0    conda-forge
msgpack-python            1.0.0            py37ha1cc60f_1    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf-fortran            4.5.2           nompi_h16a226e_103    conda-forge
networkx                  2.4                        py_1    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numpy                     1.18.1           py37hde6bac1_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openeye-toolkits          2019.10.2                py37_0    openeye
openforcefield            0.6.0                    py37_1    omnia
openforcefields           1.1.0                    py37_0    omnia
openmm                    7.4.1           py37_cuda101_rc_1    omnia
openmmforcefields         0.7.1                    py37_2    omnia
openssl                   1.1.1e               h0b31af3_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.3            py37h94625e5_0    conda-forge
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parmed                    3.2.0                    pypi_0    pypi
parso                     0.6.2                      py_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
pdb4amber                 1.7.dev0                 pypi_0    pypi
perl                      5.26.2            haec8ef5_1006    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.0.0            py37hfd78ece_1    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt-toolkit            3.0.4                      py_0    conda-forge
prompt_toolkit            3.0.4                         0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pycairo                   1.19.1           py37h4e38901_2    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.12.3           py37he22c54c_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py37h9bfed18_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytest                    5.4.1            py37hc8dfbb8_0    conda-forge
pytest-cov                2.8.1                      py_0    conda-forge
python                    3.7.6           hfa4aa89_4_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytraj                    2.0.5                    pypi_0    pypi
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3.1            py37h9bfed18_0    conda-forge
pyzmq                     19.0.0           py37haec44b1_1    conda-forge
qt                        5.12.5               h514805e_3    conda-forge
qtconsole                 4.7.1                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rdkit                     2019.09.3        py37h56de688_1    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
sander                    16.0                     pypi_0    pypi
scipy                     1.4.1            py37h82752d6_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.0.0           py37hc8dfbb8_2    conda-forge
six                       1.14.0                     py_1    conda-forge
smirnoff99frosst          1.1.0                    py37_1    omnia
sqlite                    3.30.1               h93121df_0    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tinydb                    3.15.2                     py_0    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toml                      0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h9bfed18_1    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
urllib3                   1.25.7           py37hc8dfbb8_1    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.2.2                h0b31af3_1    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                hed8d7c8_2    conda-forge

**Comment by daveminh** [comment]
Actually I was using it wrong but it still is broken...

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/6304824/77211752-2aa6de00-6ac2-11ea-9ec0-d0458f40f796.png">

**Comment by j-wags** [comment]
Ahh, interesting. Thanks for reporting this! The coordinates are serializing to bytes, which JSON can't handle. Reproducing example below:
```
from openforcefield.topology import Molecule
smiles = 'CCO'
offmol = Molecule.from_smiles(smiles)
print(offmol.to_smiles())
offmol.generate_conformers()
offmol.to_json()
```
> TypeError: Object of type bytes is not JSON serializable

This is indeed a bug!

In the interim, you can get a serializable representation of an offmol using `to_bson` instead of `to_json`:
```
from openforcefield.topology import Molecule
smiles = 'CCO'
offmol = Molecule.from_smiles(smiles)
print(offmol.to_smiles())
offmol.generate_conformers()
bson_data = offmol.to_bson()
offmol2 = Molecule.from_bson(bson_data)
assert offmol == offmol2
```

**Comment by jthorton** [comment]
@j-wags @dotsdl @mattwthompson I think we should we get this added to the next milestone.

**Comment by j-wags** [comment]
Let's have @mattwthompson report on this once he takes a look at re-implementing tests. We can decide whether to guarantee this on the 0.7.0 roadmap at Monday's sprint planning meeting.

**Comment by jchodera** [comment]
@dgasmith may have some useful suggestions for how we could improve the JSON schema to better match with [QMSchema](https://github.com/MolSSI/QCSchema) and its MMSchema.

**Comment by jthorton** [comment]
Just moving the conversation about fixing the JSON problem from PR #569 to here in case someone wants to give this a go. Also elemental has a similar problem for its Molecule model but gets around it using this custom json encoder (https://github.com/MolSSI/QCElemental/blob/d11c14135f67d635f80ca8e63ccabf608cc71d31/qcelemental/models/basemodels.py#L17) which to calls `geometry.flatten().tolist()`

> I took my cues for the array serialization form here: https://stackoverflow.com/questions/30698004/how-can-i-serialize-a-numpy-array-while-preserving-matrix-dimensions#30699208

> I'm not sure that tolist is exactly what we want here -- I think there's some lossiness when converting between numpy objects and python builtins.

> On the other hand, trying to "faithfully" serialize and deserialize a numpy array brings us through this annoying bytes-based intermediate, which doesn't actually serialize in some formats, so... any solution that actually serializes is good by me.

> Honestly, serialized = pickle.dumps(numpy_array, protocol=0) (from the link above) might gve us the string-serializable representation we want.

> The important places to modify for this would be in openforcefield/utils/utils.py's {de,}serialize_numpy functions, and FrozenMolecule._initialize_from_dict
