### ISSUE TITLE
Set up openforcefield.org website

### ISSUE THREAD

**Issue by bannanc** [openforcefield/openforcefield#55]
@mrshirts and I were talking yesterday and realized we don't have a place to send people that has the more general information about the OFF Group. The READMEs on the individual repositories tell you what is there and how to use it (or find more detailed examples). It would be nice to have a more general Wiki/website to link people not yet familiar with the project. 

Michael asked me to write and issue and this seemed the most logical place to put it, but ideally I would think this should be independent on any of the repos.

**Comment by jchodera** [comment]
I think it would be great to have a website for the OFF Group, but I just haven't had time to set one up. I've already registered the domain name `openforcefield.org` that we can use for this purpose.

We have a few options:
* Quickly put together a good-looking website with Squarespace. Would look nice, but have to use GUI for editing content.
* Use a static site rendering scheme supported by GitHub like [Jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/). Would look OK (several [templates](http://jekyllthemes.org/) are available) but would be a great way to easily add code snippets, blog posts, etc. from multiple authors simply by making PRs to a github repo.
* A wiki is easier to collaboratively edit, but doesn't look great and may be hard to add testing infrastructure to make sure online examples actually work, etc.

**Comment by davidlmobley** [comment]
For the record, we discussed this on Slack and the other issue is that we want something under version control, so NOT a GitHub wiki. Markdown could work, or GitHub pages, or similar. Here's some more info from John:

> I responded to the GitHub issue! I also support the Jekyll GitHub pages static site in a separate repo called openforcefield.org or openforcefield-org
>
> There are a bunch of Jekyll themes you can choose from too:
http://jekyllthemes.org

**Comment by jchodera** [comment]
> Markdown could work, or GitHub pages, or similar. Here's some more info from John:

We can use Jekyll deployed via GitHub Pages to accomplish all these goals!
* Web pages are written in Markdown
* Pages are under github revision control
* Automatically deployed to the web
* Can have openforcefield.org point to GitHub Pages
* Can easily include code examples

**Comment by davidlmobley** [comment]
@jchodera - do you have a good example of this?

We're using this for LiveCoMS journal's supporting pages, but it's in the very early stages and I don't understand how to make it look nice yet, so it'd be good to have a better example. (https://livecomsjournal.github.io/ and https://github.com/livecomsjournal/livecomsjournal.github.io)

**Comment by jchodera** [comment]
Here are some nice-looking Jekyll themes we might be able to use:
* [Forty](http://jekyllthemes.org/themes/Forty/): [demo](https://andrewbanchich.gitlab.io/forty-jekyll-theme/)
* [Airspace](http://jekyllthemes.org/themes/airspace/): [demo](https://luminousrubyist.github.io/airspace-jekyll/)
* [Jekyll-Mono](http://jekyllthemes.org/themes/Jekyll-Mono/): [demo](http://akshayagarwal007.github.io/Jekyll-Mono/)
* [Slender](http://jekyllthemes.org/themes/slender/): [demo](http://nikrich.github.io/jekyll-slender-template/#)
* [{ Personal }](http://jekyllthemes.org/themes/personal/): [demo](https://le4ker.github.io/personal-jekyll-theme/)
* [blueface](http://jekyllthemes.org/themes/blueface/): [demo](http://thien.io/blueface/) 
* [Spectral](http://jekyllthemes.org/themes/spectral/): [demo](http://arkadianriver.github.io/spectral/)
* [creative theme](http://jekyllthemes.org/themes/creative-theme/): [demo](https://volny.github.io/creative-theme-jekyll/)
* [Twenty](http://jekyllthemes.org/themes/twenty/): [demo](https://html5up.net/twenty)

**Comment by davidlmobley** [comment]
I think @bmanubay is going to be working on this once Pascal (in the Shirts group) is back from vacation and can give some help.

**Comment by bmanubay** [comment]
Indeed, that is the case! I'm getting familiar with how everything is set up now!

**Comment by jchodera** [comment]
@bmanubay : Instead of something bloggy like blueface, are you sure you don't want to go with something more like [Twenty](http://jekyllthemes.org/themes/twenty/): [demo](https://html5up.net/twenty)?

**Comment by bmanubay** [comment]
@jchodera : I'm open to doing whatever you all want. I just chose a theme from your list that I liked. Please scrutinize and I'll change haha
