### ISSUE TITLE
Visualization of OpenFF Molecules

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield#555]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just the inconvenience of not being able to visualize molecules without converting to something external

**Describe the solution you'd like**
I would like there to be a simple way to visualize an OpenFF molecule object while fiddling around in a notebook. I don't think this is a critical feature, but it would be a nice feature for developers (i.e. diagnosing why half of a torsion drive failed) and users (think docs, examples, future workshops, etc.) alike.

**Describe alternatives you've considered**
There's surely some way to convert to NGLView or another library with viz support, but I would like to avoid 2-3 conversions and just do a `mol.visualize()` call similar to the [Compound.visualize()](https://github.com/mosdef-hub/mbuild/blob/70ee2db5c017aa8dc7737214ea5294fd4ec2d049/mbuild/compound.py#L1245) method in mBuild. It is effectively a thin wrapper around NGLView/py3Dmol

**Additional context**
the above visualization within MoSDeF used NGLView for years but it can be flaky and [isn't so focused](https://github.com/mosdef-hub/mbuild/issues/529#issuecomment-488539719) on peeking at at a molecular snapshot, so @ahy3nz refactored it to have a switchable-ish backend and added support for py3Dmol. https://github.com/mosdef-hub/mbuild/pull/530 I think this is an approach we could mimic.

Note that you can fire a molecule off to RDKit and get a 2-D representation, but I would really like to also be able to see a 3-D representation. 

![image](https://user-images.githubusercontent.com/7935382/77966443-a960ff80-72a8-11ea-84d8-ce22f7f28ee2.png)

This points back to some discussion about what is necessarily encoded in this object, i.e. if this visualization should fail in the absence of conformers or fall back to some 2-D representation. Please correct me if I missed something, but I believe coordinates are only stored if there is a conformer stored?

This also may be worth discussing in the context of other objects, but Molecule is the easy starting point.

**Comment by jaimergp** [comment]
+1 on a switchable 3D visualization backend that falls back to 2D representation if no conformers are available at that point.

**Comment by jthorton** [comment]
This would great if we had something that came with the toolkit for now if you are on master and have qcelemental installed you can use `mol.to_qcschema()` if your molecule has a conformer.
