### ISSUE TITLE
Test round-trip serialization 

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield#559]
In order to avoid issues like #547 popping up, we should take a closer look at our serialization and, in particular, implement round-trips from our data structures to various formats, i.e.

https://github.com/openforcefield/openforcefield/blob/af7c2f862c42ab486a3bf1ec90d36920862faba3/openforcefield/tests/test_molecule.py#L258-L259

Counter-point: How much work would it be to make each `to_dict()` method adhere to the various formats compared to refactoring everything to be built on top of [pydantic](https://pydantic-docs.helpmanual.io/)? I don't have a good feel for how much work each of these would take, so it is hard for me to estimate. What I do know is that 
* we don't want bugs like this 
* a later refactor to pydantic or something similar seems likely, if not inevitable

So I'm not sure how to prioritize this at the moment - @j-wags @dotsdl @jthorton and others what do you think?

Related #531 and probably others

**Comment by dotsdl** [comment]
I don't have experience with pydantic beyond work on QCEngine, and though it's a bit painful it does provide some nice runtime guardrails, which can be important for core code paths. Let's continue the [pydantic discussion here](https://github.com/openforcefield/openforcefield/issues/138).

Even with pydantic, we still want tests of these serialization round trips, as you noted. I think these should go [right where you pointed out](https://github.com/openforcefield/openforcefield/blob/af7c2f862c42ab486a3bf1ec90d36920862faba3/openforcefield/tests/test_molecule.py#L258-L259), even with the #531 refactor. Do you want to take this on, or would you like me to?

**Comment by mattwthompson** [comment]
I would like to take the first stab and delegate from there. I probably won't be able to do it alone

**Comment by j-wags** [comment]
> So I'm not sure how to prioritize this at the moment

Getting the tests back online and offering some working functionality to serialize conformers to JSON is pretty high priority, and we can rank exactly how high at Monday's sprint planning. But it would be great to discuss the options we have on that front if you gain some insight by looking into this sooner. 

Implementing a pydantic object model will give us JSON and more, but require significantly more effort, and be a brittle design. So I agree we should consider it a separate, lower-urgency topic.
