### ISSUE TITLE
Implement proper torsion parameter interpolation based on partial bond order

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#572]
**Is your feature request related to a problem? Please describe.**
@ChayaSt's work showed that we may be able to produce higher-quality proper torsion parameters by taking into account the "partial bond order" of the torsion's central bond. We now have the machinery to compute AM1-Wiberg partial bond orders for entire molecules using either OpenEyeToolkitWrapper's or AmberToolsToolkitWrapper's [`assign_wiberg_bond_orders`](https://github.com/openforcefield/openforcefield/blob/master/openforcefield/utils/toolkits.py#L1512) methods. The thought is that, if some simple electron population analysis shows that a bond order is 1.53, maybe torsions about that bond can be described well by interpolating to 53% of the way between the single and double bond `k` values. 

A similar area of the spec has been proposed for [interpolation of parameters in the `Bonds` section](https://open-forcefield-toolkit.readthedocs.io/en/latest/smirnoff.html#fractional-bond-orders-experimental). These keywords are currently unsupported, but provide a template we can follow for torsion interpolation. If needed, we could implement Bond interpolation as a technical exercise, but that functionality is far lower-value than proper torsion interpolation.

**Describe the solution you'd like**

The extension of the [`ProperTorsions` tag](https://open-forcefield-toolkit.readthedocs.io/en/latest/smirnoff.html#propertorsions) in the SMIRNOFF XML spec, adding two new supported `ProperTorsions` header attributes:
* `fractional_bondorder_method`, with default value `AM1-Wiberg`
* `fractional_bondorder_interpolation`, with default value `linear`

The extension of the `ProperTorsion` tag in the SMIRNOFF XML spec to support EITHER 
* (currently supported) a set of non-interpolation-based torsion parameters, with attributes (for nonzero, consecutive integer values of X):
    * `kX` (required)
    * `phaseX` (required)
    * `periodicityX` (required)
    * `idivfX` (optional)
* (to be added) a set of a set of interpolation-based torsion parameters, with attributes (for nonzero, consecutive integer values of X and nonzero, consecutive integer bond orders B):
    * `kX_bondorderB` (required)
    * `phaseX` (required)
    * `periodicityX` (required)
    * `idivfX` (optional)

Note: I have no strong leaning as to whether, for a single parameter, `kX_bondorderB` should support a different range of `B` values for different `X`s. We can let ease of implementation guide this.

Note: I have no strong leaning as to whether B values should be required to be integer, however it's quite clear that this will make implementation much easier, so I think it's the way to go for our first attempt.

Note: We may consider what to do if a bond order falls outside the range of `B` values. We could solve this by adding an `extrapolate` attribute to the `ProperTorsions` tag, which could default to `False` (in which case, a bond order of 0.91 would get the k values from `kX_bondorder1`), but the FF could set it to `True` (in which case, a bond order of 0.91 would be linearly extrapolated from the `kX_bondorder1` and `kX_bondorder2` values)

**Implementation details**

We will want to add a keyword argument to `ForceField.create_openmm_system` called `partial_bond_orders_from_molecules=None`, but which could be set to `[iter of OFFMol]` (similar in implementation to the existing `charge_from_molecules` keyword argument), which lets users override our automatically-generated partial bond orders if they wish.

In [`ProperTorsionHandler.create_force`](https://github.com/openforcefield/openforcefield/blob/5e6b6dd52980a5e9a0423589c2a6370420e03694/openforcefield/typing/engines/smirnoff/parameters.py#L2118), adding logic to run `assign_fractional_bond_orders` _only if necessary,_ since a molecule might not be assigned any fractional bond order-dependent parameters, or the user may have specified `partial_bond_orders_from_molecules`, and we wouldn't want to waste time computing them in that case. 

In the class definition for [`ProperTorsionHandler.ProperTorsionType`](https://github.com/openforcefield/openforcefield/blob/5e6b6dd52980a5e9a0423589c2a6370420e03694/openforcefield/typing/engines/smirnoff/parameters.py#L2068), we'll need to either:
* define a new subclass of `ParameterAttribute`, like `DoubleIndexedParameterAttribute`. 
* somehow change or subclass `IndexedParameterAttribute` to be able to "wrap" and add a SECOND indexing system to an existing `IndexedParameterAttribute`.

I'm happy to discuss further details or consider changes to this specification. Since this will be our first version of support for torsion interpolation, we don't have any existing behavior to maintain!

**Comment by dotsdl** [comment]
Thank you for this excellent write-up @j-wags! 

I have reviewed it and believe I have enough information to proceed. I will start by putting together a parameter section in the SMIRNOFF spec for this approach, drawing largely from your description here. 

This exercise will translate directly into structuring the implementation, for which you have already noted some key points to consider.

**Comment by dotsdl** [comment]
Do we have a good example of a torsion that we want to model this way? One that can have a few different bond orders for the central bond in the wild?

**Comment by j-wags** [comment]
Yes -- Check out this test based on an interesting molecule that @ChayaSt researched:
https://github.com/openforcefield/openforcefield/blob/master/openforcefield/tests/test_toolkits.py#L565-L624

You can see the structure here: https://pubchem.ncbi.nlm.nih.gov/compound/20742535

Basically, the electronic character of the central bond changes a lot depending on whether the oxygen is protonated. I'm not sure what reasonable torsion barriers for that molecule would be, but it could be a good test case for having the same SMARTS match the central bond, even though the electronic character is really different. 

Also, it's worth mentioning that, during implementation, we don't really need to be particularly accurate with the `k` values -- In fact, using simple dummy values, and hard-coding fractional bond orders on the molecule, will probably be the best way to implement tests for this functionality.

**Comment by dotsdl** [comment]
@j-wags is the test you pointed out featuring the same molecule as on pubchem? The test appears to feature toluene, which has no proper torsion, while the link is for 4-Pyridin-4-ylphenolate. I may be missing something here.

I'll proceed with building my example case around 4-Pyridin-4-ylphenolate. I may need help constructing the proper SMIRKS for matching these.

**Comment by j-wags** [comment]
Apologies for providing the wrong link to `test_toolkits`. I've updated the comment above.

**Comment by dotsdl** [comment]
> * (currently supported) a set of non-interpolation-based torsion parameters, with attributes (for nonzero, consecutive integer values of X):
>       
>   * `kX` (required)
>   * `phaseX` (required)
>   * `periodicityX` (required)
>   * `idivfX` (optional)
> 
> * (to be added) a set of a set of interpolation-based torsion parameters, with attributes (for nonzero, consecutive integer values of X and nonzero, consecutive integer bond orders B):
>       
>   * `kX_bondorderB` (required)
>   * `phaseX` (required)
>   * `periodicityX` (required)
>   * `idivfX` (optional)

@j-wags to confirm, based on above: we want to constrain the implementation to only handle cases were higher order bonds have different `kX` (hence, we have `kX_bondorderB`), but the same `phaseX`, `periodicityX`, `ivdivfX`, yes?

**Comment by ChayaSt** [comment]
@dotsdl and @j-wags, Really cool seeing that this is being worked on!

The biphenyls are a good set to start with. There is another larger set on QCArchive that this would be great to test on. It's the `OpenFF Subsituted Phenyl Set 1`. 
[This figure (C and D](https://chayast.github.io/wbo-manuscript/#fig:substituted_phenyls) shows the linear relationship. It gets more complicated because there are trivalent nitrogens that are coupled with the torsion so maybe for the initial test those molecules should be removed.

**Comment by j-wags** [comment]
@ChayaSt Thanks for the input! Our goals right now are to provide the functionality to support assignment of WBO-interpolated torsion parameters, and I'd love to get your thoughts on the scope of this implementation. I think there's _really_ cool science/fitting to be done with this, but it's waiting on the implementation itself. 

> One question I have is how are you planning to do this interpolation when there are several torsion types per torsion scan?

We'll need to be crafty with making SMARTS for interpolation-based torsions. The current implementation will support a mix of interpolation-based and "vanilla" torsions, so it may be good to phase the interpolation-based ones in gradually during rounds of fitting.

> By weighting the different torsion types differently we might also be able to capture the asymmetry in the torsion scans that show up for torsions that involve chiral centers.

Oh boy, that's going to be an adventure. I'll need to run some tests to ensure we can handle stereo-specific SMARTS.

@dotsdl Apologies I missed your question above:

**Comment by j-wags** [comment]
@dotsdl Apologies I missed your question above:

> we want to constrain the implementation to only handle cases were higher order bonds have different kX (hence, we have kX_bondorderB), but the same phaseX, periodicityX, ivdivfX, yes?

Yes, completely correct.

**Comment by dotsdl** [comment]
Can we close this now that #590 is merged?

**Comment by mattwthompson** [comment]
I will leave it to you and @j-wags, as you spent time in the weeds of this feature, but I'd think so (and also probably not a 0.7.1 feature 😉)

**Comment by j-wags** [comment]
Oh! I've missed this for months. Yes, reviewing the discussion above, #590 closes this issue!
