### ISSUE TITLE
Remove requirement for OEMols of components if compatible Topologies provided

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#58]
In the paper draft on SMIRNOFF, @jchodera remarks

> Now that OpenMM `Topology` supports OEChem-compatible bond orders, we can remove the requirement that `OEMol` objects be provided!

This is true, and presumably what we would do is make them optional as long as the `Topology` includes bond orders. Though it's irrelevant until there are tools commonly in use which produce OpenMM `Topology` objects which have bond orders. As far as I'm aware this is so far only tools from OpenEye (e.g. in github.com/oess/oeommtools); @jchodera , are there others? If this is something people would use soon then I'm all for putting it in place quickly.

**Comment by jchodera** [comment]
I believe that's correct.

We may want to add bond order support to OpenMM's [`PDBFile`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/pdbfile.py).

Does `parmed` respect bond orders when converting to/from OpenMM `Topology` objects?

**Comment by jchodera** [comment]
It turns out that existing `Topology` formats in MDTraj, OpenMM, and ParmEd equivalents contain insufficient information for this to be feasible, so I'm closing this for now.
