### ISSUE TITLE
Improper torsion SMIRKS around trivalent N in proline is mis-percieved as Proper

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#592]
**Describe the bug**
In porting AMBER FF14SB into SMIRNOFF format, we found that the SMARTS for the improper torsion on the trivalent nitrogen in Proline was being mis-identified as a proper torsion. MWE below.

The issue is with the improper around the N in this structure. I think I've labeled the tagged atoms correctly here. (Note that this is actually a _substructure_ SMARTS, so the structure drawer added implicit Hs to satisfy the valence at the termini of the amino acid, which aren't actually in the SMARTS)
<img width="184" alt="Screen Shot 2020-05-08 at 9 29 03 AM" src="https://user-images.githubusercontent.com/16329175/81427108-c8756b80-9149-11ea-9376-fd41deac0ae3.png">

**To Reproduce**
```
from openforcefield.typing.chemistry import ChemicalEnvironment
a = ChemicalEnvironment('[H][C@:4]1(C(C([C:3]([N:2]1[C:1](=O)C([H])([H])[H])([H])[H])([H])[H])([H])[H])C=O')
print(a.getType())
```
> ProperTorsion

**Comment by j-wags** [comment]
It seems like the `N:2`-`C:4` bond isn't being parsed, probably due to being defined using ring notation (the `1` outside of brackets)
```
for at1, at2, info in a._graph_edges(data=True):
    bond = info['bond']
    print(at1.asSMIRKS(), at2.asSMIRKS(), bond.asSMIRKS())
```

> [H] [C@:4]1 -,:
> [C@:4]1 [C] -,:
> [C@:4]1 [C] -,:
> [C] [C] -,:
> [C] [H] -,:
> [C] [H] -,:
> [C] [C:3] -,:
> [C] [H] -,:
> [C] [H] -,:
> [C:3] [N:2]1 -,:
> [C:3] [H] -,:
> [C:3] [H] -,:
> [N:2]1 [C:1] -,:
> [C:1] [O] =
> [C:1] [C] -,:
> [C] [H] -,:
> [C] [H] -,:
> [C] [H] -,:
> [C] [O] =
>

**Comment by j-wags** [comment]
I think the issue is that the SMIRKS parser is confusing ring-index integers with tag-index integers. When I switch the `:1` and `:4` tags (which results in an equivalent improper torsion), it is correctly identified as an improper:
```
#a = ChemicalEnvironment('[H][C@:4]1(C(C([C:3]([N:2]1[C:1](=O)C([H])([H])[H])([H])[H])([H])[H])([H])[H])C=O')
a = ChemicalEnvironment('[H][C@:1]1(C(C([C:3]([N:2]1[C:4](=O)C([H])([H])[H])([H])[H])([H])[H])([H])[H])C=O')
print(a.getType())
```
> ImproperTorsion

**Comment by jchodera** [comment]
Yikes! Does this occur in both RDKit and OpenEye backends?
