### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#598]
The new Sphinx has an API change that doesn't work with the now-unmaintained m2r package: https://github.com/sphinx-doc/sphinx/issues/7420

~I tried to fix this in #594 but failed. This issue is to either find a replacement for m2r or pin sphinx to 2.x.x~

Replacing m2r didn't get our funciton/method docs building. This issue has been rescoped to that.

**Comment by dotsdl** [comment]
Taking this on; I'll review #594 and jump off from there.

**Comment by dotsdl** [comment]
See [this comment](https://github.com/openforcefield/openforcefield/pull/602#pullrequestreview-419531903) on path forward beyond just a temporary fix.

**Comment by j-wags** [comment]
Looks like someone has started hosting a fork of the abandoned `m2r` project (called `m2rr`). It's pypi-only right now, but that's not a bad start. https://github.com/qhua948/m2rr

**Comment by j-wags** [comment]
@SimonBoothroyd fixed this in #744!
