### ISSUE TITLE
Overriding `__getitem__` in ForceField

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield#599]
**Is your feature request related to a problem? Please describe.**
It would be nice to have cleaner lookups from `ForceField` objects to `ParameterHandler` objects, and possibly also directly to the individual parameters
```python3
>>> ff = ForceField('openff-1.1.0.offxml')
>>> ff['Bonds']
<openforcefield.typing.engines.smirnoff.parameters.BondHandler object at 0x7faeffb64b90>
>>> # Also could do
>>> # ff['Bonds']['b12']
# returns the particular parameter object
```

**Describe the solution you'd like**
This can be done by overriding `__getitem__` of `ForceField` and its individual `ParameterHandler` objects. Although some care is needed to ensure strange things don't happen. 

**Describe alternatives you've considered**
`ff.get_parameter_handler('Bonds')` works fine, as does `ff.get_parameter_handler('Bonds').get_parameter({'id': 'b12'})`, but the syntax sugar of `ff['Bonds']['b12']` would be preferred.

**Additional context**
`ParameterHandlers.get_parameter()` doesn't simply take in a value, it takes in a dict mapping that allows it to look up against SMIRKS patterns, ids, or in principle whatever other attribute is stored.

I saw this brought up in #310 and it has probably been mentioned elsewhere.

@j-wags says:

>Note, though, that ForceField.get_parameter_handler has a very important behavior that is different form a lookup -- If the parameterhandler for the requested SMIRNOFF section tag doesn't exist, it is initialized by get_parameter_handler, whereas I'd expect a lookup for the same  tag to fail.

**Comment by j-wags** [comment]
Just speculating -- In the distant future (not now), this could be extended to either accept a `string` or a `ParameterHandler` type/subclass. But that change could be made in a reverse-compatible way, so that shouldn't influence our design choices now. The behavior of a type-based lookup might be complex (what if they have the same tagname, but a different actual class?) so we can punt on that.

**Comment by mattwthompson** [comment]
Just to document the status:

#600 implements `__getitem__` for the `ForceField` class, but that only gets you the corresponding `ParameterHandler`, not an actual parameter. Behavior like `ff['Bonds']['b12']` is not possible but something like `ff['Bonds'].get_parameter({'id': 'b12'})`. The next step, overriding `ParameterHandler.__getitem__` is a little trickier but should be feasible, however, I consider it a lower priority. Let's leave this issue open until then.
