### ISSUE TITLE
Expand add_parameter Functionality

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#605]
**Describe the solution you'd like**

The `ParameterHandler.add_parameter` function should:

- allow a `Parameter` object to be passed in rather than just a dictionary.
- allow the user to optionally specify whether the new parameter should be added before and / or after certain existing parameters so that it gets applied in the correct circumstances 

e.g.

```
vdw_handler = off_force_field.get_parameter_handler("vdW")
vdw_handler.add_parameter(my_new_parameter, after="[#1:1]-[#6X4]", before="[#1:1]-[#6X4](-[#7,#8,#9,#16,#17,#35])-[#7,#8,#9,#16,#17,#35]")
```

**Comment by j-wags** [comment]
This is a good idea. A few additional thoughts:
* I'd support `before` and `after` accepting either a smirks or an integer (mirroring the behavior of `list.insert`)
* it'd probably be good to allow _either_ `before` or `after` kwargs, but not both at the same time
* The behavior of `before` and `after` might get complicated since we don't _currently_ police for multiple parameters with identical smirks (there's an issue open for this, so we might need to resolve that in the same PR)

**Comment by mattwthompson** [comment]
> it'd probably be good to allow either before or after kwargs, but not both at the same time

So `before`/`after` means "put this new parameter immediately before/after this tagged (existing) parameter"? This all seems good, I just want to clarify. It does seem like if `before` and `after` are > 1 lines apart, there would not be a reliable way to pick.

This could also specify `id` and fail if they don't exist (unless somebody wants to intentionally write id tags that look like SMARTS, which is maybe something we should forbid? Bit out of scope here)

**Comment by SimonBoothroyd** [comment]
> it'd probably be good to allow either before or after kwargs, but not both at the same time

Having both could be useful if you require that a parameter needs to go between two existing parameters, and want to validate that this is possible (e.g. raise an exception when `before` is found after `after`).

> So before/after means "put this new parameter immediately before/after this tagged (existing) parameter"?

Exactly

> This all seems good, I just want to clarify. It does seem like if before and after are > 1 lines apart, there would not be a reliable way to pick.

Just always put it directly after the "after" parameter and document this will be the case. Kind of arbitrary, but as long as it's consistent then that's fine.

**Comment by mattwthompson** [comment]
Either approach sounds reasonable to me; I don't have a sense of how valuable validating two parameters would be for the user but it's a bit of an edge case so it's fine as long as it's consistent and documented I don't see the harm
