### ISSUE TITLE
Docs default to 0.6.0 release, rather than 0.7.0

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#635]
**Describe the bug**
https://open-forcefield-toolkit.readthedocs.io/ redirects to https://open-forcefield-toolkit.readthedocs.io/en/0.6.0/, which is not the latest release (0.7.0)

**To Reproduce**
Navigate to https://open-forcefield-toolkit.readthedocs.io/

**Output**
You end up at https://open-forcefield-toolkit.readthedocs.io/en/0.6.0/

**Computing environment (please complete the following information):**
N/A

**Comment by j-wags** [comment]
My bad! Fixed.
