### ISSUE TITLE
Make a conformer generation CLI tool

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openforcefield#641]
**Is your feature request related to a problem? Please describe.**
People like the conformer energies script. We should make one that also _generates_ conformers. However, we don't want people to confuse OpenFF force fields' performance with that of the original conformer generation method (since right now we do not have a native conf. gen method).

**Describe the solution you'd like**

Create a script, `generate_conformers.py`, that can be invoked as follows:

`python generate_conformers.py -m mymol.smi -f openff-1.2.0 --rdkit --rms_cutoff 0.25`

Required:
* `--rdkit` or `--openeye` is a required argument specifying which underlying toolkit to use for initial conformer generation
* `-m`, `--molecule filename` is the molecule file to load
* `-f`, `-forcefield openff-x.y.z` is the FF to load (with or without the `.offxml` part, maybe also accepting "X.Y.Z" string)

Optional
* `-r`, `-rms_cutoff` (default `0.25`, angstroms) -- The redundancy cutoff between _pre-minimized_ conformers to pass to the `generate_conformers` method
* `-p`, `-prefix mymol` (default `molecule.name` for each loaded molecule if defined, otherwise `moleculeN`, where N is the order is was read from the file) -- string prefix for outputted files (eg `mymol_conf1.sdf`).
* `--constrained` (default `False`/unset) -- Whether to use `openff-unconstrained-X.Y.Z`. By default we use the unconstrained FF

Notes:
* If possible, there should be either _no_ or _a very generous_ energy cutoff during initial conformer _generation_ (that way, RDKit won't disqualify a "good" conformer early on because of its built-in FF)
* ~This should use a "conformer collapsing" scheme similar/identical to `conformer_energies.py`~ This becomes complicated if the repeats are non-contiguous, so let's just have an optional `--deduplicate-conformers` argument instead, and by default just run naively on all input mols. 
* If charges are defined on the molecule when loaded (so, like, if the `<atom.dprop.PartialCharges>` flag is set), then those should be used for the calculation (passed to the `charge_from_molecules` kwarg)
* The conformers should be output as separate SDFs with SD data pairs for 
    * `absolute_energy` in kcal/mol
    * conformer generation method (openeye version or rdkit version)
    * ~partial charges (so, use `ForceField.to_openmm_system`'s `return_topology` kwarg, and attach the final coordinates to `ret_topology._reference_molecules[0]`, then save that to file)~ My mistake -- this data isn't available currently.

Tests:
* loading one molecule from a `.sdf` file WITHOUT charges
* loading one molecule from a `.sdf` file WITH charges
*  (OE only) loading one molecule from a `.mol2` file WITH charges
*  (OE only) loading one molecule from a `.mol2` file WITHOUT charges (is this even possible)
* loading a molecule with a defined `name` (from any format) and ensuring the output file has that prefix
* loading a molecule with a defined `name` (from any format), and providing a `-f` option and ensuring the output file has the `-f` prefix
* loading a molecule with a defined `name` (from any format) and ensuring the output file has that prefix
* loading multiple molecules from a `.sdf` file
* loading one molecule from SMILES in a `.smi` file
* loading multiple molecules from SMILES in a `.smi` file
* loading a molecule with ambiguous stereo from SMILES and enumerating stereoisomers
* loading a molecule with defined stereo from SMILES and preserving that stereochemistry

Undecided/Implementer's choice:
* What to do if prefix is provided, but multiple molecules are in file?

Notable "Don'ts":
* Don't try to provide "relative energies", since our conformer collapsing routine isn't reliable, and people will get mixed up about which "minimum" the energy is relative to.
* Don't make the `-f` argument optional, since then people wouldn't know which FF is being used on the backend. If we want to remove that argument, we could make a variant of this script for each FF (`generate_conformers_1.2.0.py`)
* If we want to collapse conformers, we could do so by appending the SDF texts to each other. But I think this would be a bad built-in behavior because OFFTK doesn't natively handle multiconformer SDFs. 
* I thought about whether we should make a CLI entrypoint for this script, or build it into a OFF Toolkit module, and I don't think we should. Keeping it as just a python script makes the contents more visible to our users (some of whom are reusing our code already), and makes it easier to update/version (since it's not hidden somewhere in an install directory)

**Comment by mattwthompson** [comment]
> The conformers should be output as separate SDFs with SD data pairs for ... **partial charges** (so, use ForceField.to_openmm_system's return_topology kwarg, and attach the **final coordinates** to ret_topology._reference_molecules[0], then save that to file)

Is there a typo in here, or do I not understand how data flow through `to_openmm_system` and/or `Molecule.to_file`?

**Comment by j-wags** [comment]
Yeah, this one's a bit subtle.

We want to assign charges specified by the force field. Today, that means "always AM1BCC", but that won't be the case forever. So we can't just call `mol.compute_partial_charges_am1bcc`. Instead we have to let the force field do its thing.

So, the workflow here is:
```
for offmol in loaded_offmols:
    _ , ret_topology = ff.create_openmm_system(offmol.to_topology(), return_topology=True)
    (generate confs and minimize them)
    output_mol = ret_topology.reference_molecules[0] # this will have correct final charges assigned by ff
    for conf in confs:
        output_mol.conformers = None
        output_mol.add_conformer(conf)
        output_mol.to_file('conf${N}_min.sdf', file_format='sdf')
```

**Comment by mattwthompson** [comment]
Do you expect the topology returned by `return_topology=True` to include partial charges? It currently does not:

```python
In [1]: from openforcefield.topology import *

In [2]: from openforcefield.typing.engines.smirnoff import ForceField

In [3]: parsley = ForceField('openff-1.2.0.offxml')

In [4]: mol = Molecule.from_smiles('CCO'); top = Topology.from_molecules(mol)

In [5]: _, new_top = parsley.create_openmm_system(top, return_topology=True)

In [6]: assert [*new_top.reference_molecules][0].partial_charges is None

In [7]: assert [*new_top.reference_molecules][0].partial_charges is not None
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-81f3c5b6d612> in <module>
----> 1 assert [*new_top.reference_molecules][0].partial_charges is not None

AssertionError:
```

In this context (single-molecule systems) it's probably acceptable to back-map the charges from the OpenMM object, but that wouldn't work so well for more complicated topologies. It may be worth spinning this out into a separate issue to discuss the broader impact.

**Comment by mattwthompson** [comment]
> loading a molecule with a defined name (from any format), and providing a -f option and ensuring the output file has the -f prefix

Here, do you mean `-p` or `-f`?

>The conformers should be output as separate SDFs

There are some unclear edge cases on how to handle file names.

1. For molecules with ambiguous stereochemistry, I figure each of the stereoisomers that are found should be output as distinct files, but should this be encoded in the file name like `dichloroethane_stereo0_conf0.sdf`?
2. For input formats that do include conformers - make one new conformer per conformer found, or allow the number of conformers output to differ from those input? I see the value in this tool generating new conformers, but this would require another argument to put an upper bound on the number to return.
3. For input formats that do not include conformers (only SMI, I believe) - generate only one conformer, or several, per SMILES entry?
2. The above but with ambiguous stereochemistry - again, generate one and only one conformer per stereoisomer?
3. Combinations of the above, i.e. multiple distinct molecules, each possibly having multiple conformers, stereochemistry, or possibly ambiguous stereochemistry. Maybe with a `--prefix` thrown in to complicate things, although that may not make much sense for the multi-molecule case.

**Comment by j-wags** [comment]
Ah, these are really good questions. 

> Do you expect the topology returned by return_topology=True to include partial charges? It currently does not:

Oof. My mistake. I'll open a PR to add the charges to the `ret_topology.reference_molecule`s, but for now let's remove that requirement from this spec. Though, could you keep pulling the output molecule from the returned topology, so we can make that change silently take effect after the 0.8.0 release. 

> Here, do you mean -p or -f?

Ah, you're right. I should have written `-p`, not `-f`.

> For molecules with ambiguous stereochemistry, I figure each of the stereoisomers that are found should be output as distinct files, but should this be encoded in the file name like dichloroethane_stereo0_conf0.sdf?

That sounds good to me.

> For input formats that do include conformers - make one new conformer per conformer found, or allow the number of conformers output to differ from those input? I see the value in this tool generating new conformers, but this would require another argument to put an upper bound on the number to return.

> For input formats that do not include conformers (only SMI, I believe) - generate only one conformer, or several, per SMILES entry?
> The above but with ambiguous stereochemistry - again, generate one and only one conformer per stereoisomer?
> Combinations of the above, i.e. multiple distinct molecules, each possibly having multiple conformers, stereochemistry, or possibly ambiguous stereochemistry. Maybe with a --prefix thrown in to complicate things, although that may not make much sense for the multi-molecule case.

We should always generate multiple conformers for each input. The input conformers, if present, are basically irrelevant (except in the case that we use the geometry to determine the graph molecule's stereochemistry). What matters are the input _graph molecules_. The `rms_cutoff` argument should be the only limiter for the number of conformers generated per graph molecule in the initial version of this tool. 

In the future, we could add functionality to hold on to the geometry of the input conformer, and maybe include it among the generated conformers for minimization, but I wouldn't add it in the initial PR. Folks interested in minimizing their particular conformer should use the `conformer_energies` script, not this one. While that's still separate, we shouldn't try to duplicate the functionality here. 

Reading from multi-conformer files is tricky. Could we add an optional `--deduplicate-conformers` argument? If this is set, the tool would read the file, appending each loaded molecule's SMILES to a list or set. Then, if a molecule is loaded with a SMILES that was already seen, the loader will skip it and print a warning that it's being skipped. The molecule index (used for numbering the output) should increment even if the molecule is skipped. 

If the flag is NOT set, then we should not attempt to deduplicate or collapse conformers (and I'm updating my original spec to include this). We'd just treat all inputs as unique.

**Comment by j-wags** [comment]
I've opened a PR to make `return_topology` add charges to the reference molecules. Could you review if you have a chance? https://github.com/openforcefield/openforcefield/pull/670

**Comment by j-wags** [comment]
Ah, this has been closed by development in the openff-cli repo.
