### ISSUE TITLE
Orphaned TopologyParticle?

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield#651]
There is a `TopologyMolecule.particle` method that attempts to return instances of `TopologyParticle`, which is never defined in the current codebase. ([Not tested], and that's probably for the better)

```
(openff-dev) [openforcefield] grep -R "class Topology" .                                                                                                       ci-lint  ✭ ✱
./openforcefield/topology/topology.py:class TopologyAtom(Serializable):
./openforcefield/topology/topology.py:class TopologyBond(Serializable):
./openforcefield/topology/topology.py:class TopologyVirtualSite(Serializable):
./openforcefield/topology/topology.py:class TopologyMolecule:
./openforcefield/topology/topology.py:class Topology(Serializable):
(openff-dev) [openforcefield] grep -R "class TopologyParticle" .                                                                                               ci-lint  ✭ ✱
```

My other guess, that it's something @trevorgokey is working on in https://github.com/openforcefield/openforcefield/pull/548, didn't bear any fruit. 

There's some history (#233, #235) so I figure it may have just slipped through the cracks? I will remove this if there are not immediate plans for it.

**Comment by trevorgokey** [comment]
Go ahead and leave it there; I will modify it to work with the virtual site PR (#548). I currently have a `class TopologyVirtualParticle(TopologyVirtualSite)` in the implementation, so a `TopologyParticle` seems intuitive to have (even though I never had to use this missing functionality).
