### ISSUE TITLE
Fix some issues with host-guest examples on some installations

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#66]
Niel Henriksen notes some issues with the host-guest example on his installation; https://github.com/open-forcefield-group/openforcefield/pull/56#issuecomment-334301350

**Comment by slochower** [comment]
I'm loosely following the host-guest example notebook and running into an issue loading the force field (i.e., `ff = ForceField(...)`). I think I have a minimal model of the issue, but I'm actually not sure if this command is supposed to work "out of the box." Does this command require there is a molecule already loaded? Because my system is a bit different, I skipped most of the middle portion of the example notebook with regards to docking.

```python
from openforcefield.typing.engines.smirnoff import *
ff = ForceField('forcefield/smirnoff99Frosst.ffxml') 
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-40e4dbcf2f8c> in <module>()
----> 1 ff = ForceField('forcefield/smirnoff99Frosst.ffxml')

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in __init__(self, *files)
    532         """
    533         self._forces = []
--> 534         self.loadFile(files)
    535 
    536     def loadFile(self, files):

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in loadFile(self, files)
    579 
    580         # Parse XML, get force definitions
--> 581         self.parseXMLTrees()
    582 
    583     def parseXMLTrees(self):

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in parseXMLTrees(self)
    626             for child in root:
    627                 if child.tag in parsers:
--> 628                     parsers[child.tag](child, self)
    629 
    630 

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in parseElement(element, ff)
   1781         # Register all SMIRNOFF torsion definitions.
   1782         for torsion in element.findall('Proper'):
-> 1783             generator.registerProperTorsion(torsion, element)
   1784         for torsion in element.findall('Improper'):
   1785             generator.registerImproperTorsion(torsion, element)

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in registerProperTorsion(self, node, parent)
   1761     def registerProperTorsion(self, node, parent):
   1762         """Register a SMIRNOFF torsiontype definition for a proper."""
-> 1763         torsion = PeriodicTorsionGenerator.ProperTorsionType(node, parent)
   1764         self._propertorsiontypes.append(torsion)
   1765 

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in __init__(self, node, parent)
   1680             # Check that the SMIRKS pattern matches the type it's supposed to
   1681             try:
-> 1682                 chemenv = ChemicalEnvironment(self.smirks)
   1683                 thistype = chemenv.getType()
   1684                 if thistype != 'Torsion':

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/chemistry/environment.py in __init__(self, smirks, label, replacements)
    469 
    470         # Check that the created Environment is valid
--> 471         if not self.isValid():
    472             raise SMIRKSParsingError("Input SMIRKS (%s), converted to %s \
    473                     is now invalid" % (smirks, self.asSMIRKS()))

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/chemistry/environment.py in isValid(self, smirks)
    482         qmol = OEQMol()
    483         if smirks is None:
--> 484             smirks = self._asSMIRKS()
    485         if self.replacements is not None:
    486             smirks = OESmartsLexReplace(smirks, self.replacements)

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/openforcefield/typing/chemistry/environment.py in _asSMIRKS(self, initialAtom, neighbors, smarts)
    707 
    708         if initialAtom == None:
--> 709             initialAtom = self.getAtoms()[0]
    710 
    711         if neighbors is None:

~/data/applications/anaconda3/envs/openmm/lib/python3.6/site-packages/networkx/classes/reportviews.py in __getitem__(self, n)
    176 
    177     def __getitem__(self, n):
--> 178         return self._nodes[n]
    179 
    180     # Set methods

KeyError: 0
```

**Comment by jchodera** [comment]
@bannanc : It looks like this is a failure inside of the chemical environments SMIRKS parsing. Can you see if you could at least get the calls within
```
chemenv = ChemicalEnvironment(self.smirks)
```
to return the problematic SMIRKS string fed in if an exception is raised?

**Comment by jchodera** [comment]
To be clear: There's probably something else causing this issue, but without returning more informative errors when misformatted SMIRKS are passed, it's going to be hard for us to debug!

**Comment by slochower** [comment]
@jchodera Is it okay if I try loading the force field before I pass *any* SMIRKS? Or must I load some SMIRKS first and then `ForceField` command?

**Comment by bannanc** [comment]
This is the same error Chris detailed in issue #63 It was fixed with PR #64 
That exception is coming from networkX, you need to have a version in 1.X. 

@jchodera I believe any chemicalenvironment exceptions do return the SMIRKS pattern, the problem here is in the networkx incompatibility. I'm looking into fixing it (see issue #65) I should have a PR up in the next couple of days, networkx has made quite a few changes in their API that makes getting the nodes in a Graph work differently.

**Comment by slochower** [comment]
@bannanc, I see. I think `conda install -c omnia openforcefield` pulled in `    networkx:       2.0-py36_0   conda-forge`. I've just tried 

```
$ conda install networkx=1.11
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/dslochower/data/applications/anaconda3/envs/openmm:

The following packages will be DOWNGRADED:

    networkx: 2.0-py36_0 conda-forge --> 1.11-py36_0 conda-forge

Proceed ([y]/n)? y

networkx-1.11- 100% |################################| Time: 0:00:01   1.26 MB/s
```
This tentatively seems to fix things!

**Comment by davidlmobley** [comment]
@slochower - For `openforcefield` there should not be, I believe, a significant difference between conda and github at this point.

@bannanc - should we pin this to a specific networkx version for now or will your fix come in soon enough we don't need to?

**Comment by bannanc** [comment]
@davidlmobley John pinned this to a specific version in PR #64 When did you last do a release? Maybe we need another to have this in the release

**Comment by bannanc** [comment]
> @bannanc - should we pin this to a specific networkx version for now or will your fix come in soon enough we don't need to?

@davidlmobley Did you mean to add a version check somewhere.

**Comment by davidlmobley** [comment]
It can be added to the requirements, as I understand it, so that someone conda-installing gets the right networkx automatically.

**Comment by bannanc** [comment]
The last release was on on May 24, so I think we need to do a new one.

**Comment by bannanc** [comment]
Which was PR #35

**Comment by slochower** [comment]
Is there a way to tell, if say I install through `conda` and it says I have version 0.0.2, which commits are covered with that release?

**Comment by bannanc** [comment]
@slochower if you conda install includes the last released version, details are available [here](https://github.com/open-forcefield-group/openforcefield/releases/tag/0.0.2) about what changes were included in that release

**Comment by slochower** [comment]
@bannanc Right. It's not clear on a quick glance at the release notes, for example, if PR #64 was merged into the version that I had installed via conda (0.0.2). The way I checked was to click PR #64 and see what commit has it has, then go into the releases page, click "59 commits" and scan for the commit hash of #64. Is that the easiest way to do it? I figured the experts probably know a quicker way.

**Comment by bannanc** [comment]
Oh no, the way I found that the most recent PR in the 0.0.2 release was by clicking: 

From the release page --> Click on the hash for the last commit next to the release (see screen shot below)

![0 0 2](https://user-images.githubusercontent.com/11968541/31689448-4d34cc9e-b344-11e7-9034-8c4adebc1ac5.jpg)

The other thing to note is that the release is dated (May 24th) so the state of the repo on that date is what was included in that release.

**Comment by slochower** [comment]
I'm continuing this thread because I have another question related to the host-guest example, but I can move to a separate issue if it's easier.

1. Is there a way to read in both (AMBER-style) coordinates and topology to an `OEMol` -- and then use the `OEMol` with `ff.createSystem`? I've only had luck reading in mol2.

2. If I do read in a mol2, is `generateTopologyFromOEMol()` the right command to make a topology object that can be used with `ff.createSystem`? When I tried that with a host-guest complex, the connectivity was all wrong.

**Comment by davidlmobley** [comment]
@slochower 

> Is there a way to read in both (AMBER-style) coordinates and topology to an OEMol -- and then use the OEMol with ff.createSystem? I've only had luck reading in mol2.

This should be doable. But first you need to know the challenge, which is that that you need to end up with a REAL molecule, which has bond orders, etc., and this information is not contained in a topology file. That said, OpenMM Topologies DO have room to hold bond order information now, so if you happen to have an OpenMM Topology which has this information, you CAN translate it to an OEMol. here's the authoritative way of doing it (conda-installable tool): https://github.com/oess/oeommtools/blob/master/oeommtools/utils.py#L99

However, coming from AMBER-style topology/coordinates, it will take more work. Probably you'd be looking at using ParmEd to read these in, then making a utility function which does something LIKE the function I just linked to but uses the OpenEye toolkits to INFER the bond orders based on the chemistry (OEPerceiveBondOrders, I believe, perhaps also perceiving aromaticity). If you create such a function, I'd be happy to have it included here as a utility. It will go wrong sometimes (e.g. if your coordinates contain a bond which is stretched far from its equilibrium value so it is perceived incorrectly), but is basically your only path forward.

> If I do read in a mol2, is generateTopologyFromOEMol() the right command to make a topology object that can be used with ff.createSystem? When I tried that with a host-guest complex, the connectivity was all wrong.

We need to replace `generateTopologyFromOEMol()` with the functionality in `oeommtools` as it is really a much more general tool and should always be able to correctly go from OEMol to Topology and back.T hough I AM suprirsed you're getting connectivity wrong with `generateTopology...`. Is this the issue with residue names coming up again? (Are you dealing with a multi-residue mol2 file?) I'd be very interested in a specific case to reproduce the bug and it might induce me to replace `generateTopologyFromOEMol` immediately (I'd not run into a case where it was actually causing serious problems so it wasn't high priority for me to replace it).

**Comment by slochower** [comment]
> That said, OpenMM Topologies DO have room to hold bond order information now, so if you happen to have an OpenMM Topology which has this information, you CAN translate it to an OEMol. here's the authoritative way of doing it (conda-installable tool): https://github.com/oess/oeommtools/blob/master/oeommtools/utils.py#L99

I don't in this case, and might not generally have OpenMM topologies available. I tried to go through ParmEd naively, and it didn't work.
```python
from parmed import load_file
cb6_but = load_file('../test/cb6-but/vac.topo', '../test/cb6-but/vac.crds')
from oeommtools.utils import *
openmmTop_to_oemol(cb6_but.topology, cb6_but.coordinates)
```
This gives a lot of errors.

> ...then making a utility function which does something LIKE the function I just linked to but uses the OpenEye toolkits to INFER the bond orders based on the chemistry...

Do you mean by looking at the connectivity and existing hydrogens, determine the bond order? Or something else?

> (Are you dealing with a multi-residue mol2 file?)

It was a host-guest complex, so yes. However, the connectivity is also messed up with the host alone. I thought perhaps it was an issue with using GAFF atom types, but I get the same issue if I use SYBYL atom types.

Using this code...
```python
mol = oechem.OEMol()
ifs = oechem.oemolistream('../test/cb6-but/cb6.sybyl.mol2')
flavor = oechem.OEIFlavor_Generic_Default | oechem.OEIFlavor_MOL2_Default | oechem.OEIFlavor_MOL2_Forcefield
ifs.SetFlavor(oechem.OEFormat_MOL2, flavor)
oechem.OEReadMolecule(ifs, mol)

# Perceive tripos types
oechem.OETriposAtomNames(mol)

title = mol.GetTitle()
if not title:
    title = "Untitled"
print ("%s %.3f %d %d %d %d %d" %
  (title,
   oechem.OECalculateMolecularWeight(mol),
   mol.NumAtoms(),
   oechem.OECount(mol, oechem.OEIsHeavy()),
   oechem.OECount(mol, oechem.OEAtomIsInRing()),
   oechem.OECount(mol, oechem.OEIsRotor()),
   mol.NumConfs()
   ))
topology = generateTopologyFromOEMol(mol)
oenb.draw_mol(mol)
```
... this is what I see...
![openff](https://user-images.githubusercontent.com/5393995/31747001-453161ca-b41f-11e7-9150-4039212a7fe8.png)

I might be making a simple mistake, as I'm not very familiar with the OEChem toolkit.

**Comment by slochower** [comment]
Regarding the last point, if I explicitly write out a mol2 file, it looks okay. 
```python

ofs = oechem.oemolostream()
ofs.open('cb6.oechem.mol2')
ofs.SetFormat(oechem.OEFormat_MOL2)
oechem.OEWriteMolecule(ofs, mol)
ofs.close()
```

I believe `oenb.draw_mol()` is failing here. So that might not be a problem after all. But generating a proper topology still remains a hurdle.

**Comment by davidlmobley** [comment]
@slochower - I have to be brief, so if the below doesn't set you on track, perhaps we can schedule a brief call and talk through the issues. You're running into problems I understand fairly well and which we should be able to avoid/fix easily. 

Note, if you can get a proper OEMol (which you should be able to do trivially by reading it from a file using the OpenEye toolkits, if you have a well-formed file in PDB, mol2, or sdf formats), you can use the utility functionality in `oeommtools` that I linked to to generate a proper OpenMM Topology. OpenEye supports that toolkit, and it ought to behave, not just for hosts, but for proteins, etc. Since AMBER, ParmEd, and MDTraj all (as well as other tools) should be able to generate a (reasonably) well formed PDB file from a AMBER topology/coordinate file, you SHOULD be able to get this to work easily via reading in the resulting PDB using OpenEye tools and then perceiving the aromaticity and bond orders, then converting to an OpenMM Topology via `oeommtools`.

The thing you do NOT want to do is to go to a `mol2` file via a tool which does not "know" chemistry and/or from a format which doesn't retain chemistry. Remember, an AMBER topology/coordinate file does not have any information about bond orders (or chemistry, for that matter -- everything is just a graph with nodes labeled by atom types). If you go to a mol2 file without first inferring bond orders (which you need a chemistry toolkit to do) the bond orders in your mol2 file will be incorrect and then tools reading that mol2 file will end up with the wrong molecule (because it has incorrect bond orders). 

So, to restate, my procedure would be:
1) Dump your AMBER stuff to a PDB
2) Process the PDB via OpenEye toolkits to get an OEMol with bond orders, e.g. a proper molecule. You can check it by writing it out to mol2 at THIS stage and visualizing to make sure the bond orders, etc., are what you expect
3) Turn the resulting OEMol into an OpenMM Topology via functionality in `oeommtools`

This should be "foolproof" except that you need to remember step 2 will be incorrect if you have especially strained bonds since you're asking OpenEye to infer the bond orders from the bond lengths and connectivities. But there is no other way forward unless you are prepared to provide a mol2 file with proper bond orders -- which you don't have if you're originating from an AMBER topology/coordinate file.

I should probably write something formal on this for some venue because this is such a universal issue for people working with small molecules or non-proteins.

**Comment by davidlmobley** [comment]
(I expect that your approach above will fail because at best (a) all of the bond orders will be messed up, but (b) the connectivities also may be messed up, because you are asking ParmEd to write a mol2 file without it knowing your bond orders...)

**Comment by davidlmobley** [comment]
@slochower - were you ever able to get this working? If not, maybe you can provide input files so I can try? 

Also, looking back over this, it looks like your use case is that you want to be able to load AMBER-style topologies and coordinates as a starting point, rather than providing something which identifies your system. I can understand why you might want to do that, such as to build on previous simulations. *However, I don't think this is a well formed problem* unless you are willing to make considerable assumptions.

For example, check out the attached screenshot (from Chris Bayly). These are two different resonance structures of the same molecule. However, they are chemically rather different -- one has a rotatable bond joining the two aromatic rings, the other does not. But from the standpoint of the number/type of atoms present and their connectivity (the information in an AMBER topology/coordinate file) they are identical. HOWEVER, the parameter present for these two in the file won't be identical -- in the one case that central bond will be rotatable, and in the other it won't. Which one of these do you intend to simulate? That information will not be present in your AMBER topology/coordinate file, or not without back-calculating the bond order information from the parameters present in the file... 
<img width="233" alt="screen shot 2017-11-13 at 2 02 04 pm" src="https://user-images.githubusercontent.com/7132257/33057030-916af2a8-ce3d-11e7-8262-96f94540438b.png">

I would argue that this means we simply CAN'T support the fully general form of what you want to do, where we would be able to create a SMIRNOFF system from AMBER parameter/coordinate files. They've thrown away the underlying chemistry and recovering it is a big nuisance. 

Let me know if I can help any further. I'm going to go ahead and try and add some documentation of the chemistry problem here.

**Comment by davidlmobley** [comment]
Incidentally, I expect that a good solution to your problem is just to write your AMBER system to a PDB file, read in with the OpenEye toolkits, and then infer the bond orders from the bond lengths, e.g. `OEPerceiveBondOrders`, see for example https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemFunctions/OEDetermineConnectivity.html

**Comment by davidlmobley** [comment]
I have a PR up which would [add some documentation](https://github.com/openforcefield/openforcefield/blob/issue66/Chemical-starting-points.md) of good starting points for applying SMIRNOFF and why we can't start from (for example) AMBER parameter/coordinate files. Input welcome, comment on #77 .

**Comment by slochower** [comment]
> @slochower - were you ever able to get this working? If not, maybe you can provide input files so I can try?

Oops, sorry! I thought I replied here, but it must have been Slack. Yes, I was able to get it working using the steps outlined above. That is: reading a SYBYL-formatted `mol2` for the host and guest *separately*, using OpenEye to generate a water, appending those three molecules (host, guest, water) to a list of molecules (`mols`), then reading a PDB of the complex, created with `ambpdb` with CONECT records between the host and guest molecules but manually deleting the CONECT records for the TIP3P water, then creating a system using `pdb.topology` and the list of molecules `mols`. I also used `PDBFixer` to set the positions. Perhaps I should upload a little notebook showing these steps explicitly, however I note the points you mention below about the process being a little ill-defined.

> Note, if you can get a proper OEMol (which you should be able to do trivially by reading it from a file using the OpenEye toolkits, if you have a well-formed file in PDB, mol2, or sdf formats), you can use the utility functionality in oeommtools that I linked to to generate a proper OpenMM Topology. 

This sounds like the most parsimonious process (at least more so than what I outlined above) -- but I think we had difficulty getting the host and guest complex into the same `OEMol`, thus we started to separate them, and then it was tricky to get the write topology from `mol2` and coordinates from `pdb` to match up. (Again the issue with using different tools to write different things with different formats and standards...) Should I expect that a structure of the complex can go straight into an `OEMol` or OpenMM topology? In any case, I can give it another shot later this afternoon or early evening to see if things are working smoother now that I've gained a little more understanding of the process!

> Also, looking back over this, it looks like your use case is that you want to be able to load AMBER-style topologies and coordinates as a starting point, rather than providing something which identifies your system. 

The idea of specifying coordinates and topology is so that we can directly compare, say, SMIRNOFF and GAFF. If we use a specifier, which I take mean to something like a SMILES string, then we may start the simulations in a different starting state. Maybe the trick is to *build* the system with identifiers, then load just the coordinates from AMBER? 

> But from the standpoint of the number/type of atoms present and their connectivity (the information in an AMBER topology/coordinate file) they are identical. [...] I would argue that this means we simply CAN'T support the fully general form of what you want to do, where we would be able to create a SMIRNOFF system from AMBER parameter/coordinate files. 

Good point. I think that is a separate, more nuanced issue than the technical one I was having, but I agree this seems to be a problem. Even if the code said: "this input could be part of a resonance structure with different bonded parameters, which do you wish to simulate?" I think that would be really useful, but it may be out of the purview of how you intend people to use this (given what you said above about starting with an identifier).

**Comment by davidlmobley** [comment]
@slochower - thanks for this, for the record. I had in my head we had you up and running, but then when I checked here it looked still unresolved, so I was confused. I guess this is why it's good to do as much as possible on GitHub since there's a better permanent record of it. :) 

> Perhaps I should upload a little notebook showing these steps explicitly, however I note the points you mention below about the process being a little ill-defined.

OK, this would actually be great. You could simply open up a PR to add another example to the host-guest examples if you like.

>  Should I expect that a structure of the complex can go straight into an OEMol or OpenMM topology? In any case, I can give it another shot later this afternoon or early evening to see if things are working smoother now that I've gained a little more understanding of the process!

I believe so, yes. I think if you use JUST ONE TOOLCHAIN rather than trying to bring together files from multiple toolchains, it will probably work much better. So, probably, taking a PDB of the system (or even multiple PDBs, one for each component) and reading them into OpenEye and then inferring bond orders will work smoothly (with the caveats about it *inferring* them); in the worst case you would probably have to use `OEAddMols` to combine the different molecules into a single complex.

>>Also, looking back over this, it looks like your use case is that you want to be able to load AMBER-style topologies and coordinates as a starting point, rather than providing something which identifies your system.
>
>The idea of specifying coordinates and topology is so that we can directly compare, say, SMIRNOFF and GAFF. If we use a specifier, which I take mean to something like a SMILES string, then we may start the simulations in a different starting state. Maybe the trick is to build the system with identifiers, then load just the coordinates from AMBER?

I think if you want to cross-compare AMBER and SMIRNOFF, the EASIEST and most general way to do it is to set both systems up at the same time, as you DO have the chemical identities of your molecules BEFORE setting up an AMBER system, it's just that once you set it up, you throw them away.  

But, yes, the other approach is to take your AMBER coordinates and swap them into a molecule which has the correct chemistry, though that can raise issues about atom ordering, etc. 

Honestly, this whole thing is one of the most frequent hurdles facing small molecule force fields for molecular simulations -- most of our file formats are just terribly protein-centric and the only common format MD packages use which works reasonably well for small molecules is `.mol2`. 

> Good point. I think that is a separate, more nuanced issue than the technical one I was having, but I agree this seems to be a problem. Even if the code said: "this input could be part of a resonance structure with different bonded parameters, which do you wish to simulate?" I think that would be really useful, but it may be out of the purview of how you intend people to use this (given what you said above about starting with an identifier).

Yes, I agree that that's what one might want. I'm not sure if we can do this (it's a chemistry problem) but it's at least on my radar now. There is some overlap between this and #61 , which is about trying to help people check their input molecules or at least make sure they are what is intended.

We're really trying to ultimately envision two categories of users:
1) Someone (like you) who wants to just dump in molecules in whatever form they have them and get reasonable parameters without too much fussing/fiddling (and may be OK with having their molecules "changed" in the process)
2) Someone (like certain pharma users, or workflow users like those on OpenEye's Orion, etc.) who has already invested considerable effort in making sure their molecules are exactly what they want chemically (down to protonation state and tautomer) and wants things processed EXACTLY AS IS and nothing should mess with the chemistry.

So we're basically planning something that does sanity checks (#61), to ALWAYS be used, as well as something which can fix broken chemistry when needed (#78) to be used only when the user asks. Not sure if it would be able to handle resonance issues, but at least it could attempt to infer bond orders from the structure or something similar.

I'll go ahead and mark this as closed but feel free to continue commenting further, and re-open if needed.

**Comment by slochower** [comment]
> OK, this would actually be great. You could simply open up a PR to add another example to the host-guest examples if you like.

Great, I'll try to set something up next week. Thanks for the additional explanation; we briefly discussed it at group meeting yesterday and agree with what you've said.

**Comment by slochower** [comment]
I started to work through an additional host-guest example, with the goal of starting from `mol2` files written by AMBER tools and ending with AMBER-compatible files implementing SMIRNOFF via OpenEye utilities, but I ran into another issue. Based on the knowledge accumulated so far (#66 and #68), the general procedure that I tried was:

0. Generate SYBYL-formatted `mol2` files
1. Load `mol2` files into an `oechem.OEMol`
2. Build reference molecules for water and ions
3. Read in a fully solvated system with host, guest, water, and ions (to get coordinates) with the *proper* `CONECT` records
4. Create an OpenMM `system` of the PDB topology and list of `oechem.OEMol`s with (`ff = ForceField()` for `smirnoff99Frosst.ffxml`)
5. Use ParmEd to save the `system` as a `prmtop` and `inpcrd`

Steps 0-3 are working, but when I try to generate an OpenMM `system` from the `pdb.topology` and `mols`, I get an error `Exception: Error: Reference molecule must have unique atom names in order to create a Topology.` Is this because the host (cyclodextrin) has multiple copies of the same residue (and thus, multiple copies of the same atom name)? (I have yet to check if I get the same error with a different host.) I'll try a few other things over the weekend, but in the meantime, [here](https://github.com/slochower/openforcefield/blob/74a502d475f45a7e3bee812b6a85d499cd0816a5/examples/host_guest_simulation/cyclodextrin-but.ipynb) is a link to the notebook with my work and the relevant (starting and generated) files are [here](https://github.com/slochower/openforcefield/tree/74a502d475f45a7e3bee812b6a85d499cd0816a5/examples/host_guest_simulation/bcd-ben).

**Comment by nhenriksen** [comment]
> it's basically a problem with the files deposited there, or at least, they don't play nice with the rest of our tools. Specifically, the residue names are not used properly in the host mol2 files there in many cases

@davidlmobley can you be a little more specific here? Would it be preferred to have a mol2 just for each unique residue, rather than the whole host molecule?

> (It's worth noting that some of the hosts also have a residue number other than 1, which is incorrect since they only have one residue!)

Really? other than the cyclodextrins?

**Comment by slochower** [comment]
> we basically need to re-generate the host & guest mol2 files from scratch, I think.

Do you mean from, e.g., SMILES strings as I’m the existing host-guest example?

> Do you mind opening up an issue on benchmarksets cross-linking to this comment, so we don't lose it? I'm swamped for several days yet so I can't look at it right away. LMK if you or Niel have interest.

Will do. Niel and I can try some things and get back to you.

**Comment by slochower** [comment]
I agree with your last point and I’ll make a note of remembering that OpenEye follows the specifications and can be used as an arbiter. I will try adding the host atoms and then perceiving the connectivity, similar to how we’ve dealt with water, and report back.

**Comment by slochower** [comment]
I tried to go through an `xyz` file, as suggested, and that seems to get past the first hurdle of setting up the OpenMM system, but then ParmEd chokes on writing the `prmtop` file, in a section where it loops through the bonds. The current notebook is [here](https://github.com/slochower/openforcefield/blob/c4085e605b425bbbfd81b3559d606f74b5a94966/examples/host_guest_simulation/cyclodextrin-but.ipynb). I'll do a little more digging to see if `OEDetermineConnectivity` and `OEPerceiveBondOrders` is working properly.

**Comment by davidlmobley** [comment]
Please let me know, @slochower . I can dig into this relatively soon (tomorrow or next week sometime) if you're still having issues.

I believe the new Topology object we're creating will also solve a lot of the problems you're having. 

How exactly does ParmEd choke? This is after you make your final system and it chokes when you attempt to convert to AMBER format? What's the issue?

**Comment by davidlmobley** [comment]
(Would you mind spinning this off into a separate issue so I don't lose it?)

**Comment by davidlmobley** [comment]
That's definitely an odd one. It looks like it might be a ParmEd bug, in the sense that we should get an exception here if we don't have a parameter assigned to a particular bond. And if we do have them assigned to all bonds, then ParmEd SHOULD be able to convert to AMBER format I believe. 

If you're feeling ambitious, you could loop over all the bonds in the OpenMM `System` and make sure they have parameters assigned to them, and then if they do, raise an issue on ParmEd. Otherwise I should do this once I un-bury a little.

**Comment by slochower** [comment]
> If you're feeling ambitious, you could loop over all the bonds in the OpenMM System and make sure they have parameters assigned to them, and then if they do, raise an issue on ParmEd. 

I did a little poking around to see if any atoms have zero bonds connected to them, and only the ions pop up. So that's good. I'm not sure what other steps to take for debugging. I filed a ParmEd issue and I'm waiting to hear back if there are other obvious steps to take.

**Comment by davidlmobley** [comment]
Thanks, @slochower .
