### ISSUE TITLE
Expose Force Field Aromaticity Model

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#663]
**Is your feature request related to a problem? Please describe.**
The aromaticity model used by a force field can currently only be set and not accessed.

**Describe the solution you'd like**
Add a getter for a force fields aromaticity model.

**Describe alternatives you've considered**
Assume MDL, but this is not particularly future proof.

**Comment by j-wags** [comment]
Closed by #665
