### ISSUE TITLE
conformation generating under RDkit is not thread safe

### ISSUE THREAD

**Issue by trevorgokey** [openforcefield/openforcefield#671]
**Describe the bug**
Trying to compute partial charges using a parallel script/workflow fails using RDkit, since under the hood it is calling 
`sqm -i sqm.in -o sqm.out` in the current directory. This fails since multiple `sqm` processes are trying to read/write the same file.

**To Reproduce**
Run a partial charge (RDkit only; OE seems to handle file I/O internally) on two different molecules, in the same directory, at the same time.

**Comment by mattwthompson** [comment]
The temporary directory managers ([here](https://github.com/openforcefield/openforcefield/blob/6426b42a3970709f49314e05cbc21e27604e22fc/openforcefield/utils/toolkits.py#L4143-L4144) or [here](https://github.com/openforcefield/openforcefield/blob/6426b42a3970709f49314e05cbc21e27604e22fc/openforcefield/utils/toolkits.py#L3903-L3904)) should ensure the `sqm` calls happen on different files in different directories

**Comment by trevorgokey** [comment]
Interesting, I unknowingly did nearly exactly the same thing. I'll close for now until I can find something that is more concrete and repeatable.
