### ISSUE TITLE
Have toolkit wrappers know version of the toolkit they're wrapping

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield#674]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, `Toolkitwrapper` and therefore `ToolkitRegistry` objects don't know the version of the toolkit that they're wrapping. Would these be useful features?

**Describe the solution you'd like**

* When instantiating a wrapper class, the version detected from the wrapped toolkit is saved
* Each wrapper knows the class, and registries can also query that for each wrapper

Something like 
```python3

In [1]: from openforcefield.utils.toolkits import *

In [2]: reg = ToolkitRegistry(toolkit_precedence=[OpenEyeToolkitWrapper, RDKitToolkitWrapper, AmberToolsToolkitWrapper])

In [3]: # OpenEyeToolkitWrapper().wrapped_version() would return '2020.0.4'

In [4]: # RDKitToolkitWrapper().wrapped_version() would return '2020.03.4'

In [5]: # reg.wrapped_versions() would return something like ['2020.0.4', '2020.03.04', 'whatever_ambertools_says']
```
**Describe alternatives you've considered**
It's easy to enough to just import each of them and check their versions, but this would provide a single interface to them. It may also help debugging weird behavior, i.e. if the wrapper finds a different version than they think they have installed through `conda list`; this would directly store what the wrapper finds.

**Additional context**
This is motivated by writing a CLI, in which I think it would be useful to be able to access the versions of installed toolkits by only passing around a `ToolkitRegistry` object

**Comment by j-wags** [comment]
Ooh, that would be super handy. The only change I'd suggest it to make `reg.wrappped_versions` return a dict of `{'OpenEyeToolkitWrapper': '2020.0.4', ...}`, so that users know which version corresponds to which toolkit. 

I think something like this was desirable for QCSubmit's operation provenance, where if QCSubmit, for example, ran `Molecule.generate_conformers(provenance=True)`, part of the return value would be the toolkit(s) that were used and their versions. So this would be a great step towards finally implementing that.

**Comment by mattwthompson** [comment]
I don't think anything in the original post is missed. This is from the 0.8.0 tag:

```
In [1]: from openforcefield.utils.toolkits import *

In [2]: reg = ToolkitRegistry(toolkit_precedence=[OpenEyeToolkitWrapper, RDKitToolkitWrapper, AmberToolsToolkitWrapper])
   ...:

In [3]: OpenEyeToolkitWrapper().toolkit_version
Out[3]: '2020.1.0'

In [4]: RDKitToolkitWrapper().toolkit_version
Out[4]: '2020.09.1'

In [5]: reg.registered_toolkit_versions
Out[5]: {'OpenEye Toolkit': '2020.1.0', 'The RDKit': '2020.09.1', 'AmberTools': '20.0'}
```
