### ISSUE TITLE
Write residue template XML

### ISSUE THREAD

**Issue by djhuggins** [openforcefield/openforcefield#676]
Hello,

Please can I request a feature that allows a user to write out a residue template as an XML file to allow parameters to be checked and compared? All the information should already be available.

Thanks,

Dave

**Comment by j-wags** [comment]
I second this feature request. Having a general way to write out residue templates may also unblock our CHARMM-GUI integration efforts, which require residue template writers as well. 

It's likely that [openmmforcefields](https://github.com/openmm/openmmforcefields) would be the most natural home for this functionality, but I'm happy to host discussion here since the big blocking developments would be in the OFF Toolkit.

**Comment by mattwthompson** [comment]
I could take this on if it's specced out in a little more detail (I am only familiar with residue templates in the general sense, having not used them myself). Are these files written from a larger force field (i.e. `ForceField` object) or a parametrized system?

**Comment by j-wags** [comment]
In fact, maybe [openmmforcefields.SMIRNOFFTemplateGenerator.generate_residue_template](https://github.com/openmm/openmmforcefields/blob/master/openmmforcefields/generators/template_generators.py#L1112-L1303) implements exactly the desired feature?

Could you try this and report whether it covers your use case, @djhuggins? `openmmforcefields` should be conda-installable from omnia.

**Comment by djhuggins** [comment]
Hi there,

Thanks. Yes I can write it as follows:

_# Load a molecule into the openforcefield Molecule object
from openforcefield.topology import Molecule
molecule = Molecule.from_file('molecule.sdf')

# Create an openforcefield Topology object from the molecule
from openforcefield.topology import Topology
topology = Topology.from_molecules(molecule)

#Import forcefield
from openforcefield.typing.engines.smirnoff import ForceField
force_field = ForceField('openff-1.2.0.offxml')

#Make residue template
from openmmforcefields.generators.template_generators import SMIRNOFFTemplateGenerator
template_generator = SMIRNOFFTemplateGenerator(molecules=molecule)
outffxml=template_generator.generate_residue_template(molecule)

#Write
with open('molecule.xml', 'w') as f:
    f.write(outffxml)_

The resulting atom types and classes are a bit difficult to pronounce, but openmm seems to accept them. 

Thanks,

Dave

**Comment by jchodera** [comment]
I think the `openmmforcefields` solution is a good stopgap measure, since this problem is something our new portable `System` container is meant to solve.

**Comment by j-wags** [comment]
Glad to hear this worked! I'll close this as resolved.
