### ISSUE TITLE
Problem generating proper topology using either ParmEd or PDBFile

### ISSUE THREAD

**Issue by slochower** [openforcefield/openforcefield#68]
I'm trying to go from AMBER formatted file to `OEMol`s and topology. I've figured out how to get to the `OEMol`s using PDB as an intermediate format. However, I'm still having issues with the topology. I'm using the GitHub release of `openforcefield` (reporting version 0.0.3 through `pip`). I think this gist summarizes the issue:
https://nbviewer.jupyter.org/gist/slochower/d319634570c45cb8a5c1bb7916fc5456

**Comment by bannanc** [comment]
Could you provide the three `full.*` files?

**Comment by slochower** [comment]
Oops, sure! You can access `full.topo` and `full.crds` here: https://github.com/slochower/pAPRika/tree/master/test/cb6-but But just for good measure, don't use the `full.pdb` there, use the one that ParmEd writes (inside the `try` loop) so you have the same exact setup as me.

**Comment by jchodera** [comment]
To be clear here: You're starting with *only* AMBER `prmtop, inpcrd` files? Which already have AMBER parameters assigned? And instead want to assign SMIRNOFF parameters?

How did you generate those `prmtop/inpcrd` files in the first place?

**Comment by jchodera** [comment]
Workflows for generating `prmtop/inpcrd` files via LEaP almost universally involve starting with Tripos-format `mol2` files. Do you still have those around, or has all provenance for the origin of these `prmtop/inpcrd` pairs been lost (and, if so, why are you using them)?

**Comment by slochower** [comment]
> To be clear here: You're starting with only AMBER prmtop, inpcrd files? Which already have AMBER parameters assigned? And instead want to assign SMIRNOFF parameters?

Yup.

**Comment by slochower** [comment]
> Do you still have those around, or has all provenance for the origin of these prmtop/inpcrd pairs been lost (and, if so, why are you using them)?

Starting in that directory are separate starting `mol2` files for the host (`cb6.mol2`) and guest (`but.mol2`). My goal was to have the same exact starting configuration for AMBER and OpenMM/SMIRNOFF. So it seemed like a good idea to prepare the complex once, and then use the combined files to convert from AMBER to SMIRNOFF.

**Comment by jchodera** [comment]
> My goal was to have the same exact starting configuration for AMBER and OpenMM/SMIRNOFF.

Oh! That should be easy. Here's what I would do:
1. Load the Tripos `mol2` files `cb6.mol2` and `but.mol2` into `OEMol`s and use these as the `mols` fed to `createSystem()`.
2. Use `ambpdb` to generate a PDB file from your AMBER `prmtop/inpcrd` that contains `CONECT` records; alternatively, I *think* you can get the `Topology` and `positions` from ParmEd's structure, as you do in Method 1.
3. Use the PDB-derived `Topology` (which matches your PDB-derived `positions`) and the Tripos mol2-derived `OEMol`s in the call to `createSystem()`. Remember, the key here is that the `Topology` must contain connectivity information for the small molecules, which requires starting with a PDB format compliant PDB file (requiring `CONECT` records for anything but standard residues) if you use `simtk.openmm.app.PDBFile` to load the PDB file.

**Comment by bannanc** [comment]
@slochower 
I think John's suggestion should work, could you try that? Feel free to ping me if you need help.

**Comment by slochower** [comment]
Sure, I can give that a shot, although I think I'll lose the hydration unless there's something I'm missing. The thing that `full*` files contain that `cb6.mol2` and `but.mol2` don't is a solvation box.

**Comment by jchodera** [comment]
> Sure, I can give that a shot, although I think I'll lose the hydration unless there's something I'm missing. The thing that full* files contain that cb6.mol2 and but.mol2 don't is a solvation box.

The `prmtop/inpcrd` files have waters in them, right? Converting to a PDB file will *also* retain the waters, though you will need to also include the SMIRNOFF [`tip3p.ffxml`](https://github.com/open-forcefield-group/openforcefield/blob/2ed86d610e5abdcbe06a5d72ea9c2a4b4712468a/openforcefield/data/forcefield/tip3p.ffxml) file.

**Comment by slochower** [comment]
> The prmtop/inpcrd files have waters in them, right? Converting to a PDB file will also retain the waters...

Ah, right, but I don't need an `OEMol` for the waters too?

**Comment by jchodera** [comment]
> Ah, right, but I don't need an OEMol for the waters too?

Good point! Yes, you'll need to include one `OEMol` for a water molecule which includes TIP3P partial charges. The [`tip3p.ffxml`](https://github.com/open-forcefield-group/openforcefield/blob/2ed86d610e5abdcbe06a5d72ea9c2a4b4712468a/openforcefield/data/forcefield/tip3p.ffxml) file has charge overrides specified, but it looks like we [haven't implemented charge overrides yet](https://github.com/open-forcefield-group/openforcefield/issues/34).

**Comment by slochower** [comment]
Okay great. I will report back in a few hours.

**Comment by davidlmobley** [comment]
@slochower - regarding the water, that's why I was pointing you to my example Jupyter notebook for host-guest systems, as it explicitly loads a reference OEMol corresponding to TIP3P water from a mol2 file, if I remember correctly.

**Comment by bannanc** [comment]
Thanks for the help @jchodera! 
I'll be working tomorrow @slochower if you need me to look at anything just tag me here or on Slack.

**Comment by slochower** [comment]
I can load in a separate `mol2` for water but I'm still getting an issue with `No provided molecule matches topology molecule`.

Here, I'm loading separate TRIPOS `mol2` files:
```python
mols = []
ifs = oechem.oemolistream('../test/cb6-but/cb6.sybyl.mol2')
for mol in ifs.GetOEGraphMols():
    mols.append(oechem.OEMol(mol))
ifs = oechem.oemolistream('../test/cb6-but/but.sybyl.mol2')
for mol in ifs.GetOEGraphMols():
    mols.append(oechem.OEMol(mol))
ifs = oechem.oemolistream('tip3p.mol2')
for mol in ifs.GetOEGraphMols():
    mols.append(oechem.OEMol(mol))
```

Then I load in the PDB of the whole system generated by `ambpdb`:
```python
pdb = PDBFile('full.ambpdb.pdb')
```
...and `pdb.topology` looks good.

But I still fail at
```python
system = ff.createSystem(pdb.topology, 
                         mols, 
                         nonbondedMethod = PME, 
                         nonbondedCutoff=1.1*unit.nanometer, 
                         ewaldErrorTolerance=1e-4)  #, constraints=smirnoff.HBonds)
```
...with...
```
 Untitled Last Checkpoint: a minute ago (unsaved changes) [Python 3]

Python 3

    File
    Edit
    View
    Insert
    Cell
    Kernel
    Widgets
    Help

OpenFF tests (continued)

Trying AMBER (coordinates and topology) → PDB → OEMol → OpenMM topology (either through ParmEd or PDBFile) → ff.createSystem(topology, OEMol, ...)

import oenotebook as oenb

from openeye import oechem

from oeommtools import utils as oeommutils 

​

from simtk import unit

from simtk.openmm import app

from simtk.openmm.app import PDBFile

​

from openforcefield.typing.engines.smirnoff import *

​

import parmed as pmd

!pip show openforcefield

Name: openforcefield
Version: 0.0.3
Summary: Open Force Field Group tools
Home-page: http://github.com/open-forcefield-group/openforcefield
Author: John Chodera, David Mobley, and others
Author-email: john.chodera@choderalab.org
License: MIT
Location: /home/dslochower/hgst-3tb-data/projects/openforcefield/openforcefield
Requires: 

Import the AMBER files and write a PDB (if necessary) as an intermediate format.

We can either get the topology through this Structure instance or try using PDBFile
Method 1

structure = pmd.load_file('../test/cb6-but/full.topo', '../test/cb6-but/full.crds')

try:

    structure.save('full.pdb')

except:

    pass

structure.topology

<Topology; 1 chains, 1441 residues, 4439 atoms, 4456 bonds>

Method 2

pdb = PDBFile('full.pdb')

pdb.topology

<Topology; 1 chains, 1441 residues, 4439 atoms, 2878 bonds>

OpenEye tools have trouble drawing the structure, but it looks good in Chimera.
Read in the PDB and convert to OEMols.

ifs = oechem.oemolistream('full.pdb')

mols = []

for mol in ifs.GetOEGraphMols():

    mols.append(oechem.OEMol(mol))

Split the list of OEMols into separate objects.

output_ligands = oechem.OEMol()

output_protein = oechem.OEMol()

output_waters = oechem.OEMol()

output_others = oechem.OEMol()

oechem.OESplitMolComplex(output_ligands, output_protein, output_waters, output_others, mols[0])

True

output_protein

OEMol: C1N2C3C4N(C2=O)CN5C6C7N(C5=O)CN8C9C2N(C8... CB6

output_ligands

OEMol: CCCC BUT

output_waters

OEMol: O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.... WAT

ofs = oechem.oemolostream()

ofs.open('tip3p.mol2')

oechem.OEWriteMolecule(ofs, output_waters)

ofs.close()

Recombine them into a list that can be passed to ff.createSystem() down the line.

mols = [output_protein, output_ligands, output_waters]

Process all the OEMols using the relevant OpenEye tools.

I could be missing some things here.

for mol in mols:

​

    oechem.OEAddExplicitHydrogens(mol)

    oechem.OETriposAtomNames(mol)

    oechem.OEPerceiveBondOrders(mol)

    oechem.OEAssignAromaticFlags(mol)

​

    title = mol.GetTitle()

    if not title:

        title = "Untitled"

    print ("%s %.3f %d %d %d %d %d" %

      (title,

       oechem.OECalculateMolecularWeight(mol),

       mol.NumAtoms(),

       oechem.OECount(mol, oechem.OEIsHeavy()),

       oechem.OECount(mol, oechem.OEAtomIsInRing()),

       oechem.OECount(mol, oechem.OEIsRotor()),

       mol.NumConfs()

       ))

CB6 996.825 108 72 60 0 1
BUT 58.122 14 4 0 1 1
WAT 1315.115 219 73 0 0 1

Try ff.createSystem with topology from method #1

ff = ForceField('forcefield/smirnoff99Frosst.ffxml') 

mols = []

mols.append(mol)

system = ff.createSystem(structure.topology, 

                         mols, 

                         nonbondedMethod = PME, 

                         nonbondedCutoff=1.1*unit.nanometer, 

                         ewaldErrorTolerance=1e-4)  #, constraints=smirnoff.HBonds)

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-33-ec49978336ae> in <module>()
      6                          nonbondedMethod = PME,
      7                          nonbondedCutoff=1.1*unit.nanometer,
----> 8                          ewaldErrorTolerance=1e-4)  #, constraints=smirnoff.HBonds)

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in createSystem(self, topology, molecules, nonbondedMethod, nonbondedCutoff, constraints, rigidWater, removeCMMotion, hydrogenMass, residueTemplates, chargeMethod, verbose, **kwargs)
    967 
    968         # Work with a modified form of the topology that provides additional accessors.
--> 969         topology = _Topology(topology, molecules)
    970 
    971         # If the charge method was not an OpenEye AM1 method and we need Wiberg bond orders, obtain Wiberg bond orders

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in __init__(self, topology, reference_molecules)
    193 
    194         # Identify all molecules and atom mappings.
--> 195         self._identifyMolecules()
    196 
    197         # Get/initialize bond orders

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in _identifyMolecules(self)
    371                 for index in sorted(list(molecule_graph)):
    372                     msg += 'Atom %8d %5s %5d %3s\n' % (atoms[index].index, atoms[index].name, atoms[index].residue.index, atoms[index].residue.name)
--> 373                 raise Exception(msg)
    374 
    375     def _updateBondOrders(self, Wiberg = False):

Exception: No provided molecule matches topology molecule:
Atom        0     C     0 CB6
Atom        1    C1     0 CB6
Atom        2     N     0 CB6
Atom        3    N1     0 CB6
Atom        4     H     0 CB6
Atom        5    H1     0 CB6
Atom        6    N2     0 CB6
Atom        7    N3     0 CB6
Atom        8    C2     0 CB6
Atom        9    C3     0 CB6
Atom       10    C4     0 CB6
Atom       11    C5     0 CB6
Atom       12     O     0 CB6
Atom       13    O1     0 CB6
Atom       14    H2     0 CB6
Atom       15    H3     0 CB6
Atom       16    H4     0 CB6
Atom       17    H5     0 CB6
Atom       18    C6     0 CB6
Atom       19    C7     0 CB6
Atom       20    N4     0 CB6
Atom       21    N5     0 CB6
Atom       22    H6     0 CB6
Atom       23    H7     0 CB6
Atom       24    N6     0 CB6
Atom       25    N7     0 CB6
Atom       26    C8     0 CB6
Atom       27    C9     0 CB6
Atom       28   C10     0 CB6
Atom       29   C11     0 CB6
Atom       30    O2     0 CB6
Atom       31    O3     0 CB6
Atom       32    H8     0 CB6
Atom       33    H9     0 CB6
Atom       34   H10     0 CB6
Atom       35   H11     0 CB6
Atom       36   C12     0 CB6
Atom       37   C13     0 CB6
Atom       38    N8     0 CB6
Atom       39    N9     0 CB6
Atom       40   H12     0 CB6
Atom       41   H13     0 CB6
Atom       42   N10     0 CB6
Atom       43   N11     0 CB6
Atom       44   C14     0 CB6
Atom       45   C15     0 CB6
Atom       46   C16     0 CB6
Atom       47   C17     0 CB6
Atom       48    O4     0 CB6
Atom       49    O5     0 CB6
Atom       50   H14     0 CB6
Atom       51   H15     0 CB6
Atom       52   H16     0 CB6
Atom       53   H17     0 CB6
Atom       54   C18     0 CB6
Atom       55   C19     0 CB6
Atom       56   N12     0 CB6
Atom       57   N13     0 CB6
Atom       58   H18     0 CB6
Atom       59   H19     0 CB6
Atom       60   N14     0 CB6
Atom       61   N15     0 CB6
Atom       62   C20     0 CB6
Atom       63   C21     0 CB6
Atom       64   C22     0 CB6
Atom       65   C23     0 CB6
Atom       66    O6     0 CB6
Atom       67    O7     0 CB6
Atom       68   H20     0 CB6
Atom       69   H21     0 CB6
Atom       70   H22     0 CB6
Atom       71   H23     0 CB6
Atom       72   C24     0 CB6
Atom       73   C25     0 CB6
Atom       74   N16     0 CB6
Atom       75   N17     0 CB6
Atom       76   H24     0 CB6
Atom       77   H25     0 CB6
Atom       78   N18     0 CB6
Atom       79   N19     0 CB6
Atom       80   C26     0 CB6
Atom       81   C27     0 CB6
Atom       82   C28     0 CB6
Atom       83   C29     0 CB6
Atom       84    O8     0 CB6
Atom       85    O9     0 CB6
Atom       86   H26     0 CB6
Atom       87   H27     0 CB6
Atom       88   H28     0 CB6
Atom       89   H29     0 CB6
Atom       90   C30     0 CB6
Atom       91   C31     0 CB6
Atom       92   N20     0 CB6
Atom       93   N21     0 CB6
Atom       94   H30     0 CB6
Atom       95   H31     0 CB6
Atom       96   N22     0 CB6
Atom       97   N23     0 CB6
Atom       98   C32     0 CB6
Atom       99   C33     0 CB6
Atom      100   C34     0 CB6
Atom      101   C35     0 CB6
Atom      102   O10     0 CB6
Atom      103   O11     0 CB6
Atom      104   H32     0 CB6
Atom      105   H33     0 CB6
Atom      106   H34     0 CB6
Atom      107   H35     0 CB6


Try ff.createSystem with topology from method #2

ff = ForceField('forcefield/smirnoff99Frosst.ffxml') 

mols = []

mols.append(mol)

system = ff.createSystem(pdb.topology, 

                         mols, 

                         nonbondedMethod = PME, 

                         nonbondedCutoff=1.1*unit.nanometer, 

                         ewaldErrorTolerance=1e-4)  #, constraints=smirnoff.HBonds)

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-35-b1afeb4fe796> in <module>()
      6                          nonbondedMethod = PME,
      7                          nonbondedCutoff=1.1*unit.nanometer,
----> 8                          ewaldErrorTolerance=1e-4)  #, constraints=smirnoff.HBonds)

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in createSystem(self, topology, molecules, nonbondedMethod, nonbondedCutoff, constraints, rigidWater, removeCMMotion, hydrogenMass, residueTemplates, chargeMethod, verbose, **kwargs)
    967 
    968         # Work with a modified form of the topology that provides additional accessors.
--> 969         topology = _Topology(topology, molecules)
    970 
    971         # If the charge method was not an OpenEye AM1 method and we need Wiberg bond orders, obtain Wiberg bond orders

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in __init__(self, topology, reference_molecules)
    193 
    194         # Identify all molecules and atom mappings.
--> 195         self._identifyMolecules()
    196 
    197         # Get/initialize bond orders

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in _identifyMolecules(self)
    371                 for index in sorted(list(molecule_graph)):
    372                     msg += 'Atom %8d %5s %5d %3s\n' % (atoms[index].index, atoms[index].name, atoms[index].residue.index, atoms[index].residue.name)
--> 373                 raise Exception(msg)
    374 
    375     def _updateBondOrders(self, Wiberg = False):

Exception: No provided molecule matches topology molecule:
Atom        0     C     0 CB6


Try loading separate TIPOS mol2 files and then using ambpdb to read in a PDB file of the full system

mols = []

ifs = oechem.oemolistream('../test/cb6-but/cb6.sybyl.mol2')

for mol in ifs.GetOEGraphMols():

    mols.append(oechem.OEMol(mol))

ifs = oechem.oemolistream('../test/cb6-but/but.sybyl.mol2')

for mol in ifs.GetOEGraphMols():

    mols.append(oechem.OEMol(mol))

ifs = oechem.oemolistream('tip3p.mol2')

for mol in ifs.GetOEGraphMols():

    mols.append(oechem.OEMol(mol))

mols

[<'oechem.OEMol' CB6 C1N2C3C4N(C2=O)CN5C6C7N(C5=O)CN8C9C2N(C8...  >,
 <'oechem.OEMol' BUT CCCC >,
 <'oechem.OEMol' WAT O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O....  >]

$AMBERHOME/bin/ambpdb -p ../test/cb6-but/full.topo -c ../test/cb6-but/full.crds > full.ambpdb.pdb

pdb = PDBFile('full.ambpdb.pdb')

pdb.topology

<Topology; 3 chains, 1441 residues, 4439 atoms, 2878 bonds>

system = ff.createSystem(pdb.topology, 

                         mols, 

                         nonbondedMethod = PME, 

                         nonbondedCutoff=1.1*unit.nanometer, 

                         ewaldErrorTolerance=1e-4)  #, constraints=smirnoff.HBonds)

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-49-5a375586e816> in <module>()
      3                          nonbondedMethod = PME,
      4                          nonbondedCutoff=1.1*unit.nanometer,
----> 5                          ewaldErrorTolerance=1e-4)  #, constraints=smirnoff.HBonds)

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in createSystem(self, topology, molecules, nonbondedMethod, nonbondedCutoff, constraints, rigidWater, removeCMMotion, hydrogenMass, residueTemplates, chargeMethod, verbose, **kwargs)
    967 
    968         # Work with a modified form of the topology that provides additional accessors.
--> 969         topology = _Topology(topology, molecules)
    970 
    971         # If the charge method was not an OpenEye AM1 method and we need Wiberg bond orders, obtain Wiberg bond orders

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in __init__(self, topology, reference_molecules)
    193 
    194         # Identify all molecules and atom mappings.
--> 195         self._identifyMolecules()
    196 
    197         # Get/initialize bond orders

~/hgst-3tb-data/projects/openforcefield/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py in _identifyMolecules(self)
    371                 for index in sorted(list(molecule_graph)):
    372                     msg += 'Atom %8d %5s %5d %3s\n' % (atoms[index].index, atoms[index].name, atoms[index].residue.index, atoms[index].residue.name)
--> 373                 raise Exception(msg)
    374 
    375     def _updateBondOrders(self, Wiberg = False):

Exception: No provided molecule matches topology molecule:
Atom        0     C     0 CB6
```

**Comment by slochower** [comment]
FWIW, the PDB does not have `CONNECT` records, but I'm not sure that it should? Maybe @jchodera knows. The host is a single residue and the guest is a single residue with `TER` between them.

**Comment by jchodera** [comment]
Can you point to the `full.ambpdb.pdb` file?

**Comment by jchodera** [comment]
This version of [`full.pdb`](https://github.com/slochower/pAPRika/blob/master/test/cb6-but/full.pdb), for example, contains nonstandard residues (`CB6` and `BUT`) that do not have `CONECT` records, which is a violation of the [PDB format specification](http://www.bmsc.washington.edu/CrystaLinks/man/pdb/part_69.html). Loading that file into `simtk.openmm.app.PDBFile()` would produce a `Topology` with no bonds connecting host and guest atoms into actual molecules. 

It looks like the same thing must be going on here since it thinks your input `Topology` starts with a molecule consisting of a single atom:
```
Exception: No provided molecule matches topology molecule:
Atom        0     C     0 CB6
```
Your bond information is being lost somehow.

We should probably put in a more useful error message to "Check that your `Topology` actually contains bonds" if there are failing molecules with single non-ion atoms.

**Comment by slochower** [comment]
Here is a link to the full.ambpdb.pdb file: https://gist.github.com/slochower/4b2ca9d88bc776f96350fdd584e388c3 It does now have `CONECT` records, but `createSystem` is choking on the second water molecule. I've manually added the water `OEMol` as @davidlmobley suggested, by doing this: 
```python
mol = oechem.OEMol()
oechem.OESmilesToMol(mol, 'O')
oechem.OEAddExplicitHydrogens(mol)
oechem.OETriposAtomNames(mol)
mols.append(mol)
```
So my list `mols` is:
```python
[<'oechem.OEMol' CB6 C1N2C3C4N(C2=O)CN5C6C7N(C5=O)CN8C9C2N(C8...  >,
 <'oechem.OEMol' BUT CCCC >,
 <'oechem.OEMol'  O >]
```
The exception I'm getting starts at water residue 2:
```python
Exception: No provided molecule matches topology molecule:
Atom      122     O     2 HOH
Atom      123    H1     2 HOH
Atom      124    H2     2 HOH
```

**Comment by jchodera** [comment]
That file can't be the PDB file you're loading in, can it? Your PDB file has residues named `WAT`, but your exception is saying the `Topology` object has water residues named `HOH`.

**Comment by slochower** [comment]
That is definitely what I'm loading in, but maybe there's a difference between the residue name that `OEMol` builds in the topology and the residue name in the coordinates from the PDB?

**Comment by jchodera** [comment]
You're right. It looks like `PDBFile` is turning the `WAT` into `HOH` residues, which is surprising:
```
>>> from simtk import openmm
>>> from simtk.openmm import app
>>> t = app.PDBFile('full.ambpdb.pdb')
>>> residues = [r.name for r in t.topology.residues()]
>>> print(residues)
['CB6', 'BUT', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH', 'HOH',
...
```
That's not the problem, but it might also be forgetting to add in bonds. Just a moment.

**Comment by jchodera** [comment]
The bonds are definitely there, but the issue seems to be that there's an *extra* bond between `H1` and `H2` that doesn't appear in the `ffxml` definition of the residue:
```
>>> residues = [r for r in t.topology.residues()]
>>> print([b for b in residues[2].bonds()])
[Bond(<Atom 123 (H1) of chain 2 residue 2 (HOH)>, <Atom 122 (O) of chain 2 residue 2 (HOH)>), Bond(<Atom 124 (H2) of chain 2 residue 2 (HOH)>, <Atom 122 (O) of chain 2 residue 2 (HOH)>), Bond(<Atom 123 (H1) of chain 2 residue 2 (HOH)>, <Atom 124 (H2) of chain 2 residue 2 (HOH)>)]
>>> print([b for b in residues[3].bonds()])
[Bond(<Atom 126 (H1) of chain 2 residue 3 (HOH)>, <Atom 125 (O) of chain 2 residue 3 (HOH)>), Bond(<Atom 127 (H2) of chain 2 residue 3 (HOH)>, <Atom 125 (O) of chain 2 residue 3 (HOH)>), Bond(<Atom 126 (H1) of chain 2 residue 3 (HOH)>, <Atom 127 (H2) of chain 2 residue 3 (HOH)>)]
```
If I recall correctly, this is why @andrrizzi and @davidlmobley added the waters separately.

We can work around this, but I first need to figure out whether PDBFile should really be adding the `H1-H2` bonds.

**Comment by jchodera** [comment]
> That is definitely what I'm loading in, but maybe there's a difference between the residue name that OEMol builds in the topology and the residue name in the coordinates from the PDB?

The residue names aren't actually used by the forcefield assignment engine---I was just surprised that it was changing the names.

**Comment by slochower** [comment]
I see. For clarification, here is the simplified gist of the workflow.
https://nbviewer.jupyter.org/gist/slochower/fe66db617d0bbd91e24bb4573e78ac7a

**Comment by jchodera** [comment]
Oh, it's `ambpdb` that's adding `CONECT` residues between `H1-H2`. Your PDB file has:
```
CONECT 4437 4438 4439
CONECT 4438 4437 4439
CONECT 4439 4437 4438
```
It shouldn't be doing that.

For now, just delete all the `CONECT` residues involving waters and rename the waters to `HOH`. `PDBFile()` will add the right connectivity for `HOH`.

We'll need to figure out a better way to do this in the future.

**Comment by slochower** [comment]
Ah! Yes! No more errors from `createSystem`!

**Comment by davidlmobley** [comment]
Glad you guys got this sorted (and thanks for the help, @jchodera ). As I was telling David yesterday, so many of our problems result from tools violating file format specifications. This is yet another example...

**Comment by jchodera** [comment]
A good philosophy is to be lax in reading, strict in writing, so we may want to see how we can build in some tools to "fix" problematic files or `Topology` objects involving common molecules like water.

**Comment by jchodera** [comment]
Also, screw PDB files.

**Comment by davidlmobley** [comment]
Maybe we should just strip all bonds involving water and re-infer them, since these are frequently problematic.

**Comment by jchodera** [comment]
We can definitely interpose a step to fix-or-flag nonsensical molecules (monoatomic molecules that are not ions, waters with wacky bonds, etc.). 

The question is: Where should this go? Should it be an explicit step that examines the `Topology` object, like
```python
from openforcefield.typing.helpers import ChemistryFixer
fixed_topology = ChemistryFixer(topology)
...
```
or would it happen transparently in `ForceField`?

**Comment by davidlmobley** [comment]
*Not* transparently; see also #61 (changed title of that just slightly now to broaden it). 

Chris Bayly and I have the perspective that ForceField should not AUTOMATICALLY do any prep on your molecules/Topologies and should assume they are well-formed. For use by industry as part of exsiting workflows and on Orion/automated workflow platforms this is critical -- if anything is messing with your molecules without you knowing it, it can cause the whole thing to do something totally different from what you intend.

What we instead should do is provide utility functionality to check/prepare/assist with input Topologies/OEMols to make sure they are ready to go, so that users who are NOT coming in with already prepared molecules and clean chemistry can get going easily.

**Comment by davidlmobley** [comment]
See e.g. https://github.com/open-forcefield-group/openforcefield/issues/61#issuecomment-330691056

**Comment by jchodera** [comment]
Let's consolidate this discussion in #78.
