### ISSUE TITLE
ParameterType objects "have" all optional attributes, even when None

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield#702]
**Describe the bug**
I don't think `hasattr(param, opt_attr)` should return `True` when an optional attribute `opt_attr` is `None` in the object.

**To Reproduce**
```python3
openforcefield.typing.engines.smirnoff.parameters import *
from simtk import unit


# Initialize an parameter with an `id` but no `parent_id` 
param = BondHandler.BondType(
    smirks="[*:1]-[*:2]",
    length=1 * unit.angstrom,
    k=1 * unit.kilocalorie_per_mole / unit.angstrom ** 2,
    id="4",
)

for opt_attr in param._get_optional_parameter_attributes().keys():
    print("param:", opt_attr)
    print("val:", getattr(param, opt_attr))
    print(f"hasattr: {hasattr(param, opt_attr)}\n")
```

**Output**
```
param: id
val: 4
hasattr: True

param: parent_id
val: None
hasattr: True  # Should it, though?
```

**Additional context**
This may seem trivial for ids since they don't have an impact on the parametrization, but it becomes relevant for bond order interpolation, in which you need to have _either_ `k` or `k_bondorder1`/`k_bondorder2`/etc. This is implemented by making each of these optional (see [here](https://github.com/openforcefield/openforcefield/blob/e8d89f8625b3faf9cafa302f5451da0a831ca1a4/openforcefield/typing/engines/smirnoff/parameters.py#L2569-L2575) as it's done with torsions) and then it becomes natural to ask [`if hasattr(bond_params, "k_bondorder1"):`](https://github.com/openforcefield/openforcefield/blob/e8d89f8625b3faf9cafa302f5451da0a831ca1a4/openforcefield/typing/engines/smirnoff/parameters.py#L2377)

It's often [suggested](https://hynek.me/articles/hasattr/) to use `getattr(obj, attr, None)` instead of `hasattr` for various reasons, largely relating to changes between Python 2 and 3. I'd prefer to go with that approach, but the above behavior is still strange and should be avoided.

**Comment by j-wags** [comment]
Oof. That's tricky. Two thoughts:

1) How will we distinguish between a positive assignment of a `None` value, like [here](https://github.com/openforcefield/openforcefields/blob/1.2.1/openforcefields/offxml/openff-1.2.1.offxml#L12), versus an "undefined" value, like a `k_bondorder1` for a non-interpolating bond?
2) Will we only have one option for how to handle this when we switch to a Pydantic object model? That should be our long-term guiding principle for this behavior.

**Comment by mattwthompson** [comment]
Not sure what was in my coffee last week, but I was mistaken from the top. I'm pretty sure that the best practice is to store everything, but things that are `None` are implied to be optional. Python doesn't prevent you from tacking on extra attributes after initialization, but that has a tendency to  produce weirdness, i.e. diverging from the class definition. The dead-simple approach looks like this

```python3
In [1]: from pydantic import BaseModel

In [2]: class FooModel(BaseModel):
   ...:     param = 1
   ...:     opt_param: str = None
   ...:

In [3]: foo = FooModel()

In [4]: hasattr(foo, 'opt_param')
Out[4]: True

In [5]: hasattr(FooModel(opt_param='am4', param=1), 'opt_param')
Out[5]: True

In [6]: hasattr(FooModel(param=1), 'opt_param')
Out[6]: True

In [7]: FooModel(param=1).opt_param is None
Out[7]: True

In [8]: FooModel(param=1, opt_param='am4').opt_param is None
Out[8]: False
```
The optional attribute is always "had," so there is no distinction between un-set and intentionally `None` attributes. I'm not sure that's a distinction we want to capture, however; I don't see the functional difference, and I think it may actually a symptom of the data model not being well-defined (or changing across versions). I don't see the downside of trying to force optional attributes to exist, but let them be `None` if they're not carrying any meaning. Happy to be persuaded with a counter-example.


The way to get around "what's `k_bondorder2` again?" is to store both:
```python3
In [1]: from typing import Dict, Optional

In [2]: from pydantic import BaseModel

In [3]: class Parameter(BaseModel):
   ...:     smirks: str
   ...:     k: Optional[float] = None
   ...:     k_bondorder: Optional[Dict[int, float]] = None

In [4]: bond = Parameter(smirks='', k=400)

In [5]: bond_wbo = Parameter(smirks='', k_bondorder={1: 200, 2: 1000})

In [6]: bond
Out[6]: Parameter(smirks='', k=400.0, k_bondorder=None)

In [7]: bond_wbo
Out[7]: Parameter(smirks='', k=None, k_bondorder={1: 200.0, 2: 1000.0})

In [8]: if bond.k is not None: print(bond.k)  # Here's your force constant, now you can keep going
400.0

In [9]: if bond_wbo.k_bondorder is not None: print(bond_wbo.k_bondorder)  # Proceed to interpolation logic
{1: 200.0, 2: 1000.0}
```
 This approach bypasses part of your first question, but is closer to the current representation as it stands, which either stores the force constant `k` as a quantity or the set of interpolated force constants `k_bondorder` as a dict; the other is set to `None`. It looks different in the XML files, but the first step is converting them to something that looks more like the above.

Looping back to the original question: I'm fine with `hasattr(param, opt_attr)` returning True and have resolved the issue I was facing earlier (in fact, @dotsdl built this all months ago, I just took some time to understand the solution).
