### ISSUE TITLE
Handler Internal Parameter Attributes Not Found

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openforcefield#733]
**Describe the bug**
The internal values of a parameter handlers attributes are not set until the attributes are first accessed (e.g. `_method` is not set for a `NonbondedForce` until `method` is accessed). This leads to `AttributeError` exceptions when creating forces from handlers created from scratch without accessing each of the attached attributes.

**To Reproduce**

```
# Create a dummy topology containing only argon and give it a set of
# box vectors.
topology = Molecule.from_smiles("[Ar]").to_topology()
topology.box_vectors = numpy.eye(3) * unit.nanometers

# Create the FF
force_field = ForceField()

# Add only a VdW handler.
vdw_handler = vdWHandler(version=0.3)
vdw_handler.add_parameter(
    {
        "smirks": "[#18:1]",
        "epsilon": 1.0 * unit.kilojoules_per_mole,
        "sigma": 1.0 * unit.angstrom
    }
)

force_field.register_parameter_handler(vdw_handler)

# Map the FF to the dummy topology
system = force_field.create_openmm_system(topology)
```

**Output**

```
Traceback (most recent call last):
  File "repro.py", line 37, in <module>
    main()
  File "repro.py", line 31, in main
    system = force_field.create_openmm_system(topology)
  File "/XXX/openforcefield/typing/engines/smirnoff/forcefield.py", line 1297, in create_openmm_system
    parameter_handler.create_force(system, topology, **kwargs)
  File "/XXX/openforcefield/typing/engines/smirnoff/parameters.py", line 3217, in create_force
    if self._method == "PME":
  File "/XXX/openforcefield/typing/engines/smirnoff/parameters.py", line 948, in __getattr__
    f"{self.__class__} object has no attribute '{item}'"
AttributeError: <class 'openforcefield.typing.engines.smirnoff.parameters.vdWHandler'> object has no attribute '_method'
```

**Computing environment (please complete the following information):**
 - `openforcefield =0.7.2`

**Comment by mattwthompson** [comment]
This is pretty nasty, or at least I've had a difficult time wrapping my head around the intricacies of these classes. It looks like `_method` is never set when constructing a `vdWHandler` manually, but it is when explicitly constructing it with the default value.

```python3
In [1]: from openforcefield.typing.engines.smirnoff.parameters import vdWHandler


In [2]: vdw_handler = vdWHandler(version=0.3)

In [3]: vdw_handler.method
Out[3]: 'cutoff'

In [4]: try:
   ...:     print(vdw_handler._method)
   ...: except AttributeError:
   ...:     print('could not find _method')
   ...:
could not find _method

In [5]: vdw_handler2 = vdWHandler(version=0.3, method='PME')

In [6]: vdw_handler2.method
Out[6]: 'PME'

In [7]: vdw_handler2._method
Out[7]: 'PME'
```

I don't fully understand what's going on here, but it looks like `_method` would only be set with this magic method:

https://github.com/openforcefield/openforcefield/blob/e8d89f8625b3faf9cafa302f5451da0a831ca1a4/openforcefield/typing/engines/smirnoff/parameters.py#L277-L278

which is called whenever its "owner" (in this case, `vdWHandler`) is "created," but a print debug shows that it's only being called on import time, and not construction. Which does not seem consistent with the observation that the arguments passed at construction time matter. Confusing.

https://docs.python.org/3/reference/datamodel.html#object.__set_name__
