### ISSUE TITLE
AmberToolsToolkitWrapper reports different fractional bond orders if OpenEye is installed/available

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield#736]
**Describe the bug**
I'm getting different behavior from using AmberTools to assign fractional bond order.
**To Reproduce**
In a conda [environment](https://gist.github.com/7fcc91e12669893887708f9b8b9b0fdc) _with_ OpenEye toolkits:
```python3
In [1]: from openforcefield.tests.test_forcefield import create_ethanol
   ...: mol = create_ethanol()
   ...: from openforcefield.utils.toolkits import *
   ...: AmberToolsToolkitWrapper().assign_fractional_bond_orders(mol)
   ...: mol.get_bond_between(1, 2).fractional_bond_order

Out[1]: 0.99529355

```

In a conda [environment](https://gist.github.com/34fadd4229f2618d92a01369db376ffd) _without_ OpenEye toolkits:

```python3
In [1]: from openforcefield.tests.test_forcefield import create_ethanol
   ...: mol = create_ethanol()
   ...: from openforcefield.utils.toolkits import *
   ...: AmberToolsToolkitWrapper().assign_fractional_bond_orders(mol)
   ...: mol.get_bond_between(1, 2).fractional_bond_order
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing

Out[1]: 1.00093035
```

```python3
In [1]: from openforcefield.tests.test_forcefield import create_ethanol
   ...: mol = create_ethanol()
   ...: from openforcefield.utils.toolkits import *
   ...: AmberToolsToolkitWrapper().assign_fractional_bond_orders(mol, bond_order_model="am1-wiberg")
   ...: mol.get_bond_between(1, 2).fractional_bond_order

Out[1]: 0.99529355

In [2]: GLOBAL_TOOLKIT_REGISTRY.deregister_toolkit(OpenEyeToolkitWrapper)

In [3]: mol = create_ethanol()

In [4]: AmberToolsToolkitWrapper().assign_fractional_bond_orders(mol, bond_order_model="am1-wiberg")

In [5]: mol.get_bond_between(1, 2).fractional_bond_order
Out[5]: 1.00093035
```
So my hypothesis is that this depends on if OpenEye toolkits are installed (and licensed, and available). Feel free to test this hypothesis on your computer. Is there some reason that having OpenEye toolkits installed should change the behavior of AmberTools?

**Output**
The full error message (may be large, that's fine. Better to paste too much than too little.)

**Computing environment (please complete the following information):**
Everything above was reproduced on macOS 10.15.7. On a Linux cluster (without an OpenEye license) the snippet gives me 1.0009. A [GitHub runner](https://github.com/mattwthompson/gha-sandbox/runs/1210351994?check_suite_focus=true#step:7:13) that lacks an OpenEye license also gives 1.0009. The [unit tests](https://github.com/openforcefield/openforcefield/actions/runs/285155748) in #705 only fail if both RDKit and OpenEye are installed.

**Additional context**
My first guess was that the `antechamber` call might some how default to using OpenEye to read MOL2 files, but that uses SDF files (and wouldn't explain reading literally different values from disk or a memory object).

I'm not sure how much the third decimal place of bond orders matters in general terms, but such differences will definitely produce different force constants with bond interpolation. And I'd argue that even if the difference was inconsequential, having an extra toolkit installed shouldn't affect the behavior of a toolkit call.

I've had my coffee this morning - did I also take crazy pills?

**Comment by j-wags** [comment]
The problem is likely [here](https://github.com/openforcefield/openforcefield/blob/0.7.2/openforcefield/utils/toolkits.py#L4558). Since this doesn't specify a ToolkitWrapper, it calls the `GLOBAL_TOOLKIT_REGISTRY`, which will produce an OE-generated conformer if OE is available. 

The solution can build off another hack. Basically, [`AmberToolsToolkitWrapper` actually owns an `RDKitToolkitWrapper` of its own](https://github.com/openforcefield/openforcefield/blob/0.7.2/openforcefield/utils/toolkits.py#L4161). This is needed because AmberTools can only read things from disk, which means that the OpenFF Toolkit needs to have a way to convert OFFMols to SDF to work with AmberTools. 

So, the solution here is probably to change the first link from
```
temp_mol.generate_conformers(n_conformers=1)
```
to
```
temp_mol.generate_conformers(n_conformers=1, toolkit_registry=self._rdkit_toolkit_wrapper)
```

**Comment by mattwthompson** [comment]
That works perfectly! Let me see if I can add reproduce this in a unit test and I'll submit a patch

**Comment by j-wags** [comment]
Thanks. Feel free to make it part of your current PR.
