### ISSUE TITLE
Make non-standard serialization dependencies optional

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/openforcefield#772]
**Is your feature request related to a problem? Please describe.**
In https://github.com/conda-forge/staged-recipes/pull/13234#discussion_r523457715, @jaimergp noticed several serialization-only dependencies in our existing conda recipe. It might be useful to have these packaged as optional dependencies. This would require patching the toolkit (probably [here](https://github.com/openforcefield/openforcefield/blob/1183ea03102212a5da3df092a359bc63990b98c0/openforcefield/utils/serialization.py#L23)) to fail gracefully if their corresponding methods are requested.

**Describe the solution you'd like**
Something similar to what's currently done with QCElemental as a optional [feature](https://github.com/openforcefield/openforcefield/blob/1183ea03102212a5da3df092a359bc63990b98c0/openforcefield/topology/molecule.py#L4482-L4488) or [testing](https://github.com/openforcefield/openforcefield/blob/1183ea03102212a5da3df092a359bc63990b98c0/openforcefield/tests/test_molecule.py#L68-L71) dependency. The OpenEye Toolkits are similar in that they are optional, but its implementation is more complex than should be needed here.

**Describe alternatives you've considered**
We could just always package them, but it's better practice to avoid requirements that is neither essential to core functionality nor likely to be encountered by most users.

**Additional context**

**Comment by SimonBoothroyd** [comment]
Big +1 to this - the fewer optional dependencies included by default the better!

In `openff-recharge` I handle this with a decorator pattern: [example usage](https://github.com/openforcefield/openff-recharge/blob/master/openff/recharge/smirnoff/smirnoff.py), [implementation](https://github.com/openforcefield/openff-recharge/blob/2458d8536bd7d510c971fcdd25c2515643738a94/openff/recharge/utilities/utilities.py#L80)
