### ISSUE TITLE
No module named openforcefield.topology

### ISSUE THREAD

**Issue by DBurns-Lab** [openforcefield/openforcefield#798]
Hi,

I must be missing something very obvious.  

I'm in a conda environment on Mac OSX 10.13.6 with openforcefield installed.

from openforcefield.topology import Topology

No module named 'openforcefield.topology'

"import openforcefield" does not return any errors

My openforcefield version doesn't look like the latest but I have "conda updated it" and installed it with the omnia and conda-forge added to available channels.

openforcefield            0.0.4                    py37_1    omnia
openmm                    7.4.1           py37_cuda101_rc_1    omnia
openmmtools               0.17.0                   py37_0    omnia
openmoltools              0.8.4                    py37_1    omnia

I'm trying to follow https://github.com/openforcefield/openforcefield/blob/master/examples/swap_amber_parameters/swap_existing_ligand_parameters.ipynb

Thank you,

Dan

**Comment by DBurns-Lab** [comment]
I created a new conda environment and followed the same install steps but now have the latest version of openforcefield.

**Comment by mattwthompson** [comment]
(Looks like you've found the solution - I'll post this anyway in case it's of use to passersby)

That version of the toolkit is very out of date, probably predating the `openforcefield.topology` module but certainly more out of date than we'd recommend using. This doesn't mean you've done anything wrong - `conda update` typically, and often silently, gives bad solutions when there are several moving parts and some old things installed. I'd recommend either removing some packages and re-installing them (you'd think this is what `conda update` can reliably do, but that isn't always the case) or making a new environment altogether.

### Make a new environment

Recommended if the environment is mostly used for OpenFF and doesn't need many other packages installed into it. Note that this is not much different from the [docs](https://open-forcefield-toolkit.readthedocs.io/en/latest/installation.html), but explicitly installing into a separate environment:
```
$ conda create --name openff
$ conda activate openff
$ conda install "python=3.7" openforcefield openmmtools -c conda-forge -c omnia
```

### Remove and re-install

Recommended if `conda update` is stuck with old versions and making a new environment is undesirable
```
$ conda remove --force openforcefield openmm openmmtools --yes
$ conda install openforcefield openmmtools -c conda-forge -c omnia --yes
```


Either approach should grab `openforcefield` 0.8.x or newer and `openmm` 7.5 as of today.

**Comment by DBurns-Lab** [comment]
Thanks Matt!

I can post the following on the git issues page if it’s appropriate - or wherever you’d recommend - I saw that the forum is not yet running.

Is this the best tutorial on how to set up a system with a Smirnoff parameterized small molecule?  https://github.com/openforcefield/openforcefield <https://github.com/openforcefield/openforcefield>

I’ve always used gromacs.  I’m trying to set up an openmm simulation and parameterize the ligand with Smirnoff but I’m getting really confused.  

You have to use parmed?  I thought there might be some simple solution if you already have the ligand/protein pdf file.  I am trying to use the smiles format in combination with the way my ligand atoms are arranged in the pdb with:

ligand_off_molecule = Molecule.from_smiles('C=C(OP(=O)([O-])[O-])C(=O)[O-]')
ligand_pdbfile = PDBFile('PEP1.pdb')
ligand_off_topology = Topology.from_openmm(ligand_pdbfile.topology, 
                                           unique_molecules=[ligand_off_molecule])

force_field = ForceField('openff_unconstrained-1.0.0.offxml')

ligand_system = force_field.create_openmm_system(ligand_off_topology)
new_ligand_structure = parmed.openmm.load_topology(ligand_off_topology.to_openmm(),
                                                   ligand_system,
                                                   xyz=ligand_pdbfile.positions)

The atoms end up being named differently that in my pdb and when I try to save the structure I get:
string index out of range

Thank you,


Dan

**Comment by mattwthompson** [comment]
For now, yes, you have to go through ParmEd. We're working on a solution that takes out the middleman (or middlemen, plural? as it knocks out the OpenMM step as well), but that won't be ready for few months.

Could you post the full traceback of your error? There are a few different points that error could be raised.

**Comment by DBurns-Lab** [comment]
Hi Matt,

One additional thing that would be great is a way to specify the box type to use (dodecahedron).

Here is the traceback.  Thanks for looking at it.

I try to save with:
new_ligand_structure.save('pep_smirnoff.pdb', overwrite=True)

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-75-bad5d5de3dac> in <module>
----> 1 new_ligand_structure.save('pep_smirnoff.pdb', overwrite=True)

/opt/anaconda3/envs/openmm-env/lib/python3.9/site-packages/parmed/structure.py in save(self, fname, format, overwrite, **kwargs)
   1473             # Dispatch
   1474             if format == 'PDB':
-> 1475                 self.write_pdb(fname, **kwargs)
   1476             elif format == 'CIF':
   1477                 self.write_cif(fname, **kwargs)

/opt/anaconda3/envs/openmm-env/lib/python3.9/site-packages/parmed/formats/pdb.py in write(struct, dest, renumber, coordinates, altlocs, write_anisou, charmm, use_hetatoms, standard_resnames, increase_tercount, write_links)
    972                     # Do any necessary name munging to respect the PDB spec
    973                     aname = _format_atom_name_for_pdb(pa)
--> 974                     resname, hetatom = standardize(res.name)
    975                     if hetatom:
    976                         rec = hetatomrec

/opt/anaconda3/envs/openmm-env/lib/python3.9/site-packages/parmed/formats/pdb.py in <lambda>(x)
    923             standardize = lambda x: _standardize_resname(x)[:reslen]
    924         else:
--> 925             standardize = lambda x: (x[:reslen], _is_hetatm(x))
    926         nmore = 0 # how many *extra* atoms have been added?
    927         last_number = 0

/opt/anaconda3/envs/openmm-env/lib/python3.9/site-packages/parmed/formats/pdb.py in _is_hetatm(resname)
     91     """
     92     if len(resname) != 3:
---> 93         return not (RNAResidue.has(resname) or DNAResidue.has(resname))
     94     return not (AminoAcidResidue.has(resname) or RNAResidue.has(resname)
     95                 or DNAResidue.has(resname))

/opt/anaconda3/envs/openmm-env/lib/python3.9/site-packages/parmed/residue.py in has(cls, thing)
     48             return thing in cls.all_residues
     49         try:
---> 50             cls.get(thing)
     51         except KeyError:
     52             return False

/opt/anaconda3/envs/openmm-env/lib/python3.9/site-packages/parmed/residue.py in get(cls, key)
    261         """
    262         try:
--> 263             if key[-1] in '35':
    264                 return cls._all_residues_by_abbr[key[:-1].upper()]
    265             return cls._all_residues_by_abbr[key.upper()]

IndexError: string index out of range

**Comment by mattwthompson** [comment]
First, back to the top - is this line loading in the protein or ligand? A protein PDB slipping in might explain the mismatches of numbers of atoms

> ligand_pdbfile = PDBFile('PEP1.pdb')

These other issues are a little downstream of what we currently support, but I can point you in the right direction:

1. The traceback relates to ParmEd errors, maybe relating to non-standard residues. It's hard to decipher at first glance but might be related to loading in a wrong PDB file? If not, maybe worth reporting on their issue tracker (perhaps with attached files, etc.): https://github.com/ParmEd/ParmEd/issues
2. OpenMM supports triclinic boxes, of which I believe dodecahedrons is a type. If you can wrestle it into 3x3 box vectors, you can set that on the OpenMM `System` or `Context` objects; it can also be set in ParmEd with the `.box` setter
  * http://docs.openmm.org/7.5.0/api-python/generated/simtk.openmm.openmm.System.html#simtk.openmm.openmm.System.setDefaultPeriodicBoxVectors and/or
  * http://docs.openmm.org/7.5.0/api-python/generated/simtk.openmm.openmm.Context.html#simtk.openmm.openmm.Context.setPeriodicBoxVectors
  * https://parmed.github.io/ParmEd/html/structobj/parmed.structure.Structure.html#parmed-structure-structure (scroll down to `box`)

Lots of moving parts, I know  - we're working on ways to simplify several of these added complexities and reduce the number of external dependencies for relatively "simple" workflows like this.

**Comment by DBurns-Lab** [comment]
You guys are doing great work.  I can see how Openmm can be a much smoother approach to simulations than other packages once I get it figured out.

That pdb file is only the 12 small molecule atoms.  I will look at this some more.  Thank you - Happy New Year!

Dan
