### ISSUE TITLE
Write API documentation

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#82]
We should probably add true API documentation beyond the `README.md`.

Sphinx can produce nice API docs with customizable formatting, and is probably a good choice for this project as well. Here are some examples:
* [mdtraj](http://mdtraj.org/)
* [openmmtools](http://openmmtools.readthedocs.io/en/latest/)
* [openmm](http://docs.openmm.org/latest/api-python/index.html)
* [numpy](https://docs.scipy.org/doc/numpy/reference/)

Would we be OK with readthedocs, or is that too unprofessional? Here are some examples:
* [openmmtools](http://openmmtools.readthedocs.io/en/latest/)
* [protons](http://protons.readthedocs.io/en/latest/)

We could alternatively push the docs to an S3 bucket like we do with [yank](http://getyank.org/), but we'd then have to integrate that into the openforcefield.org website content.

**Comment by jchodera** [comment]
The [Sphinx Bootstrap theme](http://ryan-roemer.github.io/sphinx-bootstrap-theme/README.html) looks cleaner and more modern, and might be a good choice for us.

**Comment by davidlmobley** [comment]
Looks good to me. I don't have any experience using Sphinx, but it looks nice and I agree we need to work on the docs.

**Comment by jchodera** [comment]
Any preferred styles?

**Comment by davidlmobley** [comment]
Of those I definitely like the Sphinx Bootstrap theme best.

**Comment by jchodera** [comment]
The infrastructure has been implemented in #85.

Here's a preview: http://open-forcefield-toolkit.readthedocs.io/en/latest/

**Comment by davidlmobley** [comment]
Closed via #85 .

Lots of documentation needs writing though.

**Comment by davidlmobley** [comment]
Renaming to "write API documentation" since now infrastructure is in place.
