### ISSUE TITLE
Add example Jupyter notebooks to online docs

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openforcefield#87]
We can also add example Jupyter notebooks to the sphinx docs using the already-installed [`nbsphinx`](https://nbsphinx.readthedocs.io/en/0.2.18/) package.

**Comment by davidlmobley** [comment]
That sounds nice. Perhaps we need to get the CI testing of the notebooks working before we do that though?

**Comment by jchodera** [comment]
We should likely migrate to `py.test` so we can use [this plugin](https://github.com/computationalmodelling/nbval) for that. I'll create a new issue.
