### ISSUE TITLE
`createSystem` has nonfunctional argument `rigidWater`

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#91]
The `rigidWater` argument in `createSystem` is nonfunctional at present -- it only occurs in the function definition and doc string and nowhere else. This is certainly a bug, though it's not clear to me yet how severe a bug. 

@slochower has run into some issues converting systems containing water with ParmEd (https://github.com/ParmEd/ParmEd/issues/930) and this seems to be at least partly related (though I have hydration free energy calculations with SMIRNOFF working elsewhere, so I'm not totally clear yet on what's different in his workflow).

**Comment by jchodera** [comment]
Per our discussions today, I'll be removing most of these optional arguments and will add a way to raise an exception if any optional arguments are unused by the force generators.

**Comment by davidlmobley** [comment]
@j-wags is this one resolved now?

**Comment by andrrizzi** [comment]
Yes, I think we have this implemented.
