### ISSUE TITLE
File naming convention improvement: .ffxml -> .offxml

### ISSUE THREAD

**Issue by davidlmobley** [openforcefield/openforcefield#92]
At the meeting, I mentioned (and it was agreed to) that we will try to name our force field files using the extension `.offxml` rather than `.ffxml` to reduce the temptation for people to say, "Well, this is just a normal .ffxml file like OpenMM uses for force field libraries, so I should be able to use it with OpenMM's `createSystem`", and the to contact us when it doesn't work. Using the `.offxml` extension will make it more clear that these are not the same at all.

**Comment by bannanc** [comment]
This was done in PR #101 I'm going to close this issue now
