### ISSUE TITLE
Unable to install openforcefield package

### ISSUE THREAD

**Issue by ocmadin** [openforcefield/openforcefield#97]
When trying to install the openforcefield package using `conda install --yes -c conda-forge -c omnia openforcefield`, I am getting the following error: 

"PackagesNotFoundError: The following packages are not available from current channels:

-openforcefield"

It then lists the URLs of my current channels (which I can attach if need be), which are just default, conda-forge, and omnia. I've tried removing and re-adding conda-forge and omnia, but no luck; I've also installed several other omnia packages without issue.
I apologize is this is an easily fixable issue and on my end (I'm new at this), but I was wondering if there is any insight into why this could be happening.

-Owen

**Comment by davidlmobley** [comment]
Are you sure you didn't type `conda install --yes -c conda-forge -c omnia -openforcefield` instead of `conda install --yes -c conda-forge -c omnia openforcefield? I just tested the correct command in a fresh conda environment and it's working for me, so I'm unsure why you wouldn't be seeing it.

What platform are you on?

**Comment by ocmadin** [comment]
Yes, I double checked that the command was correct.  I'm using python 3.6 on windows 10.

**Comment by ocmadin** [comment]
Okay, I tried downloading YANK as a test and got the same error, so it seems like it may be on my end.  I'll do some more troubleshooting

**Comment by ocmadin** [comment]
Yeah, just a me/windows issue.  Works fine on linux!

**Comment by davidlmobley** [comment]
OK, thanks. Ugh, windows. :(

**Comment by Lnaden** [comment]
If its Windows 10, you could install the Linux Subsystem and get native linux terminal and support in Windows.... Not sure how well that works, but hey!

**Comment by davidlmobley** [comment]
I've used that some for a class I teach, @Lnaden . It's better than nothing but there are more snags than one might like. I ended up having my students just boot from a persistent USB (Ubuntu) because it's so much easier for me to support.
